- adbc.h
- adbc_driver_manager/adbc_driver_manager.cc
- adbc_driver_manager/adbc_driver_manager.h
- adbc_driver_manager/adbc_driver_manager_test.cc
- drivers/flight_sql/flight_sql.cc
- drivers/sqlite/sqlite.cc
- drivers/test_util.h
It's hard for the driver manager to allocate/free errors since it
would have to manually intercept all calls. Also, it makes it hard
to provide error messages when there is no driver. Move the error
release callback to the error structure itself to make this easier.
> Refactor error handling

- adbc.h
- adbc_driver_manager/adbc_driver_manager.cc
- adbc_driver_manager/adbc_driver_manager_test.cc
- drivers/sqlite/sqlite.cc
- drivers/sqlite/sqlite_test.cc
Clarify that autocommit is the default, add an option to disable it, and add an explicit commit.
Fixes #23.
> Add basic transaction semantics

- .github/workflows/cpp.yml
- .pre-commit-config.yaml
- adbc_driver_manager/adbc_driver_manager_test.cc
- ci/build_support/sanitizer-disallowed-entries.txt
- cmake_modules/AdbcDefines.cmake
- cmake_modules/san-config.cmake
- drivers/flight_sql/flight_sql.cc
- drivers/flight_sql/flight_sql_test.cc
- drivers/sqlite/sqlite.cc
- drivers/sqlite/sqlite_test.cc
- drivers/test_util.h
Doesn't enable clang-tidy since that needs some integration with the build process.
Fixes #22.
> Enable ASan/UBSan/cpplint

- .flake8
- .github/workflows/cpp.yml
- .isort.cfg
- .pre-commit-config.yaml
- adbc_driver_manager/adbc_driver_manager.cc
- ci/conda_env_python.txt
- python/adbc_driver_manager/.gitignore
- python/adbc_driver_manager/adbc_driver_manager/__init__.py
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/tests/test_lowlevel.py
- python/adbc_driver_manager/requirements-dev.txt
- python/adbc_driver_manager/setup.py
These bindings are structured as a low-level module that mostly
mirrors the ADBC API, and a TBD high-level module that will
implement PEP 249 (except with Turbodbc-style extensions).
This PR is just to get the module set up, with features in future PRs.
> Add skeleton of Python bindings

- adbc.h
- adbc_driver_manager/adbc_driver_manager.cc
- adbc_driver_manager/adbc_driver_manager_test.cc
- drivers/flight_sql/flight_sql.cc
- drivers/flight_sql/flight_sql_test.cc
- drivers/sqlite/sqlite.cc
- drivers/sqlite/sqlite_test.cc
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
Make AdbcConnectionNew consistent with AdbcDatabaseNew.
This mostly doesn't affect the driver implementations; it does make the driver manager a little more complex.
> Make AdbcConnectionNew 2-adic for consistency

- java/driver/validation/pom.xml
Updated relative path for parent pom in validation module. This fixes the following build error
[ERROR]     Non-resolvable parent POM for org.apache.arrow.adbc:adbc-driver-validation:9.0.0-SNAPSHOT: Could not find artifact org.apache.arrow.adbc:arrow-adbc-java-root:pom:9.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 11 -> [Help 2]
> Updated relative path for parent pom

- .gitignore
- adbc.h
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager_test.cc
- c/drivers/sqlite/sqlite.cc
- c/drivers/sqlite/sqlite_test.cc
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcInfoCode.java
- java/core/src/main/java/org/apache/arrow/adbc/core/StandardSchemas.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/InfoMetadataBuilder.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnection.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/ObjectMetadataBuilder.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java
- python/adbc_driver_manager/.gitignore
- python/adbc_driver_manager/adbc_driver_manager/__init__.py
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/tests/test_lowlevel.py
- python/adbc_driver_manager/setup.py
Add a ConnectionGetInfo function to query basic metadata, like the driver/database name and version. This doesn't yet expose all the of the metadata that Flight SQL exposes, but otherwise follows a very similar design (including the use of integer metadatum IDs and a union of possible result types).
> [C][Java][Python] Add GetInfo

- c/drivers/postgres/CMakeLists.txt
- c/drivers/postgres/README.md
- c/drivers/postgres/connection.cc
- c/drivers/postgres/connection.h
- c/drivers/postgres/database.cc
- c/drivers/postgres/database.h
- c/drivers/postgres/postgres.cc
- c/drivers/postgres/postgres_test.cc
- c/drivers/postgres/statement.cc
- c/drivers/postgres/statement.h
- c/drivers/postgres/type.cc
- c/drivers/postgres/type.h
- c/drivers/postgres/util.h
- c/validation/adbc_validation.c
The driver supports basic queries (int32 only) and toggling autocommit. It does not yet support bulk ingestion or prepared statements.
It hasn't been optimized for speed and the approach taken here will not be fast (it uses the per-row getters). In future PRs, we should set up some benchmarks and then see if DuckDB's approach makes more sense (use `COPY`). DuckDB also does multithreading (that might be hard for us). We may want to implement #61 first since then we will know whether it is safe to use `COPY` or not.
> [C] Basic libpq-based driver

- c/cmake_modules/BuildUtils.cmake
- c/driver_manager/AdbcDriverManagerConfig.cmake.in
- c/driver_manager/CMakeLists.txt
> [C] Add support for CMake package

- adbc.h
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager_test.cc
- c/drivers/flight_sql/flight_sql.cc
- c/drivers/postgres/postgres.cc
- c/drivers/postgres/statement.cc
- c/drivers/postgres/statement.h
- c/drivers/sqlite/sqlite.cc
- c/drivers/sqlite/sqlite_test.cc
- c/validation/adbc_validation.c
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java
- java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlConnection.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractPartitionDescriptorTest.java
- java/pom.xml
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
In C: combine ExecuteQuery/ExecuteUpdate since they're redundant
In Java: rename some things to be consistent with C. However, do not consolidate ExecuteQuery/ExecuteUpdate since the lack of out parameters means we don't have a way to differentiate the cases.
> [Format][C][Java] Consolidate ExecuteQuery/ExecuteUpdate

- .github/workflows/cpp.yml
Turns out we suddenly don't need the DYLD_LIBRARY_PATH workaround anymore and it in fact is harmful instead
> [C] Fix MacOS CI

- NOTICE.txt
- adbc.h
- c/cmake_modules/AdbcDefines.cmake
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager.h
- c/driver_manager/adbc_driver_manager_test.cc
- c/drivers/flight_sql/flight_sql.cc
- c/drivers/postgres/postgres.cc
- c/drivers/sqlite/sqlite.cc
- java/core/pom.xml
- java/core/src/main/java/org/apache/arrow/adbc/core/package-info.java
- java/driver-manager/pom.xml
- java/driver/flight-sql-validation/pom.xml
- java/driver/flight-sql/pom.xml
- java/driver/jdbc-util/pom.xml
- java/driver/jdbc-validation-derby/pom.xml
- java/driver/jdbc-validation-postgresql/pom.xml
- java/driver/jdbc/pom.xml
- java/driver/validation/pom.xml
- java/pom.xml
- java/sql/pom.xml
- java/sql/src/main/java/org/apache/arrow/adbc/sql/package-info.java
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgres/pyproject.toml
> [Format] Document API/ABI stability goals

- .gitignore
- c/drivers/sqlite/CMakeLists.txt
I was curious about the SQLite driver, so I did a quick clone and ran VSCode's default CMake: Configure, CMake: Build, and CMake: Run Tests. It almost worked out of the box, but I got some build errors, I needed a build preset to specify where Arrow was, and I ended up with a lot of untracked build files. This is my take on how to make that a smooth process for a new contributor...feel free to suggest something else!
> [C] Make it easier to build the SQLite driver out of the box

- adbc.h
Make things a little easier for implementors so they can just copy-paste the function declarations (and remove comments/defines).
Fixes #145.
> style(format): rearrange header to group functions together

- c/driver/postgres/CMakeLists.txt
- c/driver/postgres/postgres_test.cc
- c/driver/sqlite/CMakeLists.txt
- c/driver_manager/CMakeLists.txt
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
- c/validation/adbc_validation_util.cc
- c/validation/adbc_validation_util.h
This makes the utilities easier to use when writing driver-specific tests using Nanoarrow.
> refactor(c/validation): split out test utilities

- c/cmake_modules/AdbcDefines.cmake
- c/driver/postgres/CMakeLists.txt
- c/driver/postgres/postgres_test.cc
- c/driver/postgres/statement.cc
- ci/scripts/python_wheel_unix_test.sh
- glib/Gemfile
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_manager/tests/test_dbapi.py
- python/adbc_driver_manager/tests/test_lowlevel.py
- python/adbc_driver_postgres/adbc_driver_postgres/__init__.py
- python/adbc_driver_postgres/tests/test_lowlevel.py
- ruby/Gemfile
- Link to nanoarrow
- Build nanoarrow with -fPIC
- Run tests on Python wheels
- Correctly import `importlib.resources`
- Fake support for prepared statements returning result sets, to satisfy how the DBAPI adapter works
> fix(c/driver/postgres): fix wheel builds

- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi.py
Extend the DBAPI interface with methods to expose ADBC functionality that doesn't have equivalents in DBAPI.
> feat(c/driver_manager): expose ADBC functionality in DBAPI layer

- .github/workflows/packaging-wheels.yml
- ci/scripts/java_jar_upload.sh
Because the first stage is run in Docker, it creates files we can read but not overwrite.
> ci(java): skip RAT check on JAR upload

- python/adbc_driver_manager/adbc_driver_manager/_version.py
- python/adbc_driver_postgres/adbc_driver_postgres/_version.py
miniver assumes tag formats like `v0.1.0`, adjust it to work with `adbc-0.1.0`
> fix(c/driver_manager,c/driver/postgres): fix version inference from tags

- c/driver_manager/CMakeLists.txt
- c/driver_manager/adbc_driver_manager_test.cc
After this, we just need to port the SQLite driver.
> refactor(c/driver_manager): remove unnecessary libarrow dependency

- .github/workflows/nightly-website.yml
This adds the action, but does not actually add the .asf.yaml setup (I'll follow up with that separately).
The idea is to target `arrow.apache.org/adbc/docs` here. Then `dev/` will be a subtree, as demoed here: https://github.com/lidavidm/arrow-adbc/tree/asf-site
We can't use `docs/adbc/` and `docs/dev/adbc/` because we can only target a single directory at a time.
Also,  I'd like to add an `arrow.apache.org/adbc/index.html` at some point to the main arrow-site repo. That can serve as a brief project introduction that links to the various documentation subtrees.
> ci(docs): add automatic site rebuild

- .github/workflows/packaging-wheels.yml
- ci/scripts/python_wheel_unix_build.sh
- ci/scripts/python_wheel_windows_build.bat
It turns out even with `fetch-depth: 0`, the checkout action doesn't seem to properly fetch tags.
> ci: fix versioning of wheels in CI

- .asf.yaml
As discussed on https://github.com/apache/arrow/pull/14811#issuecomment-1336109840 this will add the opened and closed issues notification emails to issues@apache.org
> chore: add issues notification of issues opened and closed to issues mailing list

- .github/workflows/packaging-wheels.yml
- NOTICE.txt
- ci/docker/python-wheel-manylinux.dockerfile
- ci/scripts/python_sdist_build.sh
- ci/scripts/python_sdist_test.sh
- ci/scripts/python_util.sh
- ci/scripts/python_wheel_fix_tag.py
- ci/scripts/python_wheel_unix_build.sh
- ci/scripts/python_wheel_unix_test.sh
- ci/vcpkg/0001-Work-around-inconsistent-path.patch
- ci/vcpkg/0002-Retry-downloads.patch
- ci/vcpkg/triplets/arm64-linux-static-release.cmake
- ci/vcpkg/triplets/arm64-osx-static-release.cmake
- docker-compose.yml
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgres/pyproject.toml
- python/adbc_driver_postgres/setup.py
- python/adbc_driver_sqlite/pyproject.toml
- python/adbc_driver_sqlite/setup.py
- Use cibuildwheel for adbc_driver_manager
- Consolidate the different Python version builds into a single job
- Split the job by architecture instead
> ci: add AArch64 wheels via cross-compilation

- python/adbc_driver_manager/adbc_driver_manager/_version.py
- python/adbc_driver_postgres/adbc_driver_postgres/_version.py
- python/adbc_driver_sqlite/adbc_driver_sqlite/_version.py
This is needed for Conda packages, which build from Git checkouts and do not know the actual version.
Part of #229.
> refactor(python): allow overriding package version

- ci/linux-packages/Rakefile
Noticed when doing a dry-run of the release: https://github.com/lidavidm/arrow-adbc/actions/runs/3758626322/jobs/6387192369#step:8:33
> ci: fix typo in Rakefile

- .github/workflows/packaging.yml
> ci: disable Linux packaging builds for RCs for now

- docs/source/development/releasing.rst
Reduces clutter in generated changelogs.
Fixes #269.
> chore(dev/release): update instructions for maint branches

- dev/release/05-linux-upload.sh
Fixes #275.
Because "mv -t" isn't portable.
> chore(dev/release): use "find -exec" instead of "xargs mv -t"

- dev/release/verify-release-candidate.sh
Doesn't need to be in 0.1.0 since I think adding a backoff (apache/arrow#15090) will suffice
> chore(dev/release): reduce parallelism when downloading from GitHub

- dev/release/verify-release-candidate.sh
I don't know why but Go modules are installed with `0444` permission.
Fixes #295.
> chore(dev/release): ensure temporary directory writable on cleanup

- dev/release/verify-release-candidate.sh
> chore(dev/release): use separated build directory for Go

- ci/scripts/glib_test.sh
If we can customize `PKG_CONFIG_PATH`, `LD_LIBRARY_PATH` and so on, we can use Apache Arrow C GLib installed in custom directory such as `/tmp/local/`.
Fixes #299.
> chore(dev/release): add support for customizing build related env vars

- .github/workflows/packaging.yml
- ci/scripts/gemfury_clean.rb
For this to work, we need to first add the API token. This is a different token than the one used for uploading packages.
Fixes #242.
> ci: clean old releases

- dev/release/post-08-website.sh
- dev/release/post-09-website.sh
- docs/source/development/releasing.rst
> chore(dev/release): add script to generate release post

- .github/workflows/cpp.yml
- ci/scripts/glib_test.sh
- dev/release/verify-release-candidate.sh
Fixes #350.
We don't need to set GEM_HOME for RubyGems install test. Because we don't use installed gems. We just want to test installation.
We can't use GEM_HOME environment variable on conda environment. Because conda's Ruby sets gemhome in etc/gemrc. We can't overwrite it by GEM_HOME environment variable.
So "--install-dir" is portable than GEM_HOME.
> fix(ci/ruby): revert GEM_HOME for RubyGems install test

- c/driver/postgresql/statement.cc
'varchar' and 'text' are really the same type so just need to add it to the supported list.
> feat(c/driver/postgresql): Add varchar type support

- go/adbc/driver/flightsql/flightsql_adbc.go
the Go flightsql driver connection object should implement PostInitOptions to allow setting options on it
> fix(go/adbc/driver/flightsql): cnxn should implement PostInitOptions

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
Experimentally, it was found that at runtime, sometimes Go handles
would be corrupted after crossing the FFI boundary. Heap-allocating
the handles appears to avoid this.
> fix(go/adbc/driver/flightsql): heap-allocate Go handles

- ci/docker/python-wheel-manylinux.dockerfile
- docker-compose.yml
This was making python-sdist-test flaky since we were accidentally starting up two docker-compose services which then trampled each other. Instead of trying to share image definitions, just copy-paste and let Docker figure out deduplication.
> fix(ci): don't make jobs depend on each other

- c/cmake_modules/GoUtils.cmake
This will properly build binaries for the target architecture when cross-compiling.
Fixes #373.
> fix(c/driver/flightsql): set GOARCH appropriately on macOS

- LICENSE.txt
- ci/scripts/go_license.sh
Since we statically link Go dependencies to generate the Arrow Flight SQL driver, we need to update LICENSE.txt to include the copyright notice.  (This includes Go itself, for the Go runtime.)
> chore: update LICENSE.txt to reflect statically linked Go deps

- docs/source/driver/go/flight_sql.rst
- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/flightsql/flightsql_statement.go
- Adds more connection options around TLS.
- Adds basic smoke tests for connection options.
- Error on unknown options.
- Serialize partitions as FlightInfo with one FlightEndpoint. This is verbose, but allows preserving any other metadata that may be added to Flight in the future.
Part of #380.
> feat(go/adbc/driver/flightsql): implement more connection options

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/sqldriver/driver.go
Two small changes:
- flightsql: allow basic authentication with username or password or both
- InfluxDB/IOx has a token authentication which ignores username
- sqldriver: allow queries without prepared statements
- InfluxDB/IOx does not support prepared statements (yet)
> feat(go/adbc/driver/flightsql,go/adbc/sqldriver): small improvements

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
- go/adbc/sqldriver/driver_test.go
Fix a small nit. My "passwords" are tokens, which are base64-encoded values, so they often have an equals sign `=` suffix.
FYI the added test does not pass on my local development environment, due to a cgo issue:
```# github.com/apache/arrow-adbc/go/adbc/drivermgr
adbc_driver_manager.cc:224:26: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
adbc_driver_manager.cc:225:32: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
adbc_driver_manager.cc:316:14: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
adbc_driver_manager.cc:316:27: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
adbc_driver_manager.cc:322:12: error: no member named …
```
> fix(go/adbc/sqldriver): allow equals signs in DSN values

- docs/source/driver/go/flight_sql.rst
- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/flightsql/flightsql_statement.go
- go/adbc/driver/flightsql/record_reader.go
- go/adbc/driver/flightsql/record_reader_test.go
Assume data may be ordered in absence of an explicit server-sent indicator.
Fixes #385.
> feat(go/adbc/driver/flightsql): change parallelization of DoGet

- ci/scripts/python_conda_upload.sh
> fix(ci): don't fail Anaconda upload when packages already exist

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
Closes #391 
Cause `sql.Rows.Scan(...)` to return `time.Time` for arrow types Time32, Time64, Timestamp, Date32, and Date64.
> feat(go/sqldriver): convert Arrow times and dates to Golang time.Time

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
Helps #391 
Expose the Arrow type names via `database/sql.ColumnType.DatabaseTypeName()` by implementing `database/sql/driver.RowsColumnTypeDatabaseTypeName` with `arrow.DataType.String()`. This method allows the consumer to infer, for example, the time unit of an `arrow.Timestamp` column.
> feat(go/sqldriver): implement database/sql/driver.RowsColumnTypeDatabaseTypeName

- ci/scripts/cpp_test.sh
- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
> fix(go/adbc/driver/driver/flightsql): use libc allocator

- .github/workflows/native-unix.yml
- go/adbc/driver/flightsql/record_reader.go
- go/adbc/driver/flightsql/record_reader_test.go
In case the FlightInfo schema doesn't match the DoGet schema, return an error instead of allowing the client to misinterpret the result.
> fix(go/adbc/driver/flightsql): guard against inconsistent schemas

- ci/linux-packages/apt/debian-bookworm/Dockerfile
- dev/release/verify-apt.sh
Debian seems to have removed sources.list in favor of sources.list.d.
Fixes #420.
> chore(ci): update bookworm Dockerfile

- c/driver/flightsql/dremio_flightsql_test.cc
- go/adbc/driver/flightsql/flightsql_adbc.go
Some Flight SQL implementations, like Dremio, return no catalogs and instead have schemas live in an unnamed catalog. Handle these cases so you can still introspect metadata.
> fix(go/adbc/driver/flightsql): deal with catalogless schemas

- r/adbcdrivermanager/configure
After trying the install instructions for the R driver manager added in #365, we get rather scary message (although the install works just fine):
```
* installing *source* package ‘adbcdrivermanager’ ...
** using staged installation
Fatal error: cannot open file 'bootstrap.R': No such file or directory
Fetched ADBC from https://github.com/apache/arrow-adbc
** libs
```
This happens because bootstrap.R is in `.Rbuildignore`, so it doesn't end up in the built tarball. It's referenced from `configure` though (for when somebody is installing from the source directory, not a built tarball). This PR just adds a check for the file before attempting to run it.
> fix(r/adbcdrivermanager): Check that bootstrap.R exists before trying to run it

- go/adbc/drivermgr/wrapper.go
> build(go/adbc/drivermgr): explicitly set -std=c++11

- go/adbc/sqldriver/doc.go
- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/flightsql/README.md
- go/adbc/sqldriver/flightsql/flightsql.go
- go/adbc/sqldriver/flightsql/flightsql_test.go
Helps https://github.com/apache/arrow/issues/34332
Golang/FlightSQL docs should be updated to point here for the canonical `database/sql` wrapper.
> feat(golang/sqldriver): add simple FlightSQL database/sql driver wrapper

- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
> build(go/adbc/driver/flightsql): explicitly set -std=c++11

- go/adbc/LICENSE.txt
We can't symlink since pkg.go.dev won't follow symlinks to check
the license. So instead this is just a copy of the license. It's
only the core Apache license text, since the root license has all
the other details.
> docs(go): add LICENSE.txt so pkg.go.dev will display docs

- .github/workflows/native-unix.yml
- r/adbcdrivermanager/DESCRIPTION
Now that nanoarrow is on CRAN, we can use it like a regular dependency!
> chore(r): Drop references to nanoarrow R package on GitHub

- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi.py
This helps ensure we don't leak resources.  A warning will be raised when running under a 'test' environment to help developers catch issues.
Fixes #454.
> feat(python/adbc_driver_manager): add __del__ for resources

- ci/scripts/go_build.sh
- dev/release/verify-release-candidate.sh
- go/adbc/driver/flightsql/flightsql_adbc_test.go
Verification on macOS was failing because system git was getting confused by a Conda DYLD_LIBRARY_PATH. Use conda git instead.
Fixes #517.
> fix(ci): use conda git in verification

- .github/workflows/verify.yml
- ci/conda_env_r.txt
- dev/release/verify-release-candidate.sh
- r/adbcdrivermanager/DESCRIPTION
- r/adbcdrivermanager/configure
- r/adbcsqlite/.Rbuildignore
- r/adbcsqlite/configure
This PR adds the R packages into the bash-based verification script. The general idea is to run `R CMD INSTALL` then `R CMD check` on both packages but the bash is fairly verbose. My shell scripting is rather new and while I tried to follow patterns elsewhere I imagine there are improvements that could be made.
I didn't attempt Windows, mostly just because my PowerShell is non-existent. In theory the same set of commands would work.
> chore(r): Add R library verification to source verification script

- dev/release/verify-release-candidate.sh
If we use ci/scripts/ in local, we don't need to cut another RC when we find a problem in verification script.
Fixes #522.
> chore(release): Use ci/scripts/ in local instead of in source archive

- docs/source/development/releasing.rst
It seems that the directory name is different when the directory is created with the `git clone https://github.com/apache/arrow-adbc.git` command as per the procedure.
> docs: fix dir name created by git clone

- java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlQuirks.java
- java/driver/jdbc-validation-derby/src/test/java/org/apache/arrow/adbc/driver/jdbc/derby/DerbyQuirks.java
- java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/PostgresqlQuirks.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcArrowReader.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcBindReader.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnection.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriver.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractPartitionDescriptorTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractStatementTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractTransactionTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/SqlValidationQuirks.java
- java/pom.xml
* Close the allocator in JdbcConnection.
* Allow supplying an allocator to JdbcDriver.
* Fix miscellaneous memory leaks discovered from those changes.
Fixes #476.
Fixes #477.
> fix(java/driver/jdbc): clean up buffer leaks

- c/validation/adbc_validation.cc
When running the ADBC tests against the postgres driver you currently get output like:
```sh
[ RUN      ] PostgresStatementTest.Transactions
Failure message: [libpq] Failed to execute query: could not infer schema: ERROR:  relation "bulk_ingest" does not exist
LINE 1: SELECT * FROM bulk_ingest
^
[libpq] Query was: SELECT * FROM (SELECT * FROM bulk_ingest) AS ignored LIMIT 0
WARNING:  there is no transaction in progress
[       OK ] PostgresStatementTest.Transactions (47 ms)
```
This was pretty confusing on first glance because the test still passes. On closer inspection, I don't _think_ the stderr write in the test is intentional
> test(c/driver/postgresql): Remove errant test error message

- .gitignore
Going back to this conversation https://github.com/apache/arrow-adbc/pull/314#issuecomment-1373110668 I think useful to ignore this
> chore(c): Ignore .clangd file

- glib/adbc-glib/connection.c
- glib/adbc-glib/connection.h
- glib/test/helper.rb
- glib/test/test-connection.rb
Fixes #551.
New APIs:
* `gadbc_connection_set_auto_commit()`
* `gadbc_connection_commit()`
* `gadbc_connection_rollback()`
> feat(glib): add transaction related connection bindings

- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation.cc
Closes #578 and modifies the validation suite so that it will catch this type of accidental cast should it happen again.
> fix(c/driver/sqlite,c/validation): Ensure float/double values are not truncated on bind or select

- ci/conda_env_benchmarking.txt
- python/adbc_driver_postgresql/asv.conf.json
- python/adbc_driver_postgresql/benchmarks/__init__.py
- python/adbc_driver_postgresql/benchmarks/benchmarks.py
No setup for actually running them in CI for now (we also probably don't want that).
Fixes #568.
> test(python/adbc_driver_postgres): add benchmark suite via asv

- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite.c
- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation_util.h
- c/vendor/nanoarrow/nanoarrow.c
- c/vendor/nanoarrow/nanoarrow.h
- c/vendor/nanoarrow/nanoarrow.hpp
- c/vendor/vendor_nanoarrow.sh
Updates to the latest nanoarrow. In particular, this is needed to fix the Windows postgres driver packaging for R since the existing nanoarrow.hpp was creating some compiler errors.
> chore(c/vendor): Update vendored nanoarrow

- r/adbcpostgresql/.Rbuildignore
- r/adbcpostgresql/R/adbcpostgresql-package.R
- r/adbcpostgresql/man/adbcpostgresql.Rd
- r/adbcsqlite/R/adbcsqlite-package.R
- r/adbcsqlite/man/adbcsqlite.Rd
I believe the root of this is that the new R release contains a slightly modified check for S3 generic method implementations.
> chore: Fix CI failures reported for R driver packages

- java/driver-manager/src/main/java/org/apache/arrow/adbc/drivermanager/AdbcDriverManager.java
- java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlDriver.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriver.java
The old way was prone to memory leaks.
Fixes #563.
BREAKING CHANGE: removes static driver instances.
> fix(java)!: require supplying BufferAllocator to create drivers

- c/driver/snowflake/CMakeLists.txt
- ci/scripts/cpp_test.sh
- go/adbc/driver/snowflake/driver_test.go
Have the Go snowflake tests operate in their own schema that they cleanup to avoid clashing when multiple runs go at the same time.
> ci(go/adbc/driver/snowflake): Test cleanup and avoid clashes from multiple runs

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
The driver didn't handle NULL values at all! Fix this, and also instead of a homegrown array appender, just use NanoArrow. Simpler and less error prone!
Fixes #557.
> fix(c/driver/postgresql): properly handle NULLs

- c/driver/common/utils.c
- c/driver/postgresql/CMakeLists.txt
- c/driver/postgresql/connection.cc
- c/driver/postgresql/database.cc
- c/driver/postgresql/postgres_util.h
- c/driver/postgresql/postgresql.cc
- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite.c
- r/adbcpostgresql/bootstrap.R
- r/adbcpostgresql/src/Makevars.in
- r/adbcpostgresql/src/Makevars.ucrt
- r/adbcpostgresql/src/Makevars.win
- Use the new SetError with variadic arguments
- Replaced StringBuilder with some std::string concatenation where applicable
- Replaced any CHECK_ macro with the variant from either nanoarrow or existing util
- Renamed util.h -> postgres_util.h to disambiguate; right now this seems just scoped to utils for network byte swapping
> refactor(c/driver/postgresql): Remove utils duplication

- go/adbc/sqldriver/driver.go
In the `database/sql` `Rows.Next()` implementation, errors occurring within `array.RecordReader` were ignored, so that an error result appeared as an empty result.
> fix(go/adbc/sqldriver): do not swallow array.RecordReader error

- c/validation/adbc_validation.cc
A nested list was being indexed incorrectly, causing an out-of-bounds read. This didn't trigger before because no driver returned more than one row in the first place.
Fixes #647.
> fix(c/validation): correct indexing in TestMetadataGetObjectsTables

- c/cmake_modules/AdbcDefines.cmake
GoogleTest needs C++17 now; we still support C++11.
Fixes #650.
> build(c): only set CMAKE_CXX_STANDARD when building GoogleTest

- ruby/lib/adbc/connection.rb
- ruby/lib/adbc/statement.rb
Fixes #664.
The reader is invalid outside of the method. We must free the reader explicitly here to avoid a SEGV.
> feat(ruby): Free an imported reader in Statement#execute explicitly

- c/driver/postgresql/postgres_copy_reader.h
- ci/scripts/glib_test.sh
- ci/scripts/python_util.sh
- ci/scripts/python_wheel_unix_build.sh
- glib/Gemfile
- ruby/Gemfile
- ruby/red-adbc.gemspec
- skip Snowflake wheel on Linux/aarch64 too
- fix how we skip the Snowflake wheel to not skip all wheels
- fix compiler warning in PostgreSQL driver
- pin arrow-c-glib since red-arrow 12 came out but conda-forge does not yet have arrow-c-glib 12
Fixes #660.
Fixes #661.
Fixes #663.
> ci: 0.4.0 release fixes

- r/adbcdrivermanager/R/error.R
- r/adbcdrivermanager/tests/testthat/_snaps/driver_log.md
- r/adbcdrivermanager/tests/testthat/test-error.R
Before this PR, errors coming from ADBC were rather unhelpfully labelled:
``` r
db <- adbc_database_init(adbc_driver_void())
adbc_database_release(db)
adbc_database_release(db)
#> Error in stop_for_error(status, error): ADBC_STATUS_INVALID_STATE (6)
```
After this PR, the source of the error is better communicated and errors are given a custom class so they can be caught appropriately:
``` r
db <- adbc_database_init(adbc_driver_void())
adbc_database_release(db)
adbc_database_release(db)
#> Error in adbc_database_release(db): ADBC_STATUS_INVALID_STATE (6)
tryCatch({
db <- adbc_database_init(adbc_driver_void())
adbc_database_release(db)
adbc_database_release(db)
}, adbc_status_invalid_state = function(e) {
message(sprintf("Just warning …
```
> feat(r): Improve error communication

- go/adbc/go.mod
- go/adbc/go.sum
Snowflake finally released a new version of their lib as v1.6.21, so we can remove the `replace` directive and point at the version proper without needing to specify a specific commit.
> fix(go/adbc): Update snowflake dep

- r/adbcdrivermanager/R/adbc.R
- r/adbcdrivermanager/R/utils.R
- r/adbcdrivermanager/tests/testthat/test-radbc.R
I think initially I thought this would be useful for printing, but it turns out it's distressingly easy to print out/leak/expose secret credentials with the default print method:
``` r
uri <- Sys.getenv("ADBC_SNOWFLAKE_TEST_URI")
adbc_database_init(adbcsnowflake::adbcsnowflake(), uri = uri)
#> <adbcsnowflake_database> <pointer: 0x14f65c350> List of 2
#>  $ driver :<adbcsnowflake_driver_snowflake> List of 1
#>   ..$ driver_init_func:Class 'adbc_driver_init_func' <externalptr> 
#>  $ options:List of 1
#>   ..$ uri: chr "paleolimbot:ADBC44test@wt78143.ca-central-1.aws/SNOWFLAKE_SAMPLE_DATA/TPCH_SF1?role=ACCOUNTADMIN"
```
This PR nixes that whole system: if it's helpful to expose something it can be exposed by individual drivers. After this PR:
``` r …
```
> fix(r): Don't save database/connection/statement options at the R level

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/vendor/nanoarrow/nanoarrow.hpp
- python/adbc_driver_postgresql/tests/test_dbapi.py
Before we tried to infer the query schema before COPY by wrapping it in a "SELECT * FROM (...) LIMIT 0".  This broke if the query was (for example) a CREATE or UPDATE.  Instead, use a prepared statement to infer instead.  If we find that there are no result columns, then execute without the COPY path.
Also, test what happens with "INSERT INTO ... RETURNING" (this works with COPY).
Fixes #701.
> feat(c/driver/postgresql): handle non-SELECT statements

- .github/workflows/packaging.yml
An attempt to help close #687 by setting `fail-fast: false` on all jobs that have a matrix. 
In addition I applied the following changes:
- Set a default shell (`bash`) for all run steps (and remove them from steps that use that)
- Use [output parameters](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) instead of env vars to pass data between steps
- Add output of some "echo-only" steps to the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary)
- Renamed artifact of python sdit archive
- Some quoting changes
> chore(ci): disable fail-fast in package workflow jobs

- c/driver/postgresql/connection.cc
- c/driver/postgresql/postgresql_test.cc
You've mentioned a few other times that we need to start using a prepared statement instead of string appends for handling queries. Think we've hit that point with this PR.
Current plan is to make that prepared statement usage part of the `PqResultHelper` in a pre-cursor to this, but I think the overall structure of this is still reviewable
> feat(c/driver/postgresql): Implement GetObjects for tables

- go/adbc/driver/flightsql/flightsql_adbc.go
GetObjects uses this function, for example to list the tables in a specific schema.
The issue is getObjectsTables does not use the requested schema as a filter when making the API call, and only later the results are filtered on the client side.
This fix prevents the server from having to process a lot of unnecessary data in DBs with many schemas.
> perf(go/adbc/driver/flightsql): filter by schema in getObjectsTables

- .pre-commit-config.yaml
- adbc.h
- c/driver/postgresql/postgresql.cc
- c/driver/sqlite/sqlite.c
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager_test.cc
- go/adbc/adbc.go
- go/adbc/infocode_string.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/snowflake/driver.go
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcDriver.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcInfoCode.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcOptionKey.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcOptions.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatement.java
- java/core/src/main/java/org/apache/arrow/adbc/core/BulkIngestMode.java
> feat(format): introduce ADBC API revision 1.1.0

- adbc.h
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager_test.cc
- Clarify one of the docstrings
- Remove the 'future growth' padding since we have a different compatibility strategy
> feat(format): remove unnecessary padding

- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi.py
`fetchall` currently fails on queries that return no results.
The issue is `_reader.read_next_batch()` returns a batch with no rows which is not expected by the python code.
I've added a condition similar to the one in the [go driver](https://github.com/apache/arrow-adbc/blob/main/go/adbc/sqldriver/driver.go#L590).
> fix(python/adbc_driver_manager): fix fetching queries with empty results

- c/driver/sqlite/sqlite_test.cc
- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation.cc
Needs tests on the C side and perhaps also on the R side. Please advise.
Closes #734.
``` r
flights <- nycflights13::flights
flights$time_hour <- NULL
stmt <- adbc_statement_init(con, adbc.ingest.target_table = "flights")
adbc_statement_bind(stmt, flights)
adbc_statement_execute_query(stmt)
#> [1] 336776
adbc_statement_release(stmt)
stmt <- adbc_statement_init(con)
adbc_statement_set_sql_query(stmt, "SELECT * from flights WHERE month = 3 LIMIT 2")
stream <- nanoarrow::nanoarrow_allocate_array_stream()
adbc_statement_execute_query(stmt, stream)
#> [1] -1
result <- tibble::as_tibble(stream)
adbc_statement_release(stmt)
result
#> # A tibble: 2 × 18
#>    year month …
```
> fix(c/driver/sqlite): Fix parameter binding when inferring types and when retrieving

- .github/workflows/native-unix.yml
- docs/source/conf.py
- docs/source/driver/postgresql.rst
- docs/source/ext/adbc_cookbook.py
- docs/source/python/recipe/driver_manager.rst
- docs/source/python/recipe/driver_manager_duckdb.py
- docs/source/python/recipe/index.rst
- docs/source/python/recipe/postgresql.rst
- docs/source/python/recipe/postgresql_authenticate.py
- docs/source/python/recipe/postgresql_create_append_table.py
- docs/source/python/recipe/postgresql_execute_bind.py
- docs/source/python/recipe/postgresql_get_table_schema.py
- docs/source/python/recipe/postgresql_list_catalogs.py
- docs/source/tests/test_cookbook.py
Adds a custom Sphinx directive that generates further reStructuredText markup from a self-contained source file. Appropriately marked comments in the source file are turned into markup, and code in between is turned into code blocks. This lets us author and test recipes using language-native tooling (unlike what the Apache Arrow Cookbook does) but still embed them in a readable way inside the Sphinx documentation.
> docs: add literate-style code recipes

- java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/PostgreSqlTypeTest.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/StandardJdbcQuirks.java
> fix(java/driver/jdbc): return timestamps as MICROSECOND always

- go/adbc/driver/snowflake/driver.go
- go/adbc/pkg/Makefile
Fixes https://github.com/apache/arrow-adbc/issues/819
Adds build for Windows DLLs
> fix(go/adbc/driver/snowflake): initialize Params, add DLL build

- dev/release/post-08-bump-versions.sh
> chore(dev/release): don't push to main in post-08-bump-versions

- .gitmodules
- dev/release/rat_exclude_files.txt
- submodule was not setup correctly
- pattern matching for csproj and sln files
> fix(csharp): submodule not pulling correctly

- python/adbc_driver_flightsql/adbc_driver_flightsql/__init__.py
Add new cookie middleware option (#825) to python constants. Also see #716.
> feat(python/adbc_driver_flightsql): add cookie middleware option to DatabaseOptions

- .github/CODEOWNERS
Adding a CODEOWNERS file for auto assigning reviewers on PRs. Feel free to update, add, modify names and assignments here.
> ci: Add CODEOWNERS file

- r/adbcdrivermanager/DESCRIPTION
- r/adbcdrivermanager/man/adbcdrivermanager-package.Rd
From the CRAN incoming reviewer:
```
Thanks,
Please add a web reference for the API in the form <https:.....> to the description of the DESCRIPTION file with no space after 'https:' and angle brackets for auto-linking.
Please fix and resubmit.
```
> chore(r/adbcdrivermanager): Add link in DESCRIPTION

- docs/source/driver/flight_sql.rst
- docs/source/driver/postgresql.rst
- docs/source/driver/snowflake.rst
- docs/source/driver/sqlite.rst
- r/adbcdrivermanager/README.Rmd
- r/adbcdrivermanager/README.md
- r/adbcflightsql/DESCRIPTION
- r/adbcflightsql/R/adbcflightsql-package.R
- r/adbcflightsql/README.Rmd
- r/adbcflightsql/README.md
- r/adbcflightsql/man/adbcflightsql-package.Rd
- r/adbcpostgresql/DESCRIPTION
- r/adbcpostgresql/R/adbcpostgresql-package.R
- r/adbcpostgresql/README.Rmd
- r/adbcpostgresql/README.md
- r/adbcpostgresql/man/adbcpostgresql-package.Rd
- r/adbcsnowflake/DESCRIPTION
- r/adbcsnowflake/R/adbcsnowflake-package.R
- r/adbcsnowflake/README.Rmd
- r/adbcsnowflake/README.md
- r/adbcsnowflake/man/adbcsnowflake-package.Rd
- r/adbcsqlite/DESCRIPTION
- r/adbcsqlite/R/adbcsqlite-package.R
- r/adbcsqlite/README.Rmd
- r/adbcsqlite/README.md
- r/adbcsqlite/man/adbcsqlite-package.Rd
This PR aligns the R driver packages to use functionality available now that adbcdrivermanager and nanoarrow 0.2.0 is on CRAN. This simplifies installing drivers considerably because CRAN dependencies are picked up automatically (no more `Remotes:`!!), so `remotes::install_github(..., build = FALSE)` should work reliably. It also allows using `read_adbc()` which is much nicer for the README examples for each driver.
While I had all the DESCRIPTIONs open, I also unified them so that they have a maximal chance of passing the CRAN incoming human review.
While I had all the packages open I also unified the database/connection/statement implementations since the details had changed since I wrote the first one (I now pass on `...` so that the user can pass on options that have been added since …
> chore: Update + unify R driver packages after adbcdrivermanager CRAN release

- adbc.h
- c/driver_manager/adbc_driver_manager.cc
- go/adbc/adbc.go
- go/adbc/drivermgr/adbc.h
- go/adbc/drivermgr/adbc_driver_manager.cc
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcException.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatement.java
- java/core/src/main/java/org/apache/arrow/adbc/core/StandardStatistics.java
Intends to tackle:
- https://github.com/apache/arrow-adbc/issues/621
- https://github.com/apache/arrow-adbc/issues/685
- https://github.com/apache/arrow-adbc/issues/736
- https://github.com/apache/arrow-adbc/issues/755
> feat(format): add additional features to 1.1.0 spec

- c/driver_manager/adbc_driver_manager.cc
- glib/test/test-connection.rb
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/flightsql/utils.go
- go/adbc/drivermgr/adbc_driver_manager.cc
- python/adbc_driver_flightsql/tests/test_dbapi.py
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- r/adbcdrivermanager/R/error.R
- r/adbcdrivermanager/tests/testthat/_snaps/driver_log.md
- r/adbcdrivermanager/tests/testthat/_snaps/helpers.md
- r/adbcdrivermanager/tests/testthat/test-helpers.R
- r/adbcdrivermanager/tests/testthat/test-radbc.R
- Avoid useless prefixes and redundant information (like ADBC_ prefixes everywhere)
- Trim out some internal bits (like exceptions technically being in _lib)
Fixes #865.
> feat(c/driver_manager,go/adbc,python): trim down error messages

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
Prevents #863 from crashing, but doesn't fix the underlying error.
> fix(go/adbc/driver/snowflake): handle result sets without Arrow data

- .github/workflows/native-unix.yml
- docs/source/driver/flight_sql.rst
- docs/source/driver/installation.rst
- docs/source/driver/postgresql.rst
- docs/source/driver/snowflake.rst
- docs/source/driver/sqlite.rst
- r/adbcdrivermanager/README.Rmd
- r/adbcdrivermanager/README.md
- r/adbcflightsql/README.Rmd
- r/adbcflightsql/README.md
- r/adbcpostgresql/README.Rmd
- r/adbcpostgresql/README.md
- r/adbcsnowflake/README.Rmd
- r/adbcsnowflake/README.md
- r/adbcsqlite/README.Rmd
- r/adbcsqlite/README.md
The latest pkgbuild release fixes a bug in version 1.4.1 that prevented installation from GitHub from working properly. Our driver packages currently can *only* be installed from GitHub and so this was a bit of a problem. Thankfully, this was fixed in 1.4.2 which was just released. This PR updates READMEs and CI with install instructions that actually work 😬 .
You should be able to install any package using (e.g.):
```r
pak::pak("apache/arrow-adbc/r/adbcsqlite")
```
If you didn't *just* install pak, you have update the internal version of pkgbuild and clean its build cache. I think I successfully got this down to two lines:
```r
install.packages("pkgbuild", pak:::private_lib_dir())
pak::cache_clean()
```
> chore(r): Update CI and READMEs for latest pkgbuild release

- docs/source/driver/installation.rst
> docs: Ensure Python and R install instructions list all drivers

- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
I'm not sure if this is exactly required and I'm happy to implement differently. One limitation of the existing driver is that (1) it will error if more than 2GB of total text exists in one column and (2) the array stream's get_next will block until the entire result has been computed. A cool thing you can do in R is do something like `read_adbc() |> arrow::as_record_batch_reader() |> arrow::write_dataset()` for bigger-than-memory queries...this behaviour is basically to support that.
Some open questions:
- Default chunk size? I chose 16 MB...maybe it should be bigger? Smaller? I like MB instead of number-of rows because it doesn't make assumptions about how big or small the rows are. When querying a PostGIS table, for example, polygon features can be several MB each.
- How to configure …
> feat(c/driver/postgresql): Implement streaming/chunked output

- c/driver/postgresql/connection.cc
- c/driver/postgresql/connection.h
- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite_test.cc
- c/driver_manager/adbc_driver_manager_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
closes #867 
The lifecycle of setting the session time zone in this isn't great. I think should be handled during connect somehow? But not sure if postgres even supports that reading things like:
https://stackoverflow.com/a/11779621/621736
I think there is also something awry with the release callback for timezone schemas; needs further investigation
> feat(c/driver/postgresql): TimestampTz write

- .github/workflows/native-unix.yml
- adbc.h
- go/adbc/adbc.go
- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/flightsql/flightsql_statement.go
- go/adbc/driver/flightsql/record_reader.go
- go/adbc/driver/flightsql/utils.go
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/statement.go
- go/adbc/drivermgr/adbc.h
- go/adbc/standard_schemas.go
- go/adbc/validation/validation.go
- ADBC_INFO_DRIVER_ADBC_VERSION
- StatementExecuteSchema (#318)
- ADBC_CONNECTION_OPTION_CURRENT_{CATALOG, DB_SCHEMA} (#319)
- Get/SetOption
- error_details (#755)
- GetStatistics (#685)
- New ingest modes (#541)
> feat(go/adbc): implement ADBC 1.1.0 features

- CPPLINT.cfg
- c/driver/sqlite/CMakeLists.txt
- c/driver/sqlite/sqlite_test.cc
- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation.cc
Currently writes as a string. Here's what it looks like in the db at the end of the temporal test
```bash
sqlite> select * FROM bulk_ingest;
1970-01-01T00:00:00.000000000
1970-01-01T00:00:00.000000042
```
> feat(c/driver/sqlite): Sqlite timestamp write support

- python/adbc_driver_flightsql/README.md
- python/adbc_driver_postgresql/README.md
- python/adbc_driver_snowflake/README.md
- python/adbc_driver_sqlite/README.md
Following current instructions yields
```sh
ERROR: --no-deps is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
> docs(python): Fix README for python drivers

- c/driver/flightsql/dremio_flightsql_test.cc
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/sqlite/sqlite.c
- c/integration/duckdb/duckdb_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
Should maybe use sqlite3's string handling throughout the module; for now just focused on CREATE TABLE
fixes https://github.com/apache/arrow-adbc/issues/905#issuecomment-1636418672
> fix(c/driver/sqlite): fix escaping of sqlite TABLE CREATE columns

- c/driver/snowflake/snowflake_test.cc
- c/validation/adbc_validation.cc
> test(c/driver/snowflake): fix timestamp tests

- ci/conda_env_dev.txt
- dev/release/post-02-binary.sh
> chore(dev/release): use `--verify-tag` to guard against mistakes

- .github/workflows/native-unix.yml
- ci/conda_env_cpp.txt
- ci/conda_env_cpp_lint.txt
- ci/scripts/cpp_clang_tidy.sh
> chore(ci): run clang-tidy in parallel

- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/panicdummy/driver.go
- go/adbc/pkg/snowflake/driver.go
- python/adbc_driver_flightsql/tests/test_lowlevel.py
- python/adbc_driver_snowflake/tests/test_lowlevel.py
> fix(go/adbc/pkg): export Adbc* symbols on Windows

- c/cmake_modules/AdbcDefines.cmake
- c/driver/postgresql/connection.cc
- c/driver/sqlite/statement_reader.c
According to [this StackOverflow answer](https://stackoverflow.com/questions/61240589/how-to-initialize-a-struct-to-0-in-c), `struct Foo foo = {0}` isn't reliable for zero-initializing a struct. We don't define any default initializers because these are C structs, but regardless, GCC isn't happy, so let's be fully explicit.
Fixes #845.
> chore(c): satisfy -Wextra -Wpedantic

- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcDriver.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcException.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcOptions.java
- java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatement.java
- java/core/src/main/java/org/apache/arrow/adbc/core/ErrorDetail.java
- java/core/src/main/java/org/apache/arrow/adbc/core/StandardSchemas.java
- java/core/src/main/java/org/apache/arrow/adbc/core/StandardStatistics.java
- java/core/src/main/java/org/apache/arrow/adbc/core/TypedKey.java
- java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlQuirks.java
- java/driver/flight-sql/pom.xml
- java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlDriver.java
- java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlDriverUtil.java
- java/driver/flight-sql/src/test/java/org/apache/arrow/adbc/driver/flightsql/DetailsTest.java
- java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/PostgresqlQuirks.java
- java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/StatisticsTest.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/InfoMetadataBuilder.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcArrowReader.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnection.java
- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcStatement.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractStatementTest.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/SqlValidationQuirks.java
- ADBC_INFO_DRIVER_ADBC_VERSION
- StatementExecuteSchema (#318)
- ADBC_CONNECTION_OPTION_CURRENT_{CATALOG, DB_SCHEMA} (#319)
- error_details (#755)
- GetStatistics (#685)
> feat(java): implement 1.1.0 features

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_statement.go
- go/adbc/driver/flightsql/record_reader.go
- go/adbc/driver/flightsql/utils.go
See #862.
Example:
```
Internal: SqlState: , msg: [FlightSQL] Ballista Error: General("scheduler::from_proto(Action) invalid or missing action") (Internal; DoGet: endpoint 0: [uri:"grpc+tcp://172.24.0.5:50051"])
```
Now we can see that the error comes from issuing a DoGet against a particular location.
> feat(go/adbc/driver/flightsql): add context to gRPC errors

- adbc.h
- docs/source/format/specification.rst
- docs/source/format/versioning.rst
- go/adbc/drivermgr/adbc.h
> docs: update prose for 1.1.0 and clarify cancellation

- adbc.h
- c/driver/common/utils.c
- c/driver/common/utils.h
- c/driver/flightsql/dremio_flightsql_test.cc
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/postgresql/connection.cc
- c/driver/postgresql/connection.h
- c/driver/postgresql/database.cc
- c/driver/postgresql/database.h
- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/postgresql.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/driver/snowflake/snowflake_test.cc
- c/driver/sqlite/sqlite.c
- c/driver/sqlite/sqlite_test.cc
- c/driver_manager/CMakeLists.txt
- c/driver_manager/adbc_driver_manager.cc
- c/driver_manager/adbc_driver_manager_test.cc
- c/integration/duckdb/duckdb_test.cc
- c/validation/CMakeLists.txt
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
- go/adbc/drivermgr/adbc.h
- go/adbc/drivermgr/adbc_driver_manager.cc
- ADBC_INFO_DRIVER_ADBC_VERSION
- StatementExecuteSchema (#318)
- ADBC_CONNECTION_OPTION_CURRENT_{CATALOG, DB_SCHEMA} (#319)
- Cancellation
- Get/SetOption
- New ingest modes
> feat(c/driver/postgresql): implement ADBC 1.1.0 features

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/StandardSchemas.cs
Continuation of https://github.com/apache/arrow-adbc/issues/930
> fix(csharp): include GetInfo and GetObjects call for .NET 4.7.2

- csharp/src/Apache.Arrow.Adbc/AdbcException.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/StandardSchemas.cs
Continuation of https://github.com/apache/arrow-adbc/issues/930
Resolve https://github.com/apache/arrow-adbc/issues/947
> fix(csharp): include GetTableTypes and GetTableSchema call for .NET 4.7.2 

- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- python/adbc_driver_postgresql/tests/test_dbapi.py
> fix(c/driver/postgresql): Fix segfault associated with uninitialized copy_reader_

- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
Add example usage for how to set options from the Python bindings.
> docs(python/adbc_driver_manager): improve docstrings for set_options

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
> fix(go/adbc/sqldriver): fix handling of decimal types

- r/adbcdrivermanager/R/adbc.R
Closes #919.
Ideally we should also expose symbolic versions of the info codes so that nobody has to look in adbc.h to figure out that 0L is the code for vendor 😬 .
...also, nanoarrow chokes on converting the map<int, int> member of the union array 😬 😬 . I thought I'd handled unions and maps but perhaps the nesting is causing a problem or perhaps I forgot to implement maps.
``` r
adbc_connection_get_info(con, 0)
#> <nanoarrow_array_stream struct<info_name: uint32, info_value: dense_union([0,1,2,3,4,5])<string_value: string, bool_value: bool, int64_value: int64, int32_bitmask: int32, string_list: list<item: string>, int32_to_int32_list_map: map<entries: …
```
> fix(r): Ensure that info_codes are coerced to integer

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
> fix(go/adbc/driver/flightsql): Have GetTableSchema check for table name match instead of the first schema it receives

- r/adbcflightsql/src/Makevars.in
- r/adbcsnowflake/configure
- r/adbcsnowflake/src/Makevars.in
Required on Go 1.20+ since it no longer links this by default.
Fixes #995.
> build(r/adbcsnowflake): add -lresolv

- r/adbcflightsql/R/adbcflightsql-package.R
- r/adbcflightsql/man/adbcflightsql-package.Rd
- r/adbcpostgresql/R/adbcpostgresql-package.R
- r/adbcpostgresql/man/adbcpostgresql-package.Rd
- r/adbcsnowflake/R/adbcsnowflake-package.R
- r/adbcsnowflake/man/adbcsnowflake-package.Rd
- r/adbcsqlite/R/adbcsqlite-package.R
- r/adbcsqlite/man/adbcsqlite-package.Rd
Remotes a CMD check NOTE on R-devel:
```
* checking Rd metadata ... NOTE
Rd files without \alias:
'adbcsqlite-package.Rd'
```
I had used `@aliases NULL` because each driver package has an identically named function and using `@aliases NULL` ensured that there were no duplicate aliases. Recent r-devel added a check for .Rd files with no alias, hence the need for an update.
For #1010, #1011, and #1012.
> chore(r): Ensure package documentation has `\alias`

- r/adbcdrivermanager/src/radbc.cc
- r/adbcdrivermanager/src/radbc.h
- r/adbcdrivermanager/tests/testthat/test-utils.R
Closes #1001.
In theory one could differentiate the NULL from the "non-null but invalid" case, but I think returning FALSE is the least confusing thing to do.
> fix(r/adbcdrivermanager): Make `adbc_xptr_is_valid()` return `FALSE` for external pointer to NULL

- c/driver/postgresql/connection.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/sqlite/sqlite.c
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
> fix(c/driver/sqlite): Escape tablename in sqlite GetTableSchema

- r/adbcdrivermanager/R/adbc.R
- r/adbcdrivermanager/man/adbc_connection_get_info.Rd
- r/adbcdrivermanager/src/radbc.cc
- r/adbcdrivermanager/src/radbc.h
Thanks to @nbenn for the reprex!
``` r
flights <- nycflights13::flights
flights$time_hour <- NULL
write_adbc(flights, con, "flights")
stream <- adbc_connection_get_objects(con)
df <- as.data.frame(stream)
df$catalog_db_schemas[[1]]$db_schema_tables[[1]]$table_name
#> [1] "flights"
df$catalog_db_schemas[[1]]$db_schema_tables[[1]]$table_columns[[1]]$column_name
#>  [1] "year"           "month"          "day"            "dep_time"      
#>  [5] "sched_dep_time" "dep_delay"      "arr_time"       "sched_arr_time"
#>  [9] "arr_delay"      "carrier"        "flight"         "tailnum"       
#> [13] "origin"         "dest"           "air_time"       "distance"      
#> …
```
> fix(r/adbcdrivermanager): Ensure nullable arguments `adbc_connection_get_objects()` can be specified

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/logging.go
- go/adbc/ext.go
- go/adbc/go.mod
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/gen/main.go
- go/adbc/pkg/panicdummy/driver.go
- go/adbc/pkg/snowflake/driver.go
> feat(go): add basic driver logging

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- Add a bit more information to the error message in case there are future issues.
- Add a regression test to ensure this use case continues to work.
Fixes #1045.
> test(c/driver/postgresql): ensure ingestion works with temp table

- c/driver/common/options.h
- c/driver/flightsql/dremio_flightsql_test.cc
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/driver/sqlite/sqlite.c
- c/driver/sqlite/sqlite_test.cc
- c/integration/duckdb/duckdb_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
- python/adbc_driver_manager/adbc_driver_manager/__init__.py
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_postgresql/tests/test_dbapi.py
- python/adbc_driver_sqlite/tests/test_dbapi.py
- r/adbcpostgresql/bootstrap.R
- r/adbcsqlite/bootstrap.R
- Support target catalog/schema options for ingestion
- Fix escaping in SQLite, PostgreSQL
Fixes #1000.
> feat(c/driver): support target catalog/schema for ingestion

- go/adbc/driver/flightsql/flightsql_adbc.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
Fixes https://github.com/apache/arrow-adbc/issues/1059
> feat(go/adbc/driver/flightsql): add adbc.flight.sql.client_option.authority 

- java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlConnection.java
If an exception was thrown in InfoMetadataBuilder, the inner VectorSchemaRoot would leak.
> fix(java/driver/flight-sql): fix leak in InfoMetadataBuilder

- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi.py
fixes https://github.com/apache/arrow-adbc/issues/1076
> fix(python/adbc_driver_manager): Allow non-indexable sequences in executemany

- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/validation/validation.go
> fix(go/adbc/driver/snowflake): Prevent database options from getting overwritten

- go/adbc/driver/snowflake/statement.go
See https://github.com/apache/arrow-adbc/pull/1118#discussion_r1339095054
> fix(go/adbc/driver/snowflake): default SetOption to StatusNotImplemented

- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/postgres_copy_reader_test.cc
This is a pre-cursor to #1093 ; figured it would be easier to work piece-wise rather than all at once.
This does not try to actually connect the statement.cc code to use this, but just gets the test case / general structure set up
> feat(c/driver/postgresql): Inital COPY Writer design

- r/adbcdrivermanager/src/radbc.cc
There were two problems:
- I forgot that `allocate_xptr<>()` didn't register a finalizer!
- Apparently `ArrowError`s have to be zero-initialized before getting passed to the driver manager to avoid errors.
Closes #1124.
> fix(r/adbcdrivermanager): Fix valgrind errors identified by CRAN 0.7.0 submission

- c/driver_manager/adbc_driver_manager.cc
- go/adbc/drivermgr/adbc_driver_manager.cc
From CRAN on x86_64-apple-darwin17.0 (64-bit)
```
* installing *source* package ‘adbcdrivermanager’ ...
** package ‘adbcdrivermanager’ successfully unpacked and MD5 sums checked
** using staged installation
Found vendored ADBC
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../src -DADBC_EXPORT=""  -I/usr/local/include   -fPIC  -Wall -g -O2  -c adbc_driver_manager.cc -o adbc_driver_manager.o
adbc_driver_manager.cc:271:83: error: use of undeclared identifier 'EINVAL'
if (stream->release != ErrorArrayStreamRelease || !stream->private_data) return EINVAL;
^
adbc_driver_manager.cc:278:83: error: use of undeclared identifier 'EINVAL'
if (stream->release != ErrorArrayStreamRelease || !stream->private_data) return EINVAL;
^ …
```
> fix(c/driver_manager): Include cerrno in driver manager

- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
Needed to avoid linker issues with cgo
> chore(ci): bump Go for Windows to 1.20.8

- c/driver/postgresql/connection.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
- docs/source/python/recipe/postgresql_create_append_table.py
- python/adbc_driver_postgresql/tests/test_dbapi.py
> fix(c/driver/postgresql): reset transaction after rollback

- c/driver/postgresql/postgresql_test.cc
- c/driver/sqlite/sqlite.c
- c/driver/sqlite/sqlite_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
This feature relies on Composite Primary Keys, which are implemented, but had no tests. The missing tests are included in this PR as a separate commit. The pull request closes #936 .
- SQLite constraints are currently nameless, whereas the PostgreSQL constraints have generated names. Should it stay that way?
- SQLite and PostgreSQL return their constraints in different orders. Is that by design?
- Since the order of constraints can vary between DBs, the Foreign Key tests currently identify constraint columns by their number of column usages. Maybe there's a better solution to it?
- `c/validation/adbc_validation.cc` lines [1252-1255] assume a certain order of the constraint column usages. Should we find an order-agnostic solution instead? It might be more verbose. It's currently:
``` …
```
> feat(c/driver/postgresql,c/driver/sqlite): Implement FOREIGN KEY constraints

- r/adbcdrivermanager/src/driver_log.c
- r/adbcdrivermanager/src/driver_monkey.c
- r/adbcdrivermanager/src/driver_void.c
- r/adbcdrivermanager/src/radbc.cc
The existing code should have worked (and probably still did), but I'd like to eliminate any complexity arising from managing multiple driver versions for the purposes of eliminating potential causes of #1161.
> fix(r/adbcdrivermanager): Use ADBC_VERSION_1_1_0 to initialize drivers internally

- r/adbcdrivermanager/tests/testthat/test-utils.R
Closes #1161.
When we implement dependent reverse-reference counting (#1128), we can avoid a user accidentally ending up in this situation by prohibiting `adbc_xptr_move()` when the number of dependents is greater than 0.
> fix(r/adbcdrivermanager): Fix tests to avoid moving an external pointer with dependents

- c/driver/common/utils.c
- c/driver/common/utils_test.cc
Fixes #1100 
Test before fix:
```
Expected equality of these values:
AdbcGetObjectsDataGetTableByName(&mock_data, "mock_catalog", "mock_schema", "table_suffix")
Which is: 0x16d014ee8
&mock_table_suffix
Which is: 0x16d014ea8
arrow-adbc/c/driver/common/utils_test.cc:220: Failure
Expected equality of these values:
AdbcGetObjectsDataGetColumnByName(&mock_data, "mock_catalog", "mock_schema", "table", "column_suffix")
Which is: 0x16d014df8
&mock_column_suffix
Which is: 0x16d014d48
arrow-adbc/c/driver/common/utils_test.cc:224: Failure
Expected equality of these values:
AdbcGetObjectsDataGetConstraintByName(&mock_data, "mock_catalog", "mock_schema", "table", "constraint_suffix")
Which is: 0x16d014d08
&mock_constraint_suffix
Which is: 0x16d014cc8
[  FAILED  ] AdbcGetObjectsData.GetObjectsByName (0 …
```
> fix(c/driver/common): Object name matching handles shared prefix case correctly

- c/driver/postgresql/statement.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
> fix(c/driver/postgresql): Support trailing semicolon(s) for queries inside COPY statements

- .github/workflows/integration.yml
> ci: use pytest-error-for-skips for integration tests

- c/driver/common/utils.h
- r/adbcpostgresql/src/Makevars.win
- r/adbcsqlite/configure
- r/adbcsqlite/configure.win
- r/adbcsqlite/src/Makevars.in
Closes #1113.
The mingw headers appear to be a little inconsistent with respect to the definitions of `PRId64` and the format check attribute. I think this fix it the least intrusive way to deal with that but I'm open to thoughts!
> fix(r): Build with __USE_MINGW_ANSI_STDIO to enable use of lld in format strings

- c/driver/snowflake/snowflake_test.cc
We use quotes around the table name in the `DropTable` method but we don't use it in `CreateSampleTable`. Without the quotes, the table is created as upper case, but we attempt to drop the table with a forced lower case name. As a result the table doesn't get dropped and we fail on the table creation because the table already exists.
So if we properly put quotes around the table creation, this should fix the snowflake CI integration tests.
> ci: fix snowflake integration tests

- r/adbcdrivermanager/R/adbc.R
- r/adbcdrivermanager/man/adbc_connection_get_info.Rd
- r/adbcdrivermanager/src/radbc.cc
- r/adbcdrivermanager/src/radbc.h
- r/adbcdrivermanager/tests/testthat/test-radbc.R
Closes #1127. This also introduces better error messages and fixes some inputs that might have segfaulted (`NA_character_` input as a table type):
``` r
con <- adbc_driver_void() |> 
adbc_database_init() |> 
adbc_connection_init()
adbc_connection_get_objects(con, table_name = 5L)
#> Error in adbc_connection_get_objects(con, table_name = 5L): Expected character(1) for conversion to const char*
adbc_connection_get_objects(con, table_name = NA_character_)
#> Error in adbc_connection_get_objects(con, table_name = NA_character_): Can't convert NA_character_ to const char*
adbc_connection_get_objects(con, NA_integer_)
#> Error in adbc_connection_get_objects(con, NA_integer_): Can't convert NA_integer_ to int
adbc_connection_get_objects(con, NA_real_)
#> Error in …
```
> fix(r/adbcdrivermanager): Improve handling of integer and character list inputs

- r/adbcsnowflake/DESCRIPTION
The CI for adbcsnowflake is failing because apparently REGIONKEY gets returned as a decimal, which needs the arrow R package to inspect. The previous attempt at fixing this assumed that it was another column causing the problem.
> fix(r/adbcsnowflake): Add arrow as check dependency for adbcsnowflake

- c/cmake_modules/BuildUtils.cmake
Previously the add_benchmark CMake function would create the benchmark which could be invoked directly without issue. However, the `ctest` invocation would not yield results
> fix(c/driver/postgresql): Allow ctest to run benchmark

- r/adbcsqlite/tests/testthat/test-adbcsqlite-package.R
Closes #1211.
It wasn't an external pointer issue, it was just not cleaning up properly in some tests. These tests were written before `with_adbc()` and `local_adbc()`...the tests for all the drivers could be refactored to use them (but perhaps not today).
> fix(r/adbcsqlite): Fix incomplete cleanup in adbcsqlite tests

- r/adbcpostgresql/src/Makevars.ucrt
This PR updates adbcpostgresql to use the version of libpq distributed with RTools (i.e., the Windows build system for R). Tomas Kalibera kindly checked to make sure this change worked, and indicated that falling back to downloading static libraries on older versions of R would be tolerated by CRAN:
> since you have Makevars.ucrt for R >= 4.2 (and hence Rtools >= 42), it is ok to use Makevars.win as a fallback for older versions. CRAN tolerates downloading with Rtools40 (when many libraries were not part of the default installation) and older and CRAN doesn't really care about versions older than "oldrelease" anyway.
Tomas provided a patch if we want to use pkg-config; however, noted that the version here would work on both RTools42 and RTools43, and using pkg-config could be revisited if …
> fix(r/adbcpostgresql): Use libpq provided by Rtools for R 4.2 and R 4.3

- c/driver/sqlite/sqlite_test.cc
- c/driver/sqlite/statement_reader.c
It looks like the binding + ingest was supported already, it was just the result sets that were not supported.
From the R bindings:
``` r
read_adbc(con, "SELECT X'00' as a") |> 
as.data.frame()
#>           a
#> 1 blob[1 B]
```
<sup>Created on 2023-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> feat(c/driver/sqlite): Support BLOB in result sets for SQLite

- c/driver/flightsql/dremio_flightsql_test.cc
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/sqlite/sqlite.c
- c/integration/duckdb/duckdb_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
Fixes #1145 
If we prefer consistency with the stream case for # of rows affected instead of the actual # of rows affected, we can change this line:
```
*rows_affected = sqlite3_changes(stmt->conn);
```
to be:
```
*rows_affected = -1;
```
> fix(c/driver/sqlite): Provide # of rows affected for non-SELECT statements instead of 0

- go/adbc/driver/flightsql/flightsql_database.go
> fix(go/adbc/driver/flightsql): take metadata lock for safety

- c/driver/postgresql/postgresql_test.cc
- c/driver/sqlite/sqlite_test.cc
- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
This PR adds the ability to ingest dictionary-encoded string and binary columns.
Part of addressing #1008.
From the R bindings:
``` r
df <- data.frame(x = factor(letters[1:10]))
write_adbc(df, con, "tbl")
read_adbc(con, "SELECT * from tbl") |> 
as.data.frame()  
#>    x
#> 1  a
#> 2  b
#> 3  c
#> 4  d
#> 5  e
#> 6  f
#> 7  g
#> 8  h
#> 9  i
#> 10 j
```
<sup>Created on 2023-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> feat(c/driver/sqlite): Support binding dictionary-encoded string and binary types

- csharp/.gitignore
Can't build the C# project checking out from main directly at the moment.
README mentioned the submodule for Arrow and it's included in .gitmodules, but none of it works unless the csharp's .gitignore has src/arrow removed so that it isn't ignored, and the repo can actually pull the submodule into the expected directory path.
> build(csharp): add Arrow as submodule proper for CSharp project

- .github/workflows/java.yml
- java/driver/flight-sql/pom.xml
- java/pom.xml
> ci: add Java 21 run, drop Java 20

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/driver/sqlite/sqlite.c
- c/driver/sqlite/sqlite_test.cc
- c/validation/adbc_validation.cc
- c/validation/adbc_validation.h
> fix(c/driver): be explicit about columns in ingestion

- dev/release/verify-release-candidate.sh
> chore(dev/release): default to python 3.11 for now

- c/driver/sqlite/sqlite.c
- r/adbcsqlite/configure
- r/adbcsqlite/tools/test_extension.c
> fix(r/adbcsqlite): Allow sqlite driver to link against sqlite3 that does not contain sqlite3_load_extension()

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/statement.go
- go/adbc/go.mod
- go/adbc/go.sum
> feat(go/adbc/driver/snowflake): add support for ExecuteSchema

- r/adbcdrivermanager/R/options.R
- r/adbcdrivermanager/tests/testthat/test-options.R
This enables code like `adbc_connection_set_options(con, adbc.connection.autocommit = TRUE)`, which previously failed.
> feat(r/adbcdrivermanager): Add support for setting option as logical

- r/adbcpostgresql/configure
Closes #1268.
The configure script now falls back on `pg_config`. Barring an intervention like setting the PKG_CONFIG_PATH in advance, this method gets used on MacOS M1 (libpq installed via homebrew) and archlinux. I also checked recent ubuntu, fedora, and alpine, all of which appear to use pkg-config to pick up the include/libs location.
> chore(r/adbcpostgresql): Improve configure script using pg_config

- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/postgres_type_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
This PR adds the ability for the Postgres driver to ingest dictionary-encoded arrays. This shows up in R because factors are relatively common and encode by default in Arrow to dictionary-encoded string for performance reasons.
Reprex in R:
``` r
con <- adbcpostgresql::adbcpostgresql() |> 
adbc_database_init(uri = Sys.getenv("ADBC_POSTGRESQL_TEST_URI")) |> 
adbc_connection_init()
df <- data.frame(x = letters, y = factor(letters))
write_adbc(df, con, "some_table")
#> Error in adbc_statement_execute_query(stmt): [libpq] Failed to create table: ERROR:  relation "some_table" already exists
#> 
#> Query was: CREATE TABLE "public" . "some_table" ("x" TEXT, "y" TEXT)
read_adbc(con, "SELECT * from some_table") |> 
as.data.frame() |> 
str()
#> 'data.frame':    26 obs. of …
```
> feat(c/driver/postgresql): Accept bulk ingest of dictionary-encoded strings/binary

- csharp/src/Apache.Arrow.Adbc/AdbcStatement.cs
> fix(csharp): fix timestamp case in AdbcStatement.GetValue

- .pre-commit-config.yaml
- ci/linux-packages/debian/control
- ci/linux-packages/debian/libadbc-glib-dev.install
- ci/linux-packages/debian/rules
- ci/linux-packages/yum/almalinux-8/Dockerfile
- ci/linux-packages/yum/almalinux-9/Dockerfile
- ci/linux-packages/yum/apache-arrow-adbc.spec.in
- ci/scripts/glib_build.sh
- dev/release/verify-apt.sh
- glib/adbc-glib/error.h
- glib/adbc-glib/meson.build
- glib/example/README.md
- glib/example/meson.build
- glib/example/sqlite.c
- glib/example/vala/README.md
- glib/example/vala/meson.build
- glib/example/vala/sqlite.vala
- glib/meson.build
- glib/meson_options.txt
Vala VAPI file is generated for current GADBC 1.0 API version.
It is disable by default, but recommended to be enable when a development package is distributed.
This commit force a 1.0 API versioning, replacing the old one where 0 were used for GIR API version (gir_version), so now shows '1.0' instead of '0.0'.
> feat(glib): add Vala VAPI for GADBC

- csharp/src/Apache.Arrow.Adbc/Apache.Arrow.Adbc.csproj
Test dependency is not required for product code.
> fix(csharp/adbc): Remove xunit as a dependency from Apache.Arrow.Adbc.dll

- go/adbc/drivermgr/wrapper.go
- go/adbc/drivermgr/wrapper_sqlite_test.go
Add implementation for `GetObjects` in CGO wrapper for `adbc_driver_manager`
Functionality exists in C++ driver manager but not yet accessible via Go driver interface.
I haven't worked with CGO before so I wanted to limit the scope of this PR to just one of the unimplemented methods in the wrapper. I would like to continue implementing the other methods once I know I'm going about this correctly.
Closes part of #1291
> feat(go/adbc/drivermgr): Implement GetObjects for CGO Wrapper

- glib/adbc-glib/meson.build
In sync with arrow-glib, GADBC should name its Vala's VAPI file's name to adbc-glib and is the same as the pkg-config adbc-glib.pc file's name
> fix(glib): Vala's vapi's name should be same as pkg-config package

- csharp/test/Drivers/Snowflake/ValueTests.cs
Adding tests which do a simple insert, select and delete for the numeric data types in Snowflake, to validate that they can be added and read correctly through ADBC. The target values are usually problematic for reading and writing, such as infinity, min and max values and NaN, but some more standard values are included for sanity.
Tests structure:
1. Create a temporary table with a single column of the chosen numeric data type. Snowflake has effectively two: NUMBER and FLOAT, with NUMBER having variations depending on the precision and scale. The table will use the config specified catalog and schema, but the table itself will be a generated name to avoid collisions or overwriting other data.
2. A single value of the correct type is inserted into the table.
3. The value is queried from …
> test(csharp/test/Drivers/Snowflake): Adding numeric value tests

- .github/workflows/dev_pr.yml
- .github/workflows/dev_pr/milestone.sh
> ci: auto-assign milestones to pull requests

- csharp/test/Apache.Arrow.Adbc.Tests/Metadata/GetObjectsParser.cs
- csharp/test/Drivers/Snowflake/DriverTests.cs
Added tests to verify GetObjects for different depths like: Catalogs
DbSchemas
Tables
All
Also added tests to verify GetObjects with catalog, schema, and table names passed as patterns
> test(csharp): add more tests for verifying GetObjects (Depths and Patterns)

- csharp/test/Drivers/Snowflake/ValueTests.cs
.NET 4.7.2 will round up Double.MaxValue / round down Double.MinValue when using Double.ToString(), resulting in infinity / -infinity stored in Snowflake when passed into the INSERT query statement. This rounding does not occur in .NET 6.0.
This PR corrects that behavior and sends a properly accepted MaxValue/MinValue string when using .NET 4.7.2.
Notable that when the tests can use prepared statements, issues like this should cease to happen.
> test(csharp/test/Drivers/Snowflake): Correct FLOAT min/max tests in .NET 4.7.2

- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/test/Drivers/Snowflake/DriverTests.cs
- csharp/test/Drivers/Snowflake/ValueTests.cs
- go/adbc/driver/snowflake/connection.go
- Fixes https://github.com/apache/arrow-adbc/issues/1309
- Fixes a namespace  
- Adds a test for Xdbc in the C# code
- hanging merge fix from rebase
> fix(go/adbc/driver/snowflake): fix XDBC support when using high precision

- go/adbc/drivermgr/wrapper.go
- go/adbc/drivermgr/wrapper_sqlite_test.go
Implementations for the following methods in the CGO wrapper for `adbc_driver_manager`:
- `GetTableSchema`
- `GetTableTypes`
- `Commit`
- `Rollback`
- `GetParameterSchema`
- `BindStream`
Functionality exists in C++ driver manager but not yet accessible via Go driver interface.
Three methods in the wrapper remain unimplemented: `ExecutePartitions`, `ReadPartition`,  and `SetSubstraitPlan`. These methods are not currently supported by the SQLite driver, which is the primary test target for these changes. It is still possible to implement them in the drivermgr wrapper without support in specific drivers, but it does make it more difficult to verify correct behavior. The effort to add those methods will likely involve some additional work to ensure we are able to test their behaviors, so they …
> feat(go/adbc/drivermgr): Implement Remaining CGO Wrapper Methods that are Supported by SQLite Driver

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
> fix(csharp/src/Drivers/BigQuery): Fix failure when returning multiple table schemas from BigQuery

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
- go/adbc/sqldriver/driver_test.go
Thought I would contribute some fixes I've been using locally for the issues described in #1341
I have no previous experience with this repository or with the Arrow memory model so I would say it's likely I've gotten something wrong. Feel free to ask me to improve on my contributions or merely take them as inspiration for some other fix.
Resolves #1341
> fix(go/adbc/sqldriver): Fix nil pointer panics for query parameters

- .github/workflows/integration.yml
I don't think this is the better long term option of what is described in https://github.com/apache/arrow-adbc/issues/1333#issuecomment-1836083476 but should get CI green for now
> ci: Temporary fix for Python version

- python/adbc_driver_manager/adbc_driver_manager/_lib.pxd
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_manager/tests/test_dbapi.py
- python/adbc_driver_manager/tests/test_lowlevel.py
Addresses https://github.com/apache/arrow-adbc/issues/70
This PR adds the dunder methods to the Handle classes of the low-level interface (which already enables using the low-level interface without pyarrow and with the capsule protocol). 
And secondly, in the places that accept data (eg ingest/bind), it now also accepts objects that implement the dunders in addition to hardcoded support for pyarrow.
> feat(python/adbc_driver_manager): export handles through python Arrow Capsule interface

- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/statement.cc
> fix(c/driver/postgresql): check for underflow

- c/driver/postgresql/postgres_copy_reader.h
- c/driver/postgresql/postgres_copy_reader_test.cc
- c/driver/postgresql/postgres_util.h
- c/driver/postgresql/statement.cc
- docs/source/python/recipe/postgresql.rst
- docs/source/python/recipe/postgresql_create_dataset_table.py
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_postgresql/tests/test_dbapi.py
The COPY writer was ending the COPY command after each batch, so any dataset with more than one batch would fail. Instead, write the header once and don't end the command until we've written all batches.
Fixes #1310.
> fix(c/driver/postgresql): fix ingest with multiple batches

- docs/source/driver/duckdb.rst
- docs/source/driver/flight_sql.rst
- docs/source/driver/installation.rst
- docs/source/driver/postgresql.rst
- docs/source/driver/sqlite.rst
- r/adbcdrivermanager/NEWS.md
- r/adbcflightsql/DESCRIPTION
- r/adbcflightsql/cleanup
- r/adbcflightsql/configure
- r/adbcflightsql/src/.gitignore
- r/adbcflightsql/src/Makevars.in
- r/adbcpostgresql/NEWS.md
- r/adbcpostgresql/cran-comments.md
- r/adbcsnowflake/DESCRIPTION
- r/adbcsnowflake/cleanup
- r/adbcsnowflake/configure
- r/adbcsnowflake/src/.gitignore
- r/adbcsnowflake/src/Makevars.in
- r/adbcsnowflake/tools/.gitignore
- r/adbcsnowflake/tools/create-go-vendor-archive.R
- r/adbcsnowflake/tools/download-go-vendor-archive.R
- r/adbcsnowflake/tools/verify-go-vendor-archive.R
- r/adbcsqlite/NEWS.md
- r/adbcsqlite/cran-comments.md
A few housekeeping updates:
- Updated documentation to reflect implementation/installation status in the documentation
- Updated NEWS entries up to the current version number
- Upstreamed updates requested by CRAN regarding the Snowflake driver (syncing most with the flightsql driver as well). Some of this could be factored out into a common 'how to link a go library from R' package, but it's probably too early for that since there isn't quite consensus on what is actually going to be required yet.
> chore(r): Housekeeping for R packages

- csharp/test/Apache.Arrow.Adbc.Tests/Apache.Arrow.Adbc.Tests.csproj
- csharp/test/Drivers/BigQuery/Apache.Arrow.Adbc.Tests.Drivers.BigQuery.csproj
- csharp/test/Drivers/FlightSql/Apache.Arrow.Adbc.Tests.Drivers.FlightSql.csproj
- csharp/test/Drivers/Interop/Snowflake/Apache.Arrow.Adbc.Tests.Drivers.Interop.Snowflake.csproj
(The dependabot upgrade isn't working probably because the source has a mix of versions.)
> chore(csharp): bump Microsoft.NET.Test.Sdk from 17.6.0 to 17.8.0 in /csharp

- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDataSourceDatabase.java
I think there is a connection leak in the constructor for `JdbcDataSourceDatabase` where we're obtaining a connection in the constructor but we're obtaining another one in the `connect` method using the appropriate username/password. We can remove this and fix the bug as described in #1415.
Fixes #1415.
> fix(java/driver/jdbc): fix connection leak in `JdbcDataSourceDatabase` constructor 

- dev/release/verify-release-candidate.sh
Appears to be required transitively by Snowflake.
Fixes #1425.
> fix(dev/release): install openssl explicitly for R CMD check

- r/adbcdrivermanager/_pkgdown.yml
- r/adbcflightsql/_pkgdown.yml
- r/adbcpostgresql/_pkgdown.yml
- r/adbcsnowflake/_pkgdown.yml
- r/adbcsqlite/_pkgdown.yml
Same as apache/arrow-nanoarrow#315
Since the R package is in a subdirectory, I believe this setting is necessary to ensure that the links to the source files are generated correctly.
> docs(r): fix source links from pkgdown site

- r/adbcflightsql/.Rbuildignore
- r/adbcsnowflake/.Rbuildignore
- r/adbcsqlite/configure
> chore(r): Ensure that Go caches nor binary objects created during test compile end up in R source tarballs

- r/adbcdrivermanager/src/driver_base.h
Because it makes more sense, but also with clang18, CRAN reports a warning:
```
In file included from driver_test.cc:24:
In file included from ./driver_base.h:19:
In file included from /usr/local/clang-trunk/bin/../include/c++/v1/memory:939:
In file included from /usr/local/clang-trunk/bin/../include/c++/v1/__memory/shared_ptr.h:21:
In file included from /usr/local/clang-trunk/bin/../include/c++/v1/__fwd/ostream.h:13:
/usr/local/clang-trunk/bin/../include/c++/v1/__fwd/string.h:45:41: warning: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 19, so please migrate off of it. [-Wdeprecated-declarations]
45 | template <class _CharT, class …
```
> fix(r/adbcdrivermanager): Use std::vector<uint8_t> instead of std::basic_string<uint8_t>

- java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriverUtil.java
- java/driver/jdbc/src/test/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriverUtilTest.java
Improve error messages for JdbcDataSource connection failures.
- Identify JDBC-specific errors and only use the [JDBC] prefix for these.
- Unwrap unknown exceptions that hold known exceptions.
Fixes #1465.
> fix(java/driver/jdbc): improve error messages thrown from JdbcDataSource connect failures

- docs/source/driver/duckdb.rst
- docs/source/driver/flight_sql.rst
- docs/source/driver/postgresql.rst
- docs/source/driver/snowflake.rst
- docs/source/driver/sqlite.rst
- go/adbc/adbc.go
- go/adbc/driver/driverbase/database.go
- go/adbc/driver/driverbase/driver.go
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/flightsql/flightsql_database.go
- go/adbc/driver/flightsql/flightsql_driver.go
- go/adbc/driver/panicdummy/panicdummy_adbc.go
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/snowflake_database.go
- go/adbc/drivermgr/wrapper.go
- go/adbc/drivermgr/wrapper_sqlite_test.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/panicdummy/driver.go
- go/adbc/pkg/snowflake/driver.go
- go/adbc/validation/validation.go
Implicit database release behaves inconsistently on different OS, which leads to bugs.
BREAKING CHANGE: adds Close to the Database interface.
Closes #1306.
> feat(go/adbc)!: close database explicitly 

- r/adbcpostgresql/src/Makevars.ucrt
As requested by Tomas:
```
Dear Dewey,
I am sorry to report that your package's Makevars.ucrt needs to be updated for an upcoming release of Rtools: one also has to link crypt32, please see the attached patch.
Please update so that your package will keep working in future versions of Rtools. This can be done unconditionally, because the library was available even before, just wasn't needed - so it should be fine to simply use the patch.
```
> fix(r/adbcpostgresql): Link -lcrypt32 on Windows

- docs/source/driver/snowflake.rst
- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
- go/adbc/driver/snowflake/statement.go
- go/adbc/go.mod
- go/adbc/go.sum
- Replace Snowflake bulk ingestion with Parquet-based approach with higher throughput and better type support
- Previously: INSERT bind parameters were uploaded to a CSV-based stage, once per record batch
- Now: Parquet files written concurrently to stage independently of record batch size. Parquet logical types are used to infer schema on COPY.
- Tests to validate type support and consistency through Arrow -> Parquet -> Snowflake -> Arrow roundtrip
- Improved type mapping between Arrow <-> Snowflake timestamps. [TIMESTAMP_LTZ](https://docs.snowflake.com/en/sql-reference/data-types-datetime#timestamp-ltz-timestamp-ntz-timestamp-tz) is more consistent with Arrow timestamp semantics than TIMESTAMP_TZ, which can lead to lossy roundtrips.
- Minor bugfix where Snowflake local timestamps with …
> feat(go/adbc/driver/snowflake): improve bulk ingestion speed

- go/adbc/driver/snowflake/driver_test.go
Minor fix to a test that has been breaking each time Snowflake added a new field to the result of a `SHOW WAREHOUSES` query.
Previously we asserted the number of columns, but this number has been changing. Instead of completely removing this part of the test, we can assert the columns we know currently should be present and expect that Snowflake won't make breaking changes to the schema by removing columns. The specific contents of the schema are not relevant to the original purpose of the test anyway, so it should be fine if the actual schema continues to grow beyond what is asserted here.
> fix(go/adbc/driver/snowflake): Make SHOW WAREHOUSES test less flaky

- .github/workflows/comment_bot.yml
- CONTRIBUTING.md
Resolves https://github.com/apache/arrow-adbc/issues/1347 .
> ci: add 'take' bot like main Arrow repo

- .github/workflows/packaging.yml
- ci/scripts/source_build.sh
- dev/release/rat_exclude_files.txt
> ci: include submodules in source archive

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryParameters.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/src/Drivers/BigQuery/readme.md
- csharp/test/Drivers/BigQuery/Apache.Arrow.Adbc.Tests.Drivers.BigQuery.csproj
- csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs
- csharp/test/Drivers/BigQuery/BigQueryTestingUtils.cs
- csharp/test/Drivers/BigQuery/ClientTests.cs
- csharp/test/Drivers/FlightSql/Apache.Arrow.Adbc.Tests.Drivers.FlightSql.csproj
- Adds value for a DestinationTable, which is needed for large results
- Removes old Arrow references in test projects
> fix(csharp/src/Drivers/BigQuery): fix support for large results

- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/postgres_type_test.cc
- introduce constant with key name
- introduce separate private method to add field-level method
Fixes #1515
> fix(c/driver/postgresql): add postgres type to cols created for numeric

- .github/workflows/native-unix.yml
- ci/scripts/python_test.sh
- docker-compose.yml
- python/adbc_driver_flightsql/tests/test_errors.py
- python/adbc_driver_manager/MANIFEST.in
- python/adbc_driver_manager/adbc_driver_manager/_blocking_impl.cc
- python/adbc_driver_manager/adbc_driver_manager/_blocking_impl.h
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyi
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_manager/setup.py
- python/adbc_driver_manager/tests/test_blocking.py
Alternative to #1486.
Fixes #1484.
> feat(python/adbc_driver_manager): handle KeyboardInterrupt

- go/adbc/driver/snowflake/snowflake_database.go
- python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py
To help Snowflake track adoption and usage of the ADBC driver, we can explicitly add a prefix to any client application name to indicate the ADBC driver is the source of the requests.
> feat(go/adbc/driver/snowflake): add '[ADBC]' to snowflake application name

- docs/source/driver/flight_sql.rst
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_database.go
- go/adbc/driver/flightsql/flightsql_driver.go
- go/adbc/driver/flightsql/timeouts.go
Add a test to ensure that the driver can still fetch data from a server that returns 1 unreachable and 1 reachable location. Also, add a new option to adjust the connect timeout.
Fixes #1527.
> test(go/adbc/driver/flightsql): test handling of bad locations

- c/driver/postgresql/connection.cc
- c/driver/postgresql/result_helper.h
- c/driver/postgresql/statement.cc
> refactor(c/driver/postgresql): update with C++17 conventions

- r/adbcsnowflake/R/adbcsnowflake-package.R
A follow-up to https://github.com/apache/arrow-adbc/pull/1525 to add an R-specific prefix for the Snowflake driver. We could allow this to be customized, too, but I would prefer to that feature to be requested before pursuing it.
Closes #1526.
> chore(r/adbcsnowflake): Add application name to Snowflake driver

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
In a query such as `SELECT * FROM bigquery-public-data.fhir_synthea.explanation_of_benefit`, a number of items return null inside of the StructArray result. An exception is thrown from the underlying Arrow calls because we hit a scenario where Length and index are both 0, so an `ArgumentOutOfRangeException` is thrown per https://github.com/apache/arrow/blob/280bc112b23976d2f17c07c638bb62702ac89e8a/csharp/src/Apache.Arrow/Arrays/BinaryArray.cs#L356.
> fix(csharp/src/Drivers/BigQuery): return null on GetValue exception

- .env
- .github/workflows/integration.yml
- .github/workflows/java.yml
- .github/workflows/native-unix.yml
- .github/workflows/nightly-website.yml
- .github/workflows/packaging.yml
- CONTRIBUTING.md
- java/driver/jdbc-validation-mssqlserver/src/test/java/org/apache/arrow/adbc/driver/jdbc/mssqlserver/MsSqlServerQuirks.java
- java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/PostgresqlQuirks.java
- java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/SqlTestUtil.java
> ci: configure env vars for CI in .env file

- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/utils.go
- python/adbc_driver_flightsql/pyproject.toml
- python/adbc_driver_flightsql/tests/test_errors.py
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgresql/pyproject.toml
- python/adbc_driver_snowflake/pyproject.toml
- python/adbc_driver_sqlite/pyproject.toml
Does not work in C/C++/Python due to #1576.
Fixes #1574.
> feat(go/adbc/driver/flightsql): reflect gRPC status in vendor code

- go/adbc/driver/flightsql/cmd/testserver/main.go
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_driver.go
- go/adbc/driver/flightsql/flightsql_statement.go
- python/adbc_driver_flightsql/adbc_driver_flightsql/__init__.py
- python/adbc_driver_flightsql/tests/test_incremental.py
> feat(go/adbc/driver/flightsql): expose FlightInfo during polling

- go/adbc/drivermgr/wrapper.go
- go/adbc/drivermgr/wrapper_sqlite_test.go
> fix(go/adbc/drivermgr): don't call potentially nil pointer

- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_connection.go
- go/adbc/go.mod
- go/adbc/go.sum
> feat(go/adbc/driver/flightsql): support reuse-connection location

- c/cmake_modules/AdbcDefines.cmake
- c/driver/common/utils.c
- c/driver/common/utils.h
- c/driver/postgresql/connection.cc
- c/driver/postgresql/copy/writer.h
- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite.c
- ci/scripts/python_wheel_windows_build.bat
- python/adbc_driver_manager/adbc_driver_manager/_blocking_impl.cc
- python/adbc_driver_manager/adbc_driver_manager/_lib.pxd
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/setup.py
This leaves warnings about dllexport/dllimport which will require further investigation.
Fixes #847.
> build(c): fix warnings for MSVC

- .env
- .github/workflows/packaging.yml
- ci/conda_env_python.txt
- ci/scripts/install_python.sh
- ci/scripts/python_sdist_test.sh
- ci/scripts/python_wheel_unix_test.sh
- ci/scripts/python_wheel_windows_test.bat
- python/adbc_driver_flightsql/adbc_driver_flightsql/__init__.py
- python/adbc_driver_flightsql/pyproject.toml
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgresql/adbc_driver_postgresql/__init__.py
- python/adbc_driver_postgresql/pyproject.toml
- python/adbc_driver_postgresql/tests/test_lowlevel.py
- python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py
- python/adbc_driver_snowflake/pyproject.toml
- python/adbc_driver_sqlite/adbc_driver_sqlite/__init__.py
- python/adbc_driver_sqlite/pyproject.toml
- Update versions to match upstream
- Add 3.8 support since upstream uses 3.8 as the base
- Adjust CI to test both 3.8 and 3.12
Fixes #1610.
> chore(ci): fix wheel builds

- .github/dependabot.yml
> ci: enable dependabot for golang, java

- c/driver/postgresql/copy/postgres_copy_writer_test.cc
- c/driver/postgresql/postgresql_benchmark.cc
- c/driver/postgresql/postgresql_test.cc
- c/vendor/nanoarrow/nanoarrow.h
- c/vendor/vendor_nanoarrow.sh
> build(c): don't expose Nanoarrow symbols

- .github/workflows/packaging.yml
- CONTRIBUTING.md
- docker-compose.yml
> ci: add C# to packaging.yml

- .pre-commit-config.yaml
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
- go/adbc/driver/flightsql/flightsql_adbc_test.go
- go/adbc/driver/snowflake/connection.go
Ports over TestMetadataGetObjectsColumnsXdbc from Snowflake to also be tested on FlightSQL.
Also makes the DomainSocketTest work correctly on Windows by correcting the expected path of the generated adbc.sock file.
Also removes an ineffectual assignment in the Snowflake driver that I couldn't commit without fixing.
Also Updates pre-commit as I again could not commit without fixing.
> test(go/adbc/driver/flightsql): Add TestMetadataGetObjectsColumnsXdbc test

- csharp/test/Drivers/Interop/Snowflake/CastTests.cs
- csharp/test/Drivers/Interop/Snowflake/ErrorHandlingTests.cs
- csharp/test/Drivers/Interop/Snowflake/SnowflakeTestingUtils.cs
Add tests to check for error handling of the following invalid input.
- invalid SQL syntax
- invalid column or table names
- invalid connection information (user, password)
- invalid driver information (location, entry point)
- invalid database, warehouse
> test(csharp/test/Drivers/Interop/Snowflake): test error handling

- .gitattributes
- c/driver_manager/adbc_driver_manager.cc
- go/adbc/drivermgr/adbc_driver_manager.cc
- r/adbcdrivermanager/R/error.R
> refactor(c/driver_manager): differentiate errors from driver manager

- .github/workflows/dev_pr.yml
My scanner picked up this vulnerability added recently. Just making a PR to fix it instead of going through the whole ASF reporting process because the workflow permissions are locked down to just PR and issues write and there are no secrets, so the worst someone could do is be a nuisance or try cache poisoning (which attackers don't know how to do...yet).
Ref:
https://securitylab.github.com/research/github-actions-untrusted-input/
> fix(ci): Sanitize PR title

- dev/release/verify-release-candidate.sh
- docs/source/development/releasing.rst
updating the docs and release verification script based on my experience for non-conda verification runs
> chore(dev/release): slight fix for non-conda verification and docs

- dev/release/verify-release-candidate.ps1
This changes two things to make release verification run on my system:
- Adds ` | Resolve-Path` to three variables to make them absolute paths. Without this, cpp_build.ps1 was running CMake and pointing at the wrong path because it saves a relative path, cds into another directory, and then tries to use the relative path.
- Adds `m2w64-gcc` inline to the `mamba create` call to make sure the Go has access to gcc for building. I was a little surprised the existing `compilers` package doesn't install gcc so I'm not sure if something might have changed upstream.
Fixes #1683
> chore(dev/release): Fix Windows verification under conda

- r/adbcdrivermanager/src/Makevars
- r/adbcpostgresql/src/Makevars.ucrt
- r/adbcsqlite/src/Makevars.in
Upon submitting adbcpostgresql to CRAN, there is now a build error for R 4.1 on Windows, which uses C++14 as its default standard if unspecified. This gives:
```
g++ -std=gnu++14  -I"D:/RCompile/recent/R-4.2.3/include" -DNDEBUG -I../src -DADBC_EXPORT="" -D__USE_MINGW_ANSI_STDIO    -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c connection.cc -o connection.o
In file included from connection.cc:37:
result_helper.h:37:8: error: 'optional' in namespace 'std' does not name a template type
37 |   std::optional<double> ParseDouble() const {
|        ^~~~~~~~
result_helper.h:37:3: note: 'std::optional' is only available from C++17 onwards
```
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-x86_64/adbcpostgresql-00inst …
> fix(r): Ensure CXX_STD is set everywhere

- .gitignore
- c/driver/sqlite/CMakeLists.txt
- c/driver/sqlite/sqlite_test.cc
I opened up the C drivers and ran the tests and got a failing test: when the driver compiles against system SQLite on MacOS, extension loading is not allowed (the symbols aren't even provided nor defined in the header). I added a define to make sure the R package could build on MacOS, but the test needs it too.
I also added come CMake to check this...I also tried `check_sybmol_exists` but this seems to require setting `CMAKE_REQUIRED_LIBRARIES`/includes which seems like it might have some global impact that we don't want. Checking for the text in the header does the trick for me (and is maybe less likely to result in accidentally building the library without extension support).
The other failing test I saw before seems to have been cleared up by the SQLite driver refactor!
The `.cache` in …
> fix: Ensure that test suite passes with system-provided SQLite on MacOS

- adbc.h
- go/adbc/adbc.go
- go/adbc/drivermgr/adbc.h
- java/core/src/main/java/org/apache/arrow/adbc/core/StandardStatistics.java
> fix(format): correct duplicated statistics names

- ci/conda_env_glib.txt
- glib/adbc-glib/connection.c
- glib/adbc-glib/connection.h
- glib/adbc-glib/meson.build
- glib/adbc-glib/version.h.in
- glib/test/helper.rb
- glib/test/helper/sandbox.rb
- glib/test/test-connection.rb
- glib/test/test-statistic-key.rb
Fixes #1743.
We use PostgreSQL instead of SQLite for testing. Because the SQLite driver doesn't support GetStatistics yet.
> feat(glib): Add garrow_connection_get_statistics()

- glib/adbc-glib/connection.c
- glib/adbc-glib/connection.h
- glib/test/test-connection.rb
Fixes #1747.
This is the binding of `AdbcConnectionGetStatisticNames()`.
> feat(glib): Add garrow_connection_get_statistic_names()

- .github/workflows/rust.yml
- rust/core/src/error.rs
- rust/core/src/ffi/constants.rs
- rust/core/src/ffi/methods.rs
- rust/core/src/ffi/mod.rs
- rust/core/src/ffi/types.rs
Hey!
Here is the second PR of the Rust implementation containing full FFI bindings.
I've decided to manually implement bindings instead of relying on [bindgen](https://rust-lang.github.io/rust-bindgen/) because:
- We don't want an additional dependency on clang (which bindgen depends on) and so we cannot generate bindings at compile-time
- We could have checked-in the generated bindings in git but in that case manually editing is unavoidable because generated bindings are platform-dependent
- Besides, we still have to implement default methods, conversion traits and release mechanisms.
In the end, I found it simpler to have everything manually implemented rather than having some parts automatic and some others manual... [arrow-rs](https://github.com/apache/arrow-rs) seems to have followed …
> feat(rust): add complete FFI bindings

- glib/adbc-arrow-glib/adbc-arrow-glib.h
- glib/adbc-arrow-glib/connection.c
- glib/adbc-arrow-glib/connection.h
- glib/adbc-arrow-glib/meson.build
- glib/adbc-arrow-glib/statement.c
- glib/adbc-arrow-glib/version.h.in
- glib/adbc-glib/connection.c
- glib/adbc-glib/connection.h
- glib/adbc-glib/statement.c
- glib/test/helper.rb
- glib/test/test-arrow-connection.rb
- glib/test/test-connection.rb
- ruby/lib/adbc.rb
- ruby/lib/adbc/arrow-connection.rb
- ruby/lib/adbc/connection-operations.rb
- ruby/lib/adbc/loader.rb
Fixes #1753.
It's a wrapper of `GADBCConnection` for Apache Arrow C GLib integration.
> feat(glib): add GADBCArrowConnection

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
> fix(csharp/src/Apache.Arrow.Adbc): Fix marshaling in three functions where it was broken

- .github/workflows/csharp.yml
- .github/workflows/native-unix.yml
- .github/workflows/nightly-verify.yml
- .github/workflows/packaging.yml
- .github/workflows/rust.yml
- .github/workflows/verify.yml
> ci: macos-latest now means M1

- csharp/src/Apache.Arrow.Adbc/AdbcStatement.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/Extensions/MarshalExtensions.cs
- csharp/src/Apache.Arrow.Adbc/PartitionDescriptor.cs
Implements the remaining functions in the 1.0 specification in the C interop layer.
Closes #1221
> feat(csharp): Implement remaining functions in 1.0 spec

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/Extensions/MarshalExtensions.cs
Fairly large restructuring of the importer/exporter code with an eye towards ensuring cleanup -- but also tightening the code.
> fix(csharp): imported drivers have the potential for a lot of memory leaks

- csharp/test/Apache.Arrow.Adbc.Tests/Apache.Arrow.Adbc.Tests.csproj
- csharp/test/Apache.Arrow.Adbc.Tests/DuckDbFixture.cs
- csharp/test/Apache.Arrow.Adbc.Tests/ImportedDuckDbTests.cs
Adds support for running tests against DuckDb and implements a simple smoke test.
> feat(csharp/test): implement DuckDb test fixture

- .env
Enclose URL variables in `.env` with quotes to fix parsing errors caused by special characters like `&`.
Resolve #1778
> chore: wrap .env values in quotes to prevent parsing errors

- .github/workflows/packaging.yml
- ci/linux-packages/Rakefile
- dev/release/01-prepare.sh
- dev/release/02-sign.sh
- dev/release/03-source.sh
- dev/release/04-java-upload.sh
- dev/release/05-linux-upload.sh
- dev/release/06-binary-verify.sh
- dev/release/post-01-upload.sh
- dev/release/post-02-binary.sh
- dev/release/post-03-python.sh
- dev/release/post-04-go.sh
- dev/release/post-06-ruby.sh
- dev/release/post-07-csharp.sh
- dev/release/post-09-bump-versions.sh
- dev/release/post-10-website.sh
- dev/release/utils-common.sh
- dev/release/utils-prepare.sh
- dev/release/versions.env
Start refactoring our release process so that we can theoretically handle different version numbers in different language subprojects.
Fixes #1490.
> chore(dev/release): decouple version numbers

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
Workaround to fix #1454 until snowflake addresses https://github.com/snowflakedb/gosnowflake/issues/1110 with a better solution (hopefully by having the server actually return Arrow...)
> fix(go/adbc/driver/snowflake): workaround snowflake metadata-only limitations

- go/adbc/driver/snowflake/driver_test.go
Fixing an issue showing up in test runs such as https://github.com/apache/arrow-adbc/actions/runs/8898022790/job/24435792042
> test(go/adbc/driver/snowflake): missed a quote

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/C/Delegates.cs
- csharp/src/Apache.Arrow.Adbc/C/NativeDelegate.cs
> feat(csharp): imported objects should have call "release" when no longer in use

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/Extensions/CollectionExtensions.cs
- csharp/src/Client/AdbcCommand.cs
- csharp/src/Client/AdbcConnection.cs
- csharp/src/Client/AdbcDataReader.cs
- csharp/test/Drivers/Interop/Snowflake/CastTests.cs
- csharp/test/Drivers/Interop/Snowflake/ClientTests.cs
- csharp/test/Drivers/Interop/Snowflake/DriverTests.cs
> fix(csharp): an assortment of small fixes not worth individual pull requests

- csharp/src/Apache.Arrow.Adbc/AdbcException.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/src/Apache.Arrow.Adbc/C/Delegates.cs
Validates that required function pointers are present in an imported driver and backfills optional functions to return ADBC_STATUS_NOT_IMPLEMENTED.
Closes #1811
> fix(csharp/src/Apache.Arrow.Adbc/C): correctly handle null driver entries for imported drivers

- c/driver/snowflake/snowflake_test.cc
- go/adbc/driver/snowflake/binding.go
- go/adbc/driver/snowflake/concat_reader.go
- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/statement.go
- go/adbc/go.mod
- go/adbc/go.sum
> feat(go/adbc/driver/snowflake): support parameter binding

- dev/release/verify-release-candidate.sh
> fix(dev/release): handle versioning scheme in binary verification

- ci/linux-packages/Rakefile
- ci/linux-packages/yum/apache-arrow-adbc.spec.in
We should use the major part of `VERSION_NATIVE` not `RELEASE` for RPM package name.
(We should use `RELEASE` only for RPM version.)
Fixes #1837.
> chore(ci/linux-packages): fix RPM packages name

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
Allow imported objects to access a disposed driver when they themselves are disposed, because finalization order is nondeterministic.
Closes #1817
> fix(csharp/src/Apache.Arrow.Adbc/C): finalizer threw exception

- ci/linux-packages/yum/apache-arrow-adbc.spec.in
RPM generates dependencies automatically based on package contents such as `.pc`. Let's use it instead of specifying `arrow-glib-devel` explicitly by `Requires:`.
Fixes #1839.
> chore(ci/linux-packages): remove explicit arrow-glib-devel dependency

- ci/conda_env_glib.txt
- ci/conda_env_python.txt
Since (1) there is no arrow-c-glib for 16.0.0 yet and (2) for 16.0.0 we need to switch to pyarrow-all
> chore(dev/release): pin 15.0.2 for now

- csharp/Directory.Build.props
- csharp/src/Apache.Arrow.Adbc/Apache.Arrow.Adbc.csproj
- csharp/src/Client/Apache.Arrow.Adbc.Client.csproj
- csharp/src/Drivers/Apache/Apache.Arrow.Adbc.Drivers.Apache.csproj
- csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj
- csharp/src/Drivers/FlightSql/Apache.Arrow.Adbc.Drivers.FlightSql.csproj
- csharp/src/Drivers/Interop/Snowflake/Apache.Arrow.Adbc.Drivers.Interop.Snowflake.csproj
- csharp/test/Apache.Arrow.Adbc.Tests/Apache.Arrow.Adbc.Tests.csproj
- csharp/test/Drivers/Apache/Apache.Arrow.Adbc.Tests.Drivers.Apache.csproj
- csharp/test/Drivers/BigQuery/Apache.Arrow.Adbc.Tests.Drivers.BigQuery.csproj
- csharp/test/Drivers/FlightSql/Apache.Arrow.Adbc.Tests.Drivers.FlightSql.csproj
- csharp/test/Drivers/Interop/Snowflake/Apache.Arrow.Adbc.Tests.Drivers.Interop.Snowflake.csproj
- csharp/test/SmokeTests/Apache.Arrow.Adbc.SmokeTests/Apache.Arrow.Adbc.SmokeTests.csproj
- csharp/test/SmokeTests/BigQuery/Apache.Arrow.Adbc.SmokeTests.Drivers.BigQuery.csproj
- csharp/test/SmokeTests/FlightSql/Apache.Arrow.Adbc.SmokeTests.Drivers.FlightSql.csproj
- csharp/test/SmokeTests/Interop/Snowflake/Apache.Arrow.Adbc.SmokeTests.Drivers.Interop.Snowflake.csproj
> feat(csharp): Move more options to be set centrally and enable TreatWarningsAsErrors

- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- csharp/src/Drivers/Apache/Impala/ImpalaStatement.cs
- csharp/src/Drivers/Apache/Spark/SparkStatement.cs
- csharp/test/Drivers/Apache/Spark/StatementTests.cs
Implement AdbcStatement.SetOption on Spark driver
* `"adbc.statement.polltime_milliseconds"` -> sets the poll time to check for results to execute a statement.
* `"adbc.statement.batch_size"` -> sets the maximum size of a single batch to receive.
> feat(csharp/src/Drivers/Apache): add implementation for AdbcStatement.SetOption on Spark driver

- csharp/src/Drivers/Apache/Spark/SparkConnection.cs
Addresses a TODO item to accurately retrieve the precision and scale for `DECIMAL` (`Decimal128Type`) when retrieving table schema (`GetTableSchema`).
* Parses the type name to find the precision and scale, using the default of 10 and 0, respectively.
> fix(csharp/src/Drivers/Apache): set the precision and scale correctly on Decimal128Type

- csharp/src/Apache.Arrow.Adbc/AdbcConnection11.cs
- csharp/src/Apache.Arrow.Adbc/AdbcDatabase11.cs
- csharp/src/Apache.Arrow.Adbc/AdbcDriver11.cs
- csharp/src/Apache.Arrow.Adbc/AdbcStatement11.cs
- csharp/src/Apache.Arrow.Adbc/Results.cs
For #1843, redefines the C# APIs to prioritize full async support. As this is making a number of breaking changes already, it also takes the opportunity to do some general cleanup.
Async methods that are generally expected to run locally (e.g. GetOption/SetOption) are defined to return ValueTask and have their default implementation be synchronous. Async methods that are generally expected to run remotely are defined to return Task and have their default implementations be asynchronous.
My mental model for the four ADBC "object" types is as follows:
The driver is analogous to the ODBC or JDBC driver, or ADO.NET provider. In JDBC, this type is represented by the java.sql.Driver interface. In ADO.NET, it's represented by the DbProviderFactory class. Because this object is strictly about …
> feat(csharp): redefine C# APIs to prioritize full async support

- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
- go/adbc/go.mod
- go/adbc/go.sum
Reproduces and fixes: #1847 
Parquet files with empty row groups are valid per the spec, but Snowflake does not currently handle them properly. To mitigate this we buffer writes to the parquet file so that a row group is not written until some amount of data has been received.
The CheckedAllocator was enabled for all tests as part of this fix, which detected a leak in the BufferWriter that was fixed in: [https://github.com/apache/arrow/pull/41698](https://github.com/apache/arrow/pull/41698).
There was an unrelated test failure that surfaced once the CheckedAllocator was enabled which had to do with casting decimals of certain precision. The fix is included in this PR as well.
> fix(go/adbc/driver/snowflake): Records dropped on ingestion when empty batch is present

- go/adbc/pkg/_tmpl/driver.go.tmpl
Hi, this PR should be a minor update for the go driver template which bumps arrow from v16 to v17.
> chore(go/adbc): bump arrow from v16 to v17 in template

- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
- .github/workflows/rust.yml
- python/adbc_driver_flightsql/tests/test_errors.py
- rust/core/Cargo.toml
- rust/core/src/driver_exporter.rs
- rust/core/src/driver_manager.rs
- rust/core/src/error.rs
- rust/core/src/ffi/types.rs
- rust/core/src/lib.rs
- rust/drivers/dummy/src/lib.rs
Hey!
Here is the penultimate PR containing the driver manager for Rust.
The last PR will contain all the integration tests.
> feat(rust): add the driver manager

- .pre-commit-config.yaml
- csharp/src/Drivers/Apache/Spark/SparkConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkParameters.cs
- csharp/test/Drivers/Apache/Spark/SparkTestBase.cs
- Adds the parameter naming convention to match other adbc projects
- Fixes the UserAgent name
> fix(csharp/src/Drivers/Apache/Spark): fix parameter naming convention

- csharp/src/Drivers/Apache/Spark/SparkConnection.cs
- csharp/src/Drivers/Apache/Spark/SqlTypeNameParser.cs
- csharp/test/Drivers/Apache/Spark/DriverTests.cs
- csharp/test/Drivers/Apache/Spark/StatementTests.cs
The native response from Spark/Databricks for the type name in the column metadata (which is used to populate the `XdbcTypeName` column in the `GetObjects` call) includes both the base type and the precision and scale clause for DECIMAL/CHAR/VARCHAR. For example, `DECIMAL(38,2)`, `CHAR(255)`, `VARCHAR(255)`, etc.
This change removes the trailing precision and scale clause `( precision [ , scale ] )` from returned value for `XdbcTypeName`. As well, the `XdbcColumnSize` is now being populated with the maximum precision of `VARCHAR` and the fixed length of `CHAR` types. 
Examples:
| Native Type Name| XdbcTypeName | XdbcColumnSize | XdbcDecimalDigits |
| -------------          | -------------        | ------------- | ------------- |
| VARCHAR(255) | VARCHAR | 255 | `null` |
| CHAR(255) | CHAR …
> feat(csharp/src/Drivers/Apache): improve type name handling for CHAR/VARCHAR/DECIMAL

- csharp/src/Drivers/Interop/Snowflake/Apache.Arrow.Adbc.Drivers.Interop.Snowflake.csproj
Swapping PreBuildEvent to DispatchToInnerBuilds which accomplishes the same for multiple frameworks.
This will ensure the Snowflake build scripts are run only once during a dotnet pack.
> fix(csharp/src/Drivers/Interop/Snowflake): Swapping PreBuildEvent to DispatchToInnerBuilds

- rust/Cargo.lock
- rust/README.md
- rust/core/src/ffi/constants.rs
- rust/core/src/lib.rs
- rust/core/src/options.rs
- rust/core/tests/common/mod.rs
- rust/core/tests/driver_manager_sqlite.rs
- rust/drivers/dummy/src/lib.rs
- rust/drivers/dummy/tests/driver_exporter_dummy.rs
This should be the last PR for the initial Rust implementation.
It includes:
- An integration test for the driver manager against the official SQLite driver
- An integration test for the dummy driver against itself (comparing output when using the Rust API and when using its exported version through the driver manager)
- New info codes and options which have been added recently
- An enum for identifying statistics
Note that I also have an integration test for the driver manager against the official PostgreSQL driver but it needs a running PostgreSQL instance to be executed, so it cannot be easily integrated into the CI. This test proved useful during development as it allowed me to catch some bugs. The existence of this test is the reason why there is a common module. Maybe we can add it …
> feat(rust): add integration tests and some improvements

- ci/conda_env_docs.txt
- docs/source/driver/installation.rst
> docs: clarify that PyArrow is required for DBAPI

- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/flightsql/utils.h
- go/adbc/pkg/panicdummy/driver.go
- go/adbc/pkg/panicdummy/utils.h
- go/adbc/pkg/snowflake/driver.go
- go/adbc/pkg/snowflake/utils.h
We think malloc'ing a C struct is one possible way the Go garbage collector may still be seeing invalid Go pointers.  See #1931.
> fix(go/adbc/pkg): guard against potential crash

- c/driver/postgresql/statement.cc
- python/adbc_driver_postgresql/tests/test_dbapi.py
PostgreSQL apparently has an internal limit - split up batches to stay under that limit.  It doesn't care about message boundaries in this mode, so we can chunk naively.
Fixes #1921.
> fix(c/driver/postgresql): chunk large COPY payloads

- c/CMakeLists.txt
- c/driver/common/utils.c
- c/driver/sqlite/statement_reader.c
- c/meson.build
- c/validation/adbc_validation_statement.cc
closes https://github.com/apache/arrow-adbc/issues/1944
In its current state this fails cpplint, which (for arguably good reason) discourages use of gmtime in favor of gmtime_r. The macros are inspired by similar code in the vendored sqlite.c source however, so I think reasonably accommodate that concern. 
Not sure if its worth trying to work around that with cpplint or just disable it for C sources
> fix(c/driver/sqlite): Make SQLite driver C99 compliant

- c/driver/postgresql/copy/postgres_copy_writer_test.cc
- c/driver/postgresql/copy/writer.h
More progress towards https://github.com/apache/arrow-adbc/issues/1950
> feat(c/driver/postgresql): UInt(8/16/32) Writer

- .github/workflows/r-standard.yml
- c/vendor/nanoarrow/nanoarrow.hpp
In some of the R packages we get:
```
* checking whether package 'adbcsqlite' can be installed ... [35s] WARNING
Found the following significant warnings:
../src/c/vendor/nanoarrow/nanoarrow.hpp:868:19: warning: 'nanoarrow::ViewArrayStream::code_' will be initialized after [-Wreorder]
../src/c/vendor/nanoarrow/nanoarrow.hpp:867:15: warning:   'ArrowError* nanoarrow::ViewArrayStream::error_' [-Wreorder]
../src/c/vendor/nanoarrow/nanoarrow.hpp:828:3: warning:   when initialized here [-Wreorder]
See 'D:/a/arrow-adbc/arrow-adbc/r/adbcsqlite/check/adbcsqlite.Rcheck/00install.out' for details.
```
https://github.com/apache/arrow-adbc/actions/runs/9788345921/job/27026279250?pr=1965#step:10:166
This has already been fixed upstream:
https://github.com/apache/arrow-nanoarrow/blob/c74bb37b990541c8230 …
> fix(c/vendor/nanoarrow): Fix -Wreorder warning

- c/driver/postgresql/copy/postgres_copy_writer_test.cc
- c/driver/postgresql/copy/writer.h
Another enhancement for https://github.com/apache/arrow-adbc/issues/1882
> feat(c/driver/postgresql): FIXED_SIZED_LIST Writer support

- r/adbcdrivermanager/src/radbc.cc
In the development version of R, calling `R_ExternalPtrAddrFn()` on an SEXP that is not an external pointer will raise an error. Because we test the error message, the order of our check vs. the call to `R_ExternalPtrAddrFn()` matters. In general, it makes more sense to do our own check first anyway!
https://cran.r-project.org/web/checks/check_results_adbcdrivermanager.html
```
> test_check("adbcdrivermanager")
[ FAIL 1 | WARN 0 | SKIP 3 | PASS 176 ]
══ Skipped tests (3) ═══════════════════════════════════════════════════════════
• On CRAN (3): 'test-driver_log.R:19:3', 'test-helpers.R:22:3',
'test-helpers.R:112:3'
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-radbc.R:188:3'): invalid external pointer inputs generate errors ──
Error in …
```
> fix(r/adbcdrivermanager): Ensure that class of object is checked before calling R_ExternalPtrAddrFn

- c/driver/postgresql/copy/writer.h
As identified by the CRAN checks:
```
Version: 0.12.0
Check: whether package can be installed
Result: WARN
Found the following significant warnings:
c/driver/postgresql/copy/writer.h:218:37: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
See ‘/data/gannet/ripley/R/packages/tests-devel/adbcpostgresql.Rcheck/00install.out’ for details.
* used C++ compiler: ‘g++-14 (GCC) 14.1.0’
```
https://cran.r-project.org/web/checks/check_results_adbcpostgresql.html
> fix(c/driver/postgresql): Fix compiler warning on gcc14

- c/driver/postgresql/copy/writer.h
This is a follow up to https://github.com/apache/arrow-adbc/pull/1962, which required each writer construction to subsequently call `->Init()` to assign to a protected array_view_ member.
This takes inspiration from the following cpp guideline to have the class manage its construction more appropriately:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#discussion-use-a-factory-function-if-you-need-virtual-behavior-during-initialization
> refactor(c/driver/postgresql): Factory func for CopyWriter construction

- go/adbc/driver/flightsql/cmd/testserver/main.go
- go/adbc/driver/flightsql/flightsql_connection.go
- python/adbc_driver_flightsql/tests/conftest.py
- python/adbc_driver_flightsql/tests/test_errors.py
> fix(go/adbc/driver/flightsql): propagate headers in GetObjects

- c/driver/flightsql/meson.build
- c/driver/postgresql/meson.build
- c/driver/snowflake/meson.build
- c/driver/sqlite/adbc-driver-sqlite.pc.in
- c/driver/sqlite/meson.build
- c/driver_manager/adbc-driver-manager.pc.in
- c/driver_manager/meson.build
- c/meson.build
> feat(c): Add pkgconfig support to Meson build system

- c/driver/bigquery/meson.build
- c/meson.build
- c/meson.options
Quick follow up to https://github.com/apache/arrow-adbc/pull/1722
meson test skips everything at the moment - didn't see this getting tested in CI so assuming its something done offline
> feat(c): Add BigQuery library to Meson build system

- docs/source/driver/snowflake.rst
- python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py
It was brought up in #1997 that the currently published options for snowflake bulk ingestion are incorrect in the docs. This corrects them to the proper values that are consistent with the values in the implementation.
This also adds new constants to the python `StatementOptions` enum for the snowflake driver for users to reference.
> fix(docs): correct snowflake options for bulk ingest

- CONTRIBUTING.md
Fix broken link for Mambaforge installation in `CONTRIBUTING.md`.
> fix(docs): update broken link

- go/adbc/driver/snowflake/bulk_ingestion.go
> feat(go/adbc/driver/snowflake): use vectorized scanner for bulk ingest

- c/driver/postgresql/connection.cc
- c/driver/postgresql/postgresql_test.cc
- c/validation/adbc_validation_statement.cc
Fixes #2006.
I am not sure of the best way to test this...is there a reliable way to generate a schema whose columns will be out of order when queried in this way? Is case-sensitivity something that we should test across all backends or should this be a Postgres-specific test?
> fix(c/driver/postgresql): Ensure schema ordering is consisent and respects case sensitivity of table names

- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/driver/snowflake/bulk_ingestion_test.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
Fixes: #1997 
**Core Changes**
- Change ingestion `writeParquet` function to use unbuffered writer, skipping 0-row records to avoid recurrence of #1847
- Use parquet writer's internal `RowGroupTotalBytesWritten()` method to track output file size in favor of `limitWriter`
- Unit test to validate that file cutoff occurs precisely when expected
**Secondary Changes**
- Bump arrow dependency to `v18` to pull in the changes from [ARROW-43326](https://github.com/apache/arrow/pull/43326)
- Fix flightsql test that depends on hardcoded arrow version
> fix(go/adbc/driver/snowflake): split files properly after reaching targetSize on ingestion

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryParameters.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs
- csharp/test/Drivers/BigQuery/BigQueryTestingUtils.cs
Adds a new option to support specifying the timeout value for a query
> feat(csharp/src/Drivers/BigQuery): add support for configurable query timeouts

- .github/workflows/r-check.yml
- .github/workflows/r-extended.yml
The R check actions are currently failing because an update to r-lib actions resulted in some quarto actions being invoked, and these have not yet been whitelisted for use in Apache repositories. We don't actually need quarto for anything in the R package; however, the action is written in such a way that even though the step is skipped, the action is still loaded (and therefore its name is checked against the whitelist).
Unrelatedly, the extended R check was failing because I forgot to copy a change from #1965 into one of the workflows that only runs once a week.
> fix(ci): Pin r-lib actions as a workaround for latest action updates

- csharp/src/Apache.Arrow.Adbc/Extensions/StandardSchemaExtensions.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/test/Drivers/BigQuery/BigQueryData.cs
Fixes to make the following BigQuery tests pass:
- VerifySchemaTablesWithNoConstraints
- VerifyTypesAndValues
> fix(csharp/src/Drivers/BigQuery): update BigQuery test cases

- c/driver/postgresql/connection.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/result_helper.cc
- c/driver/postgresql/result_helper.h
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/validation/adbc_validation_util.cc
- c/validation/adbc_validation_util.h
- python/adbc_driver_postgresql/tests/test_dbapi.py
- rust/Cargo.lock
I started this PR wanting to get queries with parameters able to return their results; however, this turned into a PR leaning in to the `PqResultHelper` because it was helpful to export arrays from the `PGresult*` but wasn't quite general enough. I did a second bit of shuffling to make it (possibly, or maybe just for me) easier to understand what path gets taken on `ExecuteQuery()`.
Some side effects of these changes are that we can now support multiple statements in the same query (by using `PQexec()` instead of `PQexecParams()` when there is no output requested) and that we can `ExecuteSchema()` for all parameterized queries.
The actual feature is that a user can set `adbc.postgresql.use_copy = FALSE` to force a non-COPY path for queries that aren't supported there. Because we request …
> feat(c/driver/postgresql): Implement consuming a PGresult via the copy reader

- c/driver/postgresql/statement.cc
- c/driver/sqlite/statement_reader.c
- c/validation/adbc_validation.h
- c/validation/adbc_validation_statement.cc
I think this didn't work because we only ever wrote COPY output to the connection after each array, so if there were no arrays, there was no header sent!
Closes #2071.
After this PR:
``` r
#> Warning: package 'adbcdrivermanager' was built under R version 4.3.3
con <- adbc_database_init(
adbcpostgresql::adbcpostgresql(), 
uri = "postgresql://localhost:5432/postgres?user=postgres&password=password"
) |> 
adbc_connection_init()
con |> 
execute_adbc("DROP TABLE IF EXISTS no_integers")
nanoarrow::basic_array_stream(
list(), 
nanoarrow::na_struct(list(x = nanoarrow::na_int32()))
) |> 
write_adbc(con, "no_integers")
con |> 
read_adbc("SELECT * from no_integers") |> 
tibble::as_tibble()
#> # A tibble: 0 × 1
#> # ℹ 1 variable: x <int>
```
<sup>Created on 2024-08-11 with …
> fix(c/driver/postgresql): Fix ingest of streams with zero arrays

- go/adbc/driver/flightsql/flightsql_adbc_test.go
Do some more thorough testing of the header option to hopefully avoid more bugs around this.
> test(go/adbc/driver/flightsql): more testing of header parameter

- docs/source/python/recipe/driver_manager.rst
- docs/source/python/recipe/driver_manager_lowlevel.py
- docs/source/python/recipe/driver_manager_prepare.py
> docs: add recipe for `adbc_prepare` and low-level bindings

- docs/source/python/recipe/driver_manager_lowlevel.py
Small follow-up on https://github.com/apache/arrow-adbc/pull/2097
This method is available starting from pyarrow 15.0, only one release after introduction of the general protocol, so I think it should be fine to just use that.
> docs(python): use public API to consume stream handle

- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/go.mod
- go/adbc/go.sum
Fixes: #2094
Two primary changes:
- Skip uploading parquet files that never had any rows written to them
- This reduces number of files Snowflake must keep track of, improving success rate of the COPY command
- Keep track of all files uploaded to stage and ensure they are actually copied
- Retry the COPY command up to 5 times with backoff if files any files haven't been copied
**Snowflake Test Output**
```
➜  adbc git:(gh-2094) ✗ go test -v ./driver/snowflake/...
=== RUN   TestIngestBatchedParquetWithFileLimit
--- PASS: TestIngestBatchedParquetWithFileLimit (0.00s)
=== RUN   TestValidation
=== RUN   TestValidation/TestNewDatabase
=== RUN   TestValidation/TestAutocommitDefault
=== RUN   TestValidation/TestAutocommitToggle
=== RUN   TestValidation/TestCloseConnTwice
=== RUN …
```
> feat(go/adbc/driver/snowflake): Keep track of all files copied and skip empty files in bulk_ingestion

- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/postgres_type_test.cc
- docs/source/driver/postgresql.rst
> feat(c/driver/postgresql): add `arrow.opaque` type metadata

- c/CMakeLists.txt
- c/driver_manager/CMakeLists.txt
We shouldn't install headers that weren't enabled (the conda-forge packages check for this).
Fixes #2126.
> build(c): don't install adbc.h unless driver manager is enabled

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
This PR updates the error handling such that we properly call `PQgetresult()` and report Postgres-generated errors that occur before Postgres sends the header information. This probably wasn't reported until now because most queries with errors will error in the "prepare" step or didn't specifically generate an execution error on the very first result.
Closes #2133.
> fix(c/driver/postgresql): Improve error reporting for queries that error before the COPY header is sent

- java/pom.xml
That way dependabot can bump them together and keep it consistent
> chore(java): use property for checkerframework versions

- csharp/test/Drivers/Interop/Snowflake/DriverTests.cs
- csharp/test/Drivers/Interop/Snowflake/Resources/snowflakeconfig.json
- csharp/test/Drivers/Interop/Snowflake/SnowflakeTestConfiguration.cs
- csharp/test/Drivers/Interop/Snowflake/SnowflakeTestingUtils.cs
- Introduces a test to demonstrate the behavior of using DEFAULT_ROLE for ADBC, and then changes the role using the `adbc.snowflake.sql.role` parameter and validates the user is executing in the new role context. 
- Closes https://github.com/apache/arrow-adbc/issues/2080
> fix(csharp/src/Drivers/Interop/Snowflake): add test to demonstrate DEFAULT_ROLE behavior

- c/driver/postgresql/copy/postgres_copy_writer_test.cc
- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/postgres_type_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/driver/sqlite/sqlite_test.cc
- c/driver_manager/adbc_driver_manager_test.cc
- c/validation/adbc_validation.h
- c/validation/adbc_validation_connection.cc
- c/validation/adbc_validation_statement.cc
- c/validation/adbc_validation_util.cc
- c/validation/adbc_validation_util.h
This PR adds list ingest support in the PostgreSQL driver. The raw COPY and type support had already been added; however, there were still some hard-coded switch-on-type that implemented some necessary features (e.g., the CREATE TABLE syntax for each type). I moved these to the type/copy section and removed the previous implementation (which should also help for a future PR implementing the ability to bind nested types as parameters).
I also added the infrastructure to test this in all drivers via the validation suite, which required modifying some of the built-in concepts to accommodate a nested type.
Closes #2066.
``` r
con <- adbc_database_init(
adbcpostgresql::adbcpostgresql(),
uri = "postgresql://localhost:5432/postgres?user=postgres&password=password"
) |> …
```
> feat(c/driver/postgresql): Implement ingestion of list types for PostgreSQL

- c/driver/postgresql/bind_stream.h
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/result_reader.cc
- c/driver/postgresql/result_reader.h
- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite.cc
- c/validation/adbc_validation.h
- c/validation/adbc_validation_statement.cc
- c/validation/adbc_validation_util.h
This PR refactors the `BindStream` to use the COPY writer instead of its own serialization logic. This logic is the same between insertion and binding, although the API used to send it to the database is slightly different. This is a helpful consolidation of logic and means that adding type support on the Arrow or Postgresql side (or fixing bugs in the inference or serialization) is slightly easier. It also means we can bind parameters that are lists and is a workaround for inserting into a table with a schema where Postgres knows how to cast the types (but ADBC might not yet).
``` r
library(nanoarrow)
con <- adbc_database_init(
adbcpostgresql::adbcpostgresql(),
uri = "postgresql://localhost:5432/postgres?user=postgres&password=password"
) |> …
```
> refactor(c/driver/postgresql): Use copy writer in BindStream for parameter binding

- csharp/src/Apache.Arrow.Adbc/AdbcConnection.cs
- csharp/src/Apache.Arrow.Adbc/AdbcConnection11.cs
- csharp/test/Drivers/Interop/Snowflake/DriverTests.cs
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/driver_test.go
This PR removes the parameterization for calls to USE DATABASE and USE SCHEMA, which isn't supported for Snowflake DDL. It also modifies the GetObjects call to set the context to the database and schema, since the GetObjects call uses a sql.DB connection context instead of the snowflakeConn connection context. 
Fixes https://github.com/apache/arrow-adbc/issues/2167
Fixes https://github.com/apache/arrow-adbc/issues/2168
> fix(go/adbc/driver/snowflake): fix setting database and schema context after initial connection

- c/driver/common/utils.c
- c/driver/common/utils.h
- c/driver/framework/status.h
- c/driver/postgresql/connection.cc
- c/driver/postgresql/error.cc
- c/driver/postgresql/error.h
- c/driver/postgresql/postgresql.cc
- c/driver/postgresql/result_helper.cc
- c/driver/postgresql/result_helper.h
- c/driver/postgresql/result_reader.cc
- c/driver/postgresql/result_reader.h
- c/driver/postgresql/statement.cc
- python/adbc_driver_postgresql/tests/test_dbapi.py
This PR migrates the internal PqResultHelper and PqResultReader to use the Status error handling system. This is to make it less painful to transition the bind stream and objects helper (and later the database/connection/statement) to the framework.
The CI failures are still GLib packaging and Python packaging.
> refactor(c/driver/postgresql): Use Status instead of AdbcStatusCode/AdbcError in result helper

- c/driver/postgresql/bind_stream.h
- c/driver/postgresql/result_helper.h
- c/driver/postgresql/result_reader.cc
- c/driver/postgresql/statement.cc
This PR migrates the `BindStream` to use the `PqResultHelper` and `Status`!
I believe the CI failure are still glib and Python packaging.
> refactor(c/driver/postgresql): Use Status for error handling in BindStream

- ci/conda_env_glib.txt
- ci/scripts/python_wheel_unix_build.sh
Work around #2176.
Fixes #2163.
> chore(ci): pin build dependencies to work around issues

- csharp/src/Drivers/Apache/Hive2/DecimalUtility.cs
- csharp/test/Drivers/Apache/Hive2/DecimalUtilityTests.cs
Fixed two bugs
1. scale should be able to be the same as precision
2. when leading zeros in fractional portion and positive exponent, the significant digits where not calculated correctly.
> fix(csharp/src/Drivers/Apache/Spark): correct precision/scale handling with zeros in fractional portion

- csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- csharp/test/Apache.Arrow.Adbc.Tests/TestConfiguration.cs
- csharp/test/Drivers/Apache/ApacheTestConfiguration.cs
- csharp/test/Drivers/Apache/Spark/SparkTestEnvironment.cs
- csharp/test/Drivers/Apache/Spark/StatementTests.cs
Fixes 
1. How HiveServer2Statement.BatchSize is used in the HiveServer2Reader
2. Batch size valid range
3. Test cases
> fix(csharp/src/Drivers/Apache/Spark): correct BatchSize implementation for base reader

- .github/workflows/r-extended.yml
This PR fixes the failing weekly extended R workflow, which is currently failing because of how pak installs `local::` packages. This was fixed for other workflows but not for valgrind because the other workflows use the reusable `r-check.yml` action.
Failure: https://github.com/apache/arrow-adbc/actions/runs/11088200259/job/30807805100
> chore(ci): Fix install of local driver manager in valgrind extended checks

- docs/source/driver/snowflake.rst
- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/snowflake_database.go
Adds a new option to set a client config file to set https://github.com/snowflakedb/gosnowflake/blob/a26ac8a1b9a0dda854ac5db9c2c145f79d5ac4c0/doc.go#L130 as a driver option.
> feat(go/adbc/driver/snowflake): add support for a client config file

- CONTRIBUTING.md
- ci/conda_env_glib.txt
- dev/release/verify-release-candidate.sh
Use Miniforge instead of Mambaforge, as the latter has been deprecated.
Closes #2206
> chore(dev): Use Miniforge instead of Mambaforge

- csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs
- csharp/src/Drivers/Apache/Impala/ImpalaConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkDatabricksConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/test/Drivers/Apache/Spark/DriverTests.cs
1. Fixes batch handling of the HiveServer2Reader so that it retrieves all subsequent batches after the first batch.
2. Adds async look-ahead fetch for improved performance.
3. Adds test to ensure all records are retrieved regardless of batch size.
> fix(csharp/src/Drivers/Apache/Spark): correct batch handling for the HiveServer2Reader

- .github/workflows/rust.yml
- rust/core/src/driver_manager.rs
This step fails on `main` because the `build` directory does not exist. This was added in #2208, but never ran because the `native-unix` job was failing because of flaky tests.
> chore(ci): fix Rust workflow

- csharp/src/Drivers/Apache/Apache.Arrow.Adbc.Drivers.Apache.csproj
- csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj
- csharp/test/Apache.Arrow.Adbc.Tests/Apache.Arrow.Adbc.Tests.csproj
Update System.Text.Json to version 8.0.5 because of known vulnerability in version 8.0.4.
> fix(csharp/src/Drivers): update System.Text.Json to version 8.0.5 because of known vulnerability

- java/core/pom.xml
- java/dev/license/asf-xml.license
- java/driver-manager/pom.xml
- java/driver/flight-sql-validation/pom.xml
- java/driver/flight-sql/pom.xml
- java/driver/jdbc-validation-derby/pom.xml
- java/driver/jdbc-validation-mssqlserver/pom.xml
- java/driver/jdbc-validation-postgresql/pom.xml
- java/driver/jdbc/pom.xml
- java/driver/validation/pom.xml
- java/pom.xml
- java/sql/pom.xml
Add spotless configuration to automatically format Maven `pom.xml` files using Apache Maven style convention.
Closes #2239
> chore(java): auto-format maven pom.xml files

- rust/core/src/driver_manager.rs
- rust/drivers/dummy/src/lib.rs
> fix(rust): implement database/connection constructors without options

- .github/workflows/dev.yml
- dev/release/verify-release-candidate.sh
Various dependencies don't quite work with 3.13 yet.
> chore(dev/release): pin Python 3.12 for now

- .github/workflows/integration.yml
- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
- .github/workflows/nightly-verify.yml
- .github/workflows/nightly-website.yml
- .github/workflows/packaging.yml
- .github/workflows/verify.yml
- docker-compose.yml
- Mambaforge is deprecated.
- System `pip` in the runners now requires a scary flag to install packages.  Install our own Python explicitly instead.
Fixes #2257.
> ci: switch mambaforge to miniforge, explicitly install Python

- c/driver/framework/objects.cc
- c/driver/framework/objects.h
- c/driver/postgresql/connection.cc
- c/driver/postgresql/result_helper.h
- c/driver/sqlite/sqlite.cc
- r/adbcpostgresql/configure
This PR migrates the PostgreSQL driver to use the same `GetObjectsHelper` as the SQLite driver (the one provided by the framework). This involved a few updates to the helper (notably: ensure the filter is passed to the `LoadXXX()` methods), and an update to the result helper to make it easier to store iteration state along a result as a member of the helper.
> refactor(c/driver/postgresql): Use GetObjectsHelper from framework to build objects

- r/adbcbigquery/README.Rmd
- r/adbcbigquery/README.md
- r/adbcflightsql/README.Rmd
- r/adbcflightsql/README.md
- r/adbcsnowflake/README.Rmd
- r/adbcsnowflake/README.md
Close #1647
In the short term, CRAN is unlikely to accept Go-based packages, so for now we can recommend installation from R-multiverse.
We can also use the ASF repo of R-universe (<https://apache.r-universe.dev/>), but R-multiverse is more reliable because it is tied to the latest release with certainty.
Note that `adbcbigquery` has not been added to R-multiverse yet (r-multiverse/contributions#213 will be merged after ADBC 15 release)
> docs(r/adbcbigquery,r/adbcflightsql,r/adbcsnowflake): recommend to install from R-multiverse

- c/validation/adbc_validation.h
- c/validation/adbc_validation_statement.cc
Noticed this when compiled via meson:
```base
$ meson setup builddir -Dtests=true -Dsqlite=true
$ meson compile -C builddir
...
/usr/bin/ld: driver/sqlite/adbc-driver-sqlite-test.p/sqlite_test.cc.o: in function `SqliteStatementTest_SqlIngestUInt64_Test::TestBody()':
sqlite_test.cc:(.text+0x802): undefined reference to `void adbc_validation::StatementTest::TestSqlIngestType<unsigned long>(ArrowType, std::vector<std::optional<unsigned long>, std::allocator<std::optional<unsigned long> > > const&, bool)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
I'm not sure why the CMake config is OK with this, likely some magic I don't understand. However, it makes sense to me that the linker is complaining; the adbc_validation.h header declares this template …
> build(c): Fix linker error with SQLite tests

- c/driver/framework/base_driver.h
- c/driver_manager/adbc_driver_manager.cc
> fix(c/driver_manager): More robust error reporting for errors that occur before AdbcDatabaseInit()

- csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs
- csharp/test/Drivers/Apache/Spark/DriverTests.cs
The attempt to use “look-ahead” buffering in the HiveServer2Reader is not supported by the Thrift library. The issue is that the Thrift library uses a shared buffer on the Client/Protocol/Transport object -so interleaving Fetch and ExecuteStatement will fail because the buffer will get closed unexpectedly.
> fix(csharp/src/Drivers/Apache): remove interleaved async look-ahead code

- csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs
- csharp/src/Drivers/Apache/Impala/ImpalaConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkDatabricksConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/test/Apache.Arrow.Adbc.Tests/ClientTests.cs
- csharp/test/Apache.Arrow.Adbc.Tests/DriverTests.cs
- csharp/test/Apache.Arrow.Adbc.Tests/TestBase.cs
- csharp/test/Apache.Arrow.Adbc.Tests/TestEnvironment.cs
- csharp/test/Drivers/Apache/Impala/ImpalaTestEnvironment.cs
- csharp/test/Drivers/Apache/Spark/BinaryBooleanValueTests.cs
- csharp/test/Drivers/Apache/Spark/ClientTests.cs
- csharp/test/Drivers/Apache/Spark/DriverTests.cs
- csharp/test/Drivers/Apache/Spark/SparkTestEnvironment.cs
* Fixes issue of returning an empty RecordBatch when an empty response is return from the server.
* Adds test to check for empty result in both the AdbcStatement and AdbcDataReader
* Add Client tests for the Spark driver.
closes #2233
> fix(csharp/src/Drivers/Apache): correctly handle empty response and add Client tests

- csharp/src/Drivers/Apache/Spark/SparkDatabricksConnection.cs
- csharp/test/Drivers/Apache/Spark/ClientTests.cs
- csharp/test/Drivers/Apache/Spark/DriverTests.cs
- csharp/test/Drivers/Apache/Spark/Resources/SparkData-Databricks.sql
- csharp/test/Drivers/Apache/Spark/Resources/SparkData.sql
Provides an interim work-around for the concurrency issue identified in #2280.
* Removes the SQL `DELETE` statements from the SQL table scripts.
* Uses the XUnit.Collection to serialize the execution of ClientTests and DriverTests.
* Fixes the missing application of `HttpRequestTimeout` due to an incomplete implementation of the `ValidateOptions` in `SparkDatabricksConnection`.
* Improve table create table syntax to `CREATE OR REPLACE TABLE` to reduce probably of inconsistent state.
Note: this is not the final solution. A more robust isolation of table creation needs to done to isolate concurrency.
> fix(csharp/src/Drivers/Apache): fix to workaround concurrency issue

- go/adbc/driver/internal/driverbase/connection.go
- go/adbc/driver/internal/driverbase/driver_test.go
- go/adbc/driver/snowflake/driver_test.go
Fixes #2278
The current `UnmarshalJSON` function for `requiredList` ended up unmarshalling into a copy of the underlying slice rather than using the actual slice, so the data wasn't being propagated appropriately. This fixes the `UnmarshalJSON` function to handle the scenario appropriately.
> fix(go/adbc/driver/internal/driverbase): proper unmarshalling for ConstraintColumnNames

- csharp/test/Drivers/Apache/Spark/SparkTestEnvironment.cs
Fixes the handling of `float` data type when running the integration tests on Databricks Spark
closes #2281
> fix(csharp/src/Drivers/Apache): fix float data type handling for tests on Databricks Spark

- csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2SchemaParser.cs
- csharp/src/Drivers/Apache/Spark/README.md
- csharp/test/Drivers/Apache/Spark/NumericValueTests.cs
- csharp/test/Drivers/Apache/Spark/Resources/SparkData.sql
- csharp/test/Drivers/Apache/Spark/SparkTestEnvironment.cs
If Apache Spark server indicates the host data type is FLOAT, and the `scalar` data type conversion is selected, convert Double array to Float array.
* Performs conversion as prescribed
* Updates tests
* Corrects SQL statement for older versions of Spark server.
> feat(csharp/src/Drivers/Apache): convert Double to Float for Apache Spark on scalar conversion

- rust/drivers/datafusion/src/lib.rs
- rust/drivers/datafusion/tests/test_datafusion.rs
- swaps todos from Optionable impls to partial support: none for Database, CurrentCatalog and CurrentSchema for Connection and IngestTableTarget for Statement.
- adds support for binding a single batch and executing a bulk insert on it. I used `RefCell` to pass bound record batch from `bind` to an `execute_update` method.
> feat(rust/drivers/datafusion): add support for bulk ingest

- c/driver/postgresql/connection.cc
- c/driver/postgresql/connection.h
- c/driver/postgresql/copy/postgres_copy_reader_test.cc
- c/driver/postgresql/copy/reader.h
- c/driver/postgresql/database.cc
- c/driver/postgresql/database.h
- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/postgres_type_test.cc
- c/driver/postgresql/result_helper.h
- c/driver/postgresql/result_reader.cc
- c/driver/postgresql/result_reader.h
- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- docs/source/driver/postgresql.rst
Just following up on #1563 to see if the missing `typarray` column is the only issue. To get the details right might be a large project, but we might be able to support a basic connection without too much effort. Paramter binding and non-COPY result fetching seem to work...the default query fetch method (COPY) is not supported, `connection_get_info()` fails, and at a glance, `connection_get_objects()` might be returning incorrect results (and fails at the column depth).
``` r
db <- adbc_database_init(
adbcpostgresql::adbcpostgresql(),
uri = Sys.getenv("ADBC_REDSHIFT_TEST_URI"),
adbc.postgresql.load_array_types = FALSE
)
con <- db |> 
adbc_connection_init()
stmt <- con |> 
adbc_statement_init(adbc.postgresql.use_copy = FALSE)
stream <- …
```
> feat(c/driver/postgresql): Enable basic connect/query workflow for Redshift

- .env
- .github/workflows/java.yml
- .github/workflows/packaging.yml
- ci/scripts/java_build.sh
- dev/release/verify-release-candidate.sh
- docs/source/development/releasing.rst
- java/driver/flight-sql/pom.xml
- java/driver/flight-sql/src/test/java/org/apache/arrow/adbc/driver/flightsql/GetObjectsTests.java
- java/driver/flight-sql/src/test/java/org/apache/arrow/adbc/driver/flightsql/MutualTlsTest.java
- java/driver/flight-sql/src/test/java/org/apache/arrow/adbc/driver/flightsql/TlsTest.java
- java/driver/jdbc-validation-mssqlserver/pom.xml
- java/pom.xml
Update arrow dependency from 15.0.0 to 18.0.0.
As Apache Arrow now requires Java 11, Apache Arrow ADBC also now requires Java 11.
Update Apache Parent pom to version 33 and take advantage of Java 9+ support.
Clean up pom.xml files to remove duplicate or conflicting plugin version definition and/or configuration
Update FlightSQL tests to use the FlightSQL Junit 5 extension.
Update build and dev scripts, and documentation
> chore(java): bump arrow to 18.0.0

- .github/workflows/verify.yml
Otherwise GitHub rate-limits us.
Fixes #2307.
> ci: make token available when verifying binaries

- .github/workflows/packaging.yml
> ci: include BigQuery wheels in packaging artifacts

- c/cmake_modules/AdbcDefines.cmake
- c/driver/framework/base_driver.h
- c/driver/framework/utility.cc
- c/driver/postgresql/connection.cc
- c/driver/postgresql/database.cc
- c/driver/postgresql/result_helper.cc
- c/driver/postgresql/result_reader.cc
- c/driver/postgresql/statement.cc
- c/driver/sqlite/sqlite.cc
- c/driver/sqlite/statement_reader.c
- go/adbc/drivermgr/adbc_driver_manager.cc
Noted in https://github.com/conda-forge/arrow-adbc-split-feedstock/pull/17
> chore(c): fix some warnings reported by MSVC

- .github/workflows/packaging.yml
This instance was merged a day after everything else was bumped and as the dependabot PR was closed it's ignoring it.
> chore: bump last instance of `actions/*-artifact` to v4

- ci/scripts/csharp_pack.ps1
- ci/scripts/csharp_pack.sh
Modifying the csharp_pack.ps1 script to allow for packing without building.
This unlocks scenarios where we can build and sign the binaries, then pack without having them be overwritten by an implicit build.
Updated the csharp_pack.sh script for parity.
> ci(ci/scripts): Introduce the option to pack csharp without building

- rust/driver/snowflake/README.md
- rust/driver/snowflake/src/builder.rs
- rust/driver/snowflake/src/connection/builder.rs
- rust/driver/snowflake/src/database/builder.rs
- rust/driver/snowflake/src/driver/builder.rs
- rust/driver/snowflake/src/duration.rs
- rust/driver/snowflake/tests/driver.rs
As suggested in https://github.com/apache/arrow-adbc/pull/2207#discussion_r1853206066 the `Builder::from_env` methods should return a result when parsing fails.
> feat(rust/driver/snowflake)!: return a `Result` from `Builder::from_env` when parsing fails

- dev/release/post-08-rust.sh
This reverts commit 041f72ded9b594efa950454a6284385319ef3f9e.
We want to hold off publishing the `adbc_snowflake` crate to crates.io for now.
> chore(dev/release): hold off publishing `adbc_snowflake` crate for now

- .env
- .github/workflows/packaging.yml
- ci/docker/python-wheel-manylinux-relocate.dockerfile
- ci/scripts/python_util.sh
- ci/scripts/python_wheel_unix_build.sh
- ci/scripts/python_wheel_unix_relocate.sh
- docker-compose.yml
- Build binaries separately using an older glibc.
- Use a separate image with a new docker to run cibuildwheel.
Fixes #2350.
> fix(ci): ensure wheels are built with older manylinux

- csharp/src/Client/AdbcCommand.cs
- csharp/src/Client/AdbcConnection.cs
- csharp/src/Client/ConnectionStringParser.cs
- csharp/src/Client/readme.md
- csharp/test/Apache.Arrow.Adbc.Tests/Client/ClientTests.cs
Follow up to https://github.com/apache/arrow-adbc/pull/2312 to add parsing of the timeout values and other custom properties like StructBehavior and DecimalBehavior from the connection string.
> feat(csharp/src/Client): parse custom properties from connection string

- csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs
Checks the return status when polling for response. 
* Must be in the `FINISHED_STATE`. Other states are invalid after polling.
* Difficult to write tests for this without "abusing" the server to invoke a server error.
> fix(csharp/src/Drivers/Apache): detect sever error when polling for response

- go/adbc/driver/bigquery/connection.go
This PR sets `DefaultProjectID` and `DefaultDatasetID` for new `adbc.Statement` to the corresponding value in the `adbc.Connection`.
> fix(go/adbc/driver/bigquery): set default project and dataset for new statements

- .github/dependabot.yml
Adds a weekly `cargo` update check with dependabot for `/rust/`.
> chore(rust): add dependabot updates

- .github/dependabot.yml
We want to bump these crates together.
> chore(rust): group `arrow` and `datafusion` dependabot updates

- .github/workflows/native-unix.yml
- ci/conda_env_glib.txt
It appears that Ruby 3.4.0 introduces a dependency on stdckdint.h. On Linux this appears fine but on macOS for some reason Ruby is configured to assume that this C23 header is provided by the compiler/standard library (it isn't) and fails. Pin to older Ruby for the time being.
> ci: pin Ruby version

- docs/source/driver/flight_sql.rst
- docs/source/ext/adbc_cookbook.py
- go/adbc/driver/flightsql/example_usage_test.go
> docs: change Flight SQL driver usage to executable example

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
Fix a minor typo,
I think we accidentally forgot to export the `statement_execute_schema` handler from the C# exporter. And mistook StatementGetParameterSchema for it, as they two looked so alike to each other...
so, this should restore it, please kindly approve.
> fix(csharp/src/Apache.Arrow.Adbc/C): export statement_execute_schema correctly

- .github/workflows/rust.yml
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
Setting default shell for Rust CI jobs to `bash -l -eo pipefail {0}`. Without `pipefail` the exit code is the result of the last command (e.g. `popd` as noted here https://github.com/apache/arrow-adbc/pull/2414#issuecomment-2573937068).
> chore(ci): add `-o pipefail` to default `bash` shell for Rust jobs and fix CI job

- rust/Cargo.lock
- rust/driver/datafusion/Cargo.toml
- rust/driver/datafusion/src/lib.rs
- rust/driver/datafusion/tests/test_datafusion.rs
This is #2414 with an additional commit to handle the breaking change from https://github.com/apache/datafusion/pull/13343.
> chore(rust): bump the datafusion group in /rust with 2 updates

- .github/workflows/integration.yml
- c/driver/postgresql/bind_stream.h
- python/adbc_driver_postgresql/tests/test_dbapi.py
> fix(c/driver/postgresql): don't unnecessarily COMMIT

- .github/workflows/csharp.yml
- .github/workflows/dev.yml
- .github/workflows/dev_pr.yml
- .github/workflows/integration.yml
- .github/workflows/java.yml
- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
- .github/workflows/nightly-verify.yml
- .github/workflows/nightly-website.yml
- .github/workflows/packaging.yml
- .github/workflows/verify.yml
- go/adbc/driver/flightsql/flightsql_adbc_test.go
> ci: make sure bash has pipefail

- .github/workflows/nightly-verify.yml
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/validation/adbc_validation_statement.cc
- c/vendor/nanoarrow/nanoarrow.hpp
- ci/docker/cpp-clang-latest.dockerfile
- ci/docker/cpp-gcc-latest.dockerfile
- docker-compose.yml
- Backport nanoarrow patch to satisfy newer Clang
- Add test using GCC 15
- Update tests using sketchy casts to satisfy these compilers
- Refactor the clang/gcc Docker jobs
Fixes #2424.
> test(c): don't use sketchy cast to test backwards compatibility

- csharp/src/Drivers/BigQuery/AssemblyInfo.cs
- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryTableTypes.cs
- csharp/test/Apache.Arrow.Adbc.Tests/Metadata/GetObjectsParser.cs
- csharp/test/Drivers/BigQuery/DriverTests.cs
- removes additional suffix details from data type names. For example, STRUCT<...> is just a STRUCT type, and NUMERIC(n,y) is just NUMERIC to match the ODBC type names.
- adds support for querying additional table types
> fix(csharp/src/Drivers/BigQuery): remove details to have type names match ODBC

- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/result_helper.cc
> fix(c/driver/postgresql): return unknown OIDs as opaque

- rust/Cargo.lock
The version in our lock file is yanked.
> chore(rust): bump `bytes` to `1.9.0`

- rust/Cargo.lock
- rust/core/Cargo.toml
- rust/core/src/schemas.rs
[`LazyLock`](https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html) was stabilized in `1.80`, which is the minimal version in our workspace, so we can drop the `once_cell` dependency:
https://github.com/apache/arrow-adbc/blob/c092bdc807ecf74e7532bc6c5f9b127ea26f4a8d/rust/Cargo.toml#L26
> chore(rust): replace `once_cell::Lazy` with `std::sync::LazyLock`

- rust/core/Cargo.toml
- rust/driver/datafusion/Cargo.toml
- rust/driver/dummy/Cargo.toml
- rust/driver/snowflake/Cargo.toml
> chore(rust): include more metadata fields in Cargo manifests

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/statement.go
- python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py
This lets you identify particular queries in the query history.
Fixes #1934.
> feat(go/adbc/driver/snowflake): add query tag option

- ci/conda_env_python.txt
- python/adbc_driver_postgresql/tests/test_dbapi.py
`datetime.UTC` only exists on Python >= 3.11 (we only run this test on a single Python version so we didn't notice it earlier). Use `datetime.timezone.utc` which should always exist.
> test(python/adbc_driver_postgresql): fix typecheck error on py3.9

- .github/workflows/nightly-verify.yml
- ci/docker/cpp-clang-latest.dockerfile
It appears LLVM's deb repo is slightly borked and has set the clang package to alias unreleased LLVM instead of latest stable. Explicitly install the latest version by checking the API.
Fixes #2497.
> ci: explicitly install latest clang for nightly test

- docs/source/driver/sqlite.rst
- docs/source/python/recipe/sqlite.rst
- docs/source/python/recipe/sqlite_batch_rows.py
- docs/source/python/recipe/sqlite_batch_rows.py.stdout.txt
> docs: add SQLite cookbook example for batch size/inference

- docs/source/driver/jdbc.rst
- docs/source/java/quickstart.rst
> docs: update java quickstart to use the PARAM_URI instead of the legacy PARAM_URL

- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/snowflake_database.go
Instead of creating a separate connection for simple queries like SELECT COUNT and the metadata queries, we'll keep using the single connection to maintain the existing session throughout. This should avoid the problem mentioned in #2128 where a new session cancels the remaining COPY INTO queries. It also simplifies some of the work on metadata queries so that we don't need to explicitly propagate catalog, schema and database names between connections.
Fixes #2517
> fix(go/adbc/driver/snowflake): use one session for connection

- csharp/Apache.Arrow.Adbc.sln
- csharp/Benchmarks/Benchmarks.csproj
- csharp/Benchmarks/Program.cs
- csharp/src/Apache.Arrow.Adbc/Extensions/IArrowArrayExtensions.cs
- csharp/src/Client/AdbcDataReader.cs
- csharp/src/Client/SchemaConverter.cs
- csharp/test/Apache.Arrow.Adbc.Tests/DuckDbFixture.cs
I noticed that the ValueAt helper had compiled into some very inefficient IL, so I decided to improve its performance by replacing with a simpler switch statement. I then realized that in AdbcDataReader, we don't need to do the type check on every row because it's the same underlying Arrow type for the entire column -- so it's faster to get a delegate once and keep using the same delegate for the entire data set. Benchmarking came up with these results when testing through AdbcDataReader.GetValues:
| Method      | Mean    | Error    | StdDev   |
|------------ |--------:|---------:|---------:|
| Original    | 6.263 s | 0.0575 s | 0.0538 s |
| New ValueAt | 5.400 s | 0.0424 s | 0.0397 s |
| Getter      | 4.650 s | 0.0281 s | 0.0249 s |
> feat(csharp/src/Apache.Arrow.Adbc): improved performance of ValueAt helper and AdbcDataReader

- c/driver/sqlite/sqlite.cc
- c/driver/sqlite/sqlite_test.cc
- python/adbc_driver_manager/tests/test_dbapi.py
A recent update to the conda-forge feedstock disabled double-quoted strings, which we were accidentally relying on.
Ref: https://github.com/conda-forge/sqlite-feedstock/commit/302e685b984ea3a36a333a453e75b547007d0f88
Fixes #2554.
> fix(c/driver/sqlite): don't rely on double-quoted strings feature

- .env
- .pre-commit-config.yaml
- c/driver/bigquery/bigquery_test.cc
- c/driver/flightsql/dremio_flightsql_test.cc
- c/driver/flightsql/sqlite_flightsql_test.cc
- c/driver/framework/objects.cc
- c/driver/postgresql/copy/postgres_copy_reader_test.cc
- c/driver/postgresql/copy/postgres_copy_writer_test.cc
- c/driver/postgresql/database.cc
- c/driver/postgresql/error.cc
- c/driver/postgresql/postgres_type_test.cc
- c/driver/postgresql/postgresql_test.cc
- c/driver/postgresql/result_helper.cc
- c/driver/postgresql/statement.cc
- c/driver/snowflake/snowflake_test.cc
- c/driver/sqlite/sqlite.cc
- c/driver/sqlite/sqlite_test.cc
- c/integration/duckdb/duckdb_test.cc
- c/validation/adbc_validation_connection.cc
- c/validation/adbc_validation_statement.cc
- c/validation/adbc_validation_util.cc
- ci/docker/golang-flightsql-sqlite.dockerfile
- go/adbc/go.mod
- python/adbc_driver_manager/adbc_driver_manager/_blocking_impl.cc
- r/adbcdrivermanager/src/driver_test.cc
Go 1.22 is EOL with the release of 1.24.
Various pre-commit hooks have seen major updates. Bump them to the latest versions.
> chore: bump versions of Go, pre-commit hooks

- c/cmake_modules/BuildUtils.cmake
- c/cmake_modules/GoUtils.cmake
- c/driver/bigquery/AdbcDriverBigQueryConfig.cmake.in
- c/driver/bigquery/CMakeLists.txt
- c/driver/bigquery/README.md
- c/driver/flightsql/AdbcDriverFlightSQLConfig.cmake.in
- c/driver/flightsql/CMakeLists.txt
- c/driver/snowflake/AdbcDriverSnowflakeConfig.cmake.in
- c/driver/snowflake/CMakeLists.txt
- ci/linux-packages/debian/libadbc-driver-flightsql-dev.install
- ci/linux-packages/debian/libadbc-driver-snowflake-dev.install
- ci/linux-packages/yum/apache-arrow-adbc.spec.in
> feat(c/driver): add support for CMake packages of Go based drivers

- go/adbc/driver/internal/shared_utils.go
- go/adbc/driver/snowflake/connection.go
- go/adbc/driver/snowflake/driver_test.go
Fixes #2544 by eliminating the null pointer dereference for unknown column types
> fix(go/adbc/driver/snowflake): fix GetObjects for VECTOR cols

- dev/release/04-java-upload.sh
- docs/source/development/releasing.rst
The script was removed from apache/arrow after Java as moved to apache/arrow-java.  The new script is not as easily reused so inline it here instead.
Fixes #2451.
> chore(dev/release): update the Java release upload process

- csharp/src/Drivers/Apache/Hive2/HiveServer2AuthType.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2HttpConnection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2TransportType.cs
- csharp/src/Drivers/Apache/Impala/ImpalaAuthType.cs
- csharp/src/Drivers/Apache/Impala/ImpalaHttpConnection.cs
- csharp/src/Drivers/Apache/Impala/ImpalaServerType.cs
- csharp/src/Drivers/Apache/Impala/ImpalaStandardConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkAuthType.cs
- csharp/src/Drivers/Apache/Spark/SparkConnectionFactory.cs
- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkServerType.cs
- csharp/src/Drivers/Apache/Spark/SparkStandardConnection.cs
Improves idiomatic handling of authentication and server type enumerations
Fixes #2569
> fix(csharp/src/Drivers/Apache): Improve handling of authentication and server type enumeration parsing

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
- csharp/test/Apache.Arrow.Adbc.Tests/ImportedDuckDbTests.cs
An override was missing from `ImportedAdbcConnection`.
> fix(csharp/src): Add missing override to ImportedAdbcConnection

- ci/scripts/glib_build.sh
Fixes #2584
If we want to enable Vala support in ADBC GLib, we require Apache Arrow GLib with Vala support.
> chore(glib): improve Vala API availability check

- .github/workflows/rust.yml
- dev/release/utils-prepare.sh
- rust/Cargo.lock
The lock file needs to be updated after bumping the crate versions. This also adds `--locked` to CI to make sure the checked-in lock file is updated.
> chore(rust): update lock file

- docs/source/python/recipe/postgresql_execute_nocopy.py
- docs/source/python/recipe/postgresql_execute_nocopy.py.stdout.txt
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_postgresql/adbc_driver_postgresql/__init__.py
- Add a keyword-only argument to set statement options directly when creating a cursor, which makes it a little clearer what's going on.
- Allow using True and False directly as option values (they will get converted to ENABLED and DISABLED, respectively).
- Add the `use_copy` option to the PostgreSQL options enum.
- Add an example of this with PostgreSQL.
Fixes #2093.
Fixes #2146.
> feat(python/adbc_driver_manager): add cursor() arg to set options

- python/adbc_driver_bigquery/pyproject.toml
- python/adbc_driver_flightsql/pyproject.toml
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgresql/pyproject.toml
- python/adbc_driver_snowflake/pyproject.toml
- python/adbc_driver_sqlite/pyproject.toml
This released in November 2023 and included a CVE fix.  While I don't expect us to actually require anything new, it's best to avoid older versions with the CVE.  (The previous bound, 8.0.0, is from May 2022 so we're advancing ~18 months.)
Fixes #1272.
> chore(python): bump minimum PyArrow to 14.0.1

- .github/workflows/csharp.yml
- ci/scripts/csharp_test.sh
- csharp/Directory.Build.props
- dev/release/verify-release-candidate.sh
Fix MacOS builds for C# by moving to newer SourceLink
Closes #2568.
> fix(ci): fix MacOS builds for C#

- .github/workflows/dev_adbc.yml
- .github/workflows/integration.yml
- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
- .github/workflows/nightly-verify.yml
- .github/workflows/packaging.yml
- .github/workflows/r-check.yml
- .github/workflows/r-extended.yml
- .github/workflows/verify.yml
- .pre-commit-config.yaml
- ci/scripts/run_pre_commit_pin.py
Apache wants us to limit concurrency, ensure actions are pinned, and ensure we aren't exporting GITHUB_TOKEN etc. (https://infra.apache.org/github-actions-policy.html) It's not clear to me if our use of GITHUB_TOKEN in dev_pr.yaml falls under that.
Fixes #2575.
> ci: ensure GitHub Actions and pre-commit hooks are pinned

- go/adbc/driver/bigquery/driver_test.go
- go/adbc/driver/bigquery/record_reader.go
- go/adbc/driver/bigquery/record_reader_test.go
This PR avoids creating arrow iterator in case the resulting schema is empty.  The issue was that `IsAccelerated` (in `google-cloud-go/bigquery/storage_iterator.go`)  would return `false` in case there is no result (e.g., one is running `drop schema`) when creating `ArrowIterator`. Now, before we try to get `ArrowIterator`, we check if schema is empty.
The PR also adds tests following (i.e., trying to follow) the existing formats. 
Closes: https://github.com/apache/arrow-adbc/issues/2173
> fix(go/adbc/driver/bigquery): Avoid creating arrow iterator when schema is empty

- c/driver/postgresql/statement.cc
- c/driver/postgresql/statement.h
- c/validation/adbc_validation.h
- c/validation/adbc_validation_statement.cc
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
The driver does not prevent you from closing a statement when there is still an open result set.  Then closing the result set would crash.  Avoid this by having the result set keep a weak pointer to the actual state.
Fixes #2629.
> fix(c/driver/postgresql): avoid crash if closing invalidated result

- csharp/src/Drivers/Apache/Spark/CloudFetch/SparkCloudFetchReader.cs
- csharp/src/Drivers/Apache/Spark/Lz4Utilities.cs
- csharp/src/Drivers/Apache/Spark/SparkDatabricksConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkDatabricksReader.cs
- csharp/src/Drivers/Apache/Spark/SparkStatement.cs
- csharp/src/Drivers/Apache/Thrift/ChunkStream.cs
- csharp/test/Drivers/Apache/Spark/StatementTests.cs
1. Create a new file [Lz4Utilities.cs](https://github.com/apache/arrow-adbc/compare/main...eric-wang-1990:arrow-adbc:add_lz4_to_arrowbatch#diff-7275463b6b9fcc3cf3b954580e3ded8b0b7237a90e0f4aea33eb11e613f3db39) to abstract common Lz4 decompress util functions for both cloud fetch and arrow batch.
2. Add support for decompress arrow batch with Lz4
3. Rename adbc.spark.cloudfetch.lz4.enabled to adbc.spark.lz4Compression.enabled since it is not specific to cloudfetch
4. Add test to test both cloudFetch and arrowBatch in StatementTests.
> feat(csharp/src/Drivers/Apache/Spark): Add Lz4 compression support to arrow batch reader

- go/adbc/sqldriver/driver.go
- go/adbc/sqldriver/driver_internals_test.go
Implements reading from union types and adds a unit test. All tests pass, except those with C shared object dependencies. I did not build the code outside go/adbc - let me know if needed for this PR.
In addition to the added unit test, I tested the scenario from the issue with DuckDB.
Closes #2636
> feat(go/adbc/sqldriver): read from union types

- go/adbc/driver/snowflake/driver.go
It turns out gosnowflake also exposes a log level control; set this to "warn".
I also filed https://github.com/snowflakedb/gosnowflake/pull/1332. We need the fix to be upstream since ultimately the log message is triggered by constructing a global, so we're powerless to suppress it. It was ultimately fixed by https://github.com/snowflakedb/gosnowflake/pull/1327.
> fix(go/adbc/driver/snowflake): try to suppress stray logs

- rust/core/Cargo.toml
Currently, `driver_manager` module is not shown on [docs.rs](https://docs.rs/adbc_core/0.17.0/adbc_core/index.html). This pull request adds `[package.metadata.docs.rs]` option to enable the feature.
If this is just as intended (e.g., you don't want to expose a module that is not matured yet), please ignore!
> docs(rust): show driver_manager features on docs.rs

- c/driver/postgresql/connection.cc
- c/driver/postgresql/postgresql_test.cc
- c/validation/adbc_validation_statement.cc
- python/adbc_driver_postgresql/adbc_driver_postgresql/__init__.py
- python/adbc_driver_postgresql/tests/test_dbapi.py
This avoids spamming the server-side log with "WARNING: there is no transaction in progress" messages.
Also, fix ConnectionRollback not properly starting a new transaction afterwards.
Fixes #2673.
> feat(c/driver/postgresql): avoid commit/rollback when idle

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksReader.cs
This PR https://github.com/apache/arrow-adbc/commit/9ba6bdb8bd42e35237dadfae758419846e6c442c introduce a regression for DatabricksReader.
Fix it, also remove the unneeded constructor to prevent any misuse in the future.
> fix(csharp/src/Drivers/Databricks): Fix Lz4 compression logic for DatabricksReader

- python/adbc_driver_postgresql/adbc_driver_postgresql/__init__.py
- python/adbc_driver_postgresql/adbc_driver_postgresql/dbapi.py
- python/adbc_driver_postgresql/tests/test_dbapi.py
Closes #2696
But I've encountered some issues when writing a test for the change:
- there are currently no supported `db_kwargs` beyond `driver` and `uri` - which are set explicitly
- regarding `conn_kwargs` - only two appear to be supported:
- `adbc.connection.autocommit` - which is [configurable explicitly](https://github.com/apache/arrow-adbc/blob/a187ead78afebe85c75b466a06ad6e01ae4ac8c6/python/adbc_driver_manager/adbc_driver_manager/dbapi.py#L305)
- `adbc.connection.db_schema` - which seems to cause a SEGFAULT when I add a test that tries to set this using `conn_kwargs`
The SEGFAULT happens only when I'm trying to set this specific option, when I change the key I get the expected `adbc_driver_manager.NotSupportedError: NOT_IMPLEMENTED: [libpq] Unknown option …
> fix(python/adbc_driver_postgresql): handle kwargs in dbapi connect

- .github/workflows/r-basic.yml
- .github/workflows/r-check.yml
- .github/workflows/r-extended.yml
- .github/workflows/r-standard.yml
Closes #2707.
This is more likely to be a change in Adbc somewhere since it's showing up in all versions. Did we add anything recently that logged anything to stderr or called assert or abort?
In the event it can't be avoided (it often can't), we can update the warning fail level for go-based drivers since we don't distribute them on CRAN.
> chore(r): Update CI setup to silence warnings for Go-based drivers

- go/adbc/pkg/Makefile
- go/adbc/pkg/_tmpl/driver.go.tmpl
This makes the templates consistent with the generated (then manually edited code).
> fix(go): Use arrow-go in templates instead of arrow/go

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryParameters.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/src/Drivers/BigQuery/readme.md
- csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs
- csharp/test/Drivers/BigQuery/BigQueryTestingUtils.cs
- csharp/test/Drivers/BigQuery/DriverTests.cs
- csharp/test/Drivers/BigQuery/readme.md
Support evaluation kind and statement type setting for GBQ driver, and improve code at BigQueryStatement.cs.
> feat(csharp/src/Drivers/BigQuery): support evaluation kind and statement type setting

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksDatabase.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/test/Drivers/Databricks/ServerSidePropertyE2ETest.cs
We want to be able to pass server side properties through the driver, e.g. use_cached_result.
In ODBC driver, the behavior is like this:
- If ApplySSPWithQueries = 1, set server side properties using "set x=y" commands during open session
- If ApplySSPWithQueries = 0, set server side properties using thrift configuration
This PR adds support in the ADBC driver for this
Tested E2E by setting 
```
{ "adbc.databricks.apply_ssp_with_queries", "false" },
{ "adbc.databricks.SSP_use_cached_result", "false"},
```
which disabled result cache for the executed query.
When using `{ "adbc.databricks.apply_ssp_with_queries", "true" }`, I see a set query in the query history
> feat(csharp/src/Drivers/Databricks): Support server side property passthrough

- csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2HttpConnection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- csharp/src/Drivers/Apache/Hive2/SqlTypeNameParser.cs
- csharp/src/Drivers/Apache/Impala/ImpalaConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkConnection.cs
- csharp/test/Drivers/Databricks/StatementTests.cs
This PR enhances the C# ADBC driver's `GetColumns` functionality by adding a new `BASE_TYPE_NAME` column to the result set. This column provides the base type name without parameters or decorations, making it easier for clients to identify the fundamental data type regardless of its parameterization.
- Added a new `BASE_TYPE_NAME` column to the `GetColumns` result schema
- Enhanced the `HiveServer2Statement` class to process and populate the `BASE_TYPE_NAME` column
- Changed visibility modifiers for several methods from `protected` to `public` or `internal` to enable the enhancement
- Added support for the `VARIANT` SQL type in the `SqlTypeNameParser`
- Created comprehensive unit tests to verify the functionality with various data types
The implementation:
1. Intercepts `GetColumns` query …
> feat(csharp/src/Drivers/Apache): enhance GetColumns with BASE_TYPE_NAME column

- dev/release/verify-release-candidate.sh
- Bump the Go version to keep up
- Explicitly allow using .NET 9 to run tests (though the build targets .NET 8)
> chore: fix nightly verification run

- .github/dependabot.yml
Until we fix https://github.com/apache/arrow-adbc/pull/2525, this merges the `arrow` and `datafusion` dependabot update PRs.
> chore: merge `arrow` and `datafusion` update groups

- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksException.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/RetryHttpHandler.cs
- csharp/test/Drivers/Databricks/DatabricksConnectionTest.cs
- csharp/test/Drivers/Databricks/RetryHttpHandlerTest.cs
This PR implements retry-after behavior for the Spark ADBC driver when receiving 503 responses with Retry-After headers. This is particularly useful for Databricks clusters that may return 503 responses when a cluster is starting up or experiencing temporary unavailability.
- Added new configuration parameters:
- `adbc.spark.temporarily_unavailable_retry` (default: 1 - enabled)
- `adbc.spark.temporarily_unavailable_retry_timeout` (default: 900 seconds)
- Created a `RetryHttpHandler` class that wraps the existing `HttpClientHandler` to handle 503 responses
- Modified `SparkHttpConnection` to use the new retry handler
- Added comprehensive unit tests for the retry behavior
When a 503 response with a Retry-After header is received:
1. The handler will wait for the number of seconds specified …
> feat(csharp): Add retry-after behavior for 503 responses in Spark ADBC driver

- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkParameters.cs
- csharp/test/Drivers/Apache/Spark/SparkHttpConnectionUserAgentTest.cs
Enables user agent entry to be passed via SparkParameters, such as "user_agent_entry = PowerBi".
Also adds Thrift version to user agent header
Verified in Databricks HTTP Logs for the user agent:
ADBCSparkDriver/1.0.0 Thrift/0.21.0 PowerBI
> feat(csharp/src/Drivers/Apache/Spark): add user agent entry + thrift version for spark http connections

- c/driver_manager/meson.build
Not sure how this was working before, but on main I get the following issues without this:
```
adbc_driver_manager.cc:(.text.AdbcLoadDriver+0xbe): undefined reference to `dlopen'
/home/willayd/miniforge3/envs/pandas-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: adbc_driver_manager.cc:(.text.AdbcLoadDriver+0xf8): undefined reference to `dlsym'
/home/willayd/miniforge3/envs/pandas-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: adbc_driver_manager.cc:(.text.AdbcLoadDriver+0x33e): undefined reference to `dlsym'
/home/willayd/miniforge3/envs/pandas-dev/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: adbc_driver_manager.cc:(.text.AdbcLoadDriver+0x43b): undefined …
```
> fix(c): Add libdl as dependency of driver manager in Meson

- c/driver/bigquery/meson.build
- c/driver/common/meson.build
- c/driver/flightsql/meson.build
- c/driver/postgresql/meson.build
- c/driver/snowflake/meson.build
- c/driver/sqlite/meson.build
The gtest_main_dep and gmock_dep dependencies are set to `disabler()` when the test option is not enabled in the top level configuration. Therefore, all of these subsequent `if get_option('tests')` checks are redundant; if not set, the disabler() will naturally take care of disabling the dependent target for you
> build(c): Remove unnecessary test branching from Meson configuration

- go/adbc/driver/snowflake/driver.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/snowflake_database.go
I had to move the initialization of the `defaultAppName` to the `databaseImpl` instance to be able to use it when setting options post initialization.
Fixes #2727
> fix(go/adbc/driver/snowflake): implement ability to set database options after initialization

- .github/workflows/nightly-verify.yml
- ci/scripts/verify_ubuntu.sh
- compose.yaml
- dev/release/verify-release-candidate.sh
- go/adbc/driver/flightsql/flightsql_adbc_server_test.go
We've only really tested Conda so far.  Validate non-Conda builds too.
This only tests Ubuntu/APT but eventually we should also test Debian/APT, macOS/Homebrew, Fedora/RPM, and AlmaLinux/RPM.
> ci: verify source using OS-installed dependencies

- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloadManager.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloader.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchMemoryBufferManager.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchReader.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchResultFetcher.cs
- csharp/src/Drivers/Databricks/CloudFetch/DownloadResult.cs
- csharp/src/Drivers/Databricks/CloudFetch/EndOfResultsGuard.cs
- csharp/src/Drivers/Databricks/CloudFetch/ICloudFetchInterfaces.cs
- csharp/src/Drivers/Databricks/CloudFetch/IHiveServer2Statement.cs
- csharp/src/Drivers/Databricks/CloudFetch/cloudfetch-pipeline-design.md
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/DatabricksStatement.cs
- csharp/test/Drivers/Databricks/CloudFetch/CloudFetchDownloaderTest.cs
- csharp/test/Drivers/Databricks/CloudFetch/CloudFetchResultFetcherTest.cs
This PR enhances the CloudFetch feature in the Spark ADBC driver by implementing prefetch functionality, which improves performance by fetching multiple batches of results ahead of time.
- **Initial Prefetch**: Added code to perform an initial prefetch of multiple batches when the fetcher starts, ensuring data is available immediately when needed.
- **State Management**: Added tracking for current batch offset and size, with proper state reset when starting the fetcher.
- Added new methods to `ICloudFetchResultFetcher` interface:
- Created `ITestableHiveServer2Statement` interface to facilitate testing
- Updated tests to account for prefetch behavior
- Ensured all tests pass with the new prefetch functionality
- **Improved Performance**: By prefetching multiple batches, data is available …
> feat(csharp/src/Drivers/Apache): Add prefetch functionality to CloudFetch in Spark ADBC driver

- .github/workflows/native-unix.yml
Per comment https://github.com/apache/arrow-adbc/pull/2546#issuecomment-2685799436 this might help fix the flaky CI failures with meson + ASAN
> fix(ci): Skip flaky ASAN failures in Meson

- dev/release/.env.example
- dev/release/06-binary-verify.sh
- dev/release/post-09-announce.sh
- dev/release/verify-apt.sh
- dev/release/verify-yum.sh
arrow-apt-source and arrow-release changed to use packages.apache.org from apache.jfrog.io in https://github.com/apache/arrow/pull/46108 . (Note that packages.apache.org is an alias of apache.jfrog.io.)
We need to do the same change to pass CI.
Fixes #2757.
> fix(dev/release): use packages.apache.org instead of apache.jfrog.io

- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloader.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchReader.cs
- csharp/test/Drivers/Databricks/CloudFetchE2ETest.cs
This PR fixes an issue where PowerBI would hang when reading CloudFetch results and significantly improves the logging capabilities in the CloudFetch downloader component.
1. The CloudFetchReader was not properly disposing of the download manager after completing downloads, causing resource leaks that led to PowerBI hanging.
2. The CloudFetchDownloader was using Debug.WriteLine for logging, which is inadequate for production scenarios and doesn't provide sufficient diagnostic information.
- Fixed resource management in CloudFetchReader by properly disposing the download manager after all files are processed
- Replaced Debug.WriteLine calls with more comprehensive Trace logging
- Added detailed performance metrics and diagnostics:
- Download start/completion timestamps
- File sizes and …
> feat(csharp): fix powerbi hang when reading cloudfetch result in Databricks driver

- glib/adbc-arrow-glib/meson.build
- glib/adbc-glib/meson.build
- glib/meson.build
AlmaLinux 9 RPM build environment disables PIE by default by `LDFLAGS="-specs=/usr/lib/rpm/redhat/redhat-hardened-ld"`. If PIE is disabled, `g-ir-scanner` is failed:
/usr/bin/ld:
/build/rpmbuild/BUILD/apache-arrow-adbc-18/glib/build/tmp-introspect4ug84fdq/ADBC-1.0.o:
relocation R_X86_64_32 against `.rodata' can not be used when
making a PIE object; recompile with -fPIE
Fixes #2574.
> fix(glib): use -fPIE explicitly for g-ir-scanner

- docs/source/faq.rst
This PR is a bit of a check on my understanding. There are a few changes here:
1. Changed first sentence to help draw the reader in a bit better.
2. Changes the language "a set of abstract APIs" around. Is it more accurate to say there's one abstract API and that there are interface definitions in a few languages, most recently including Rust?
3. Remove the "For example..." as it felt out of place and slows the reader down from getting to bullet point 2.
4. Instead of referencing an easily out of date list of implementations, just link to the driver status page.
> docs: rework "What exactly is ADBC?" in FAQ

- csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs
Currently, calling GetCrossReference with just ForeignCatalogName, ForeignSchemaName, and ForeignTableName parameters fails because these parameters aren't properly set on the Thrift request. 
This PR fixes the typo
Tested E2E locally and it works
```
statement.SqlQuery = "getcrossreference";
statement.SetOption(ApacheParameters.IsMetadataCommand, "true");
statement.SetOption(ApacheParameters.ForeignCatalogName, "powerbi");
statement.SetOption(ApacheParameters.ForeignSchemaName, "default");
statement.SetOption(ApacheParameters.ForeignTableName, "nyc_taxi_tripdata");
```
> fix(csharp/src/Drivers/Apache): Fix setting foreign schema/table in GetCrossReference

- r/adbcsnowflake/configure
Closes #2767 
It seems like the RTools shell identifies itself as `MSYS_NT...` whereas the git shell identifies itself as `MINGW64_NT...`. It looks like r-universe configures using the git shell? We can support both!
> fix(r/adbcsnowflake): Fix configuration of adbcsnowflake when configure is run from a git shell

- rust/core/src/driver_manager.rs
- rust/core/src/lib.rs
- rust/core/tests/common/mod.rs
- rust/core/tests/driver_manager_sqlite.rs
- rust/driver/datafusion/README.md
- rust/driver/datafusion/src/lib.rs
- rust/driver/datafusion/tests/test_datafusion.rs
- rust/driver/dummy/src/lib.rs
- rust/driver/dummy/tests/driver_exporter_dummy.rs
- rust/driver/snowflake/src/connection/builder.rs
- rust/driver/snowflake/src/database.rs
- rust/driver/snowflake/tests/driver.rs
Since the removal of the global driver lock, there is no risk of deadlocks between the locks on the driver and on the database objects.
IIUC, this was why member functions on the database struct took a mutable `self` parameter:
```rust
/// Initialize the given database using the loaded driver.
///
/// This uses `&mut self` to prevent a deadlock.
fn database_init(
&mut self,
mut database: ffi::FFI_AdbcDatabase,
) -> Result<ffi::FFI_AdbcDatabase> {
```
Requiring `&mut self` is overkill and requires another layer of locking at the application side if multiple threads share a database instance (as they should for connection pooling).
This doesn't mean we are passing a forged mutable pointer to the driver via the FFI, the locking on the inner database ensures exclusive access to the …
> fix(rust)!: Let immutable drivers create connections

- docs/source/python/recipe/flight_sql.rst
The Go Arrow implementation moved out of the mono repo to apache/arrow-go and this command should be updated to match. The current command technically still works because `arrow/go` wasn't pulled from gopkgs but I think using the new `arrow-go` repo is better. I've tested the go install command still works.
> fix(docs): update go install command in flight sql recipe

- csharp/src/Drivers/Databricks/Auth/OAuthClientCredentialsProvider.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/readme.md
- csharp/test/Drivers/Databricks/Auth/OAuthClientCredentialsProviderTests.cs
- csharp/test/Drivers/Databricks/DatabricksTestConfiguration.cs
- csharp/test/Drivers/Databricks/DatabricksTestEnvironment.cs
Makes auth-scope configurable for client-credentials.
Added a test; verified that it works.
> feat(csharp/src/Drivers/Databricks): Allow configurable auth scope for client-credentials flow

- csharp/src/Drivers/Apache/Hive2/HiveServer2HttpConnection.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2ProxyConfigurator.cs
- csharp/src/Drivers/Apache/Hive2/HiveServer2TlsImpl.cs
- csharp/src/Drivers/Apache/Hive2/README.md
- csharp/src/Drivers/Apache/Impala/ImpalaHttpConnection.cs
- csharp/src/Drivers/Apache/Spark/SparkHttpConnection.cs
- csharp/src/Drivers/Databricks/Auth/OAuthClientCredentialsProvider.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloadManager.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchReader.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/test/Drivers/Apache/ApacheTestConfiguration.cs
- csharp/test/Drivers/Apache/Hive2/HiveServer2TestEnvironment.cs
- csharp/test/Drivers/Apache/Spark/SparkTestEnvironment.cs
- csharp/test/Drivers/Databricks/Auth/OAuthClientCredentialsProviderTests.cs
- csharp/test/Drivers/Databricks/DatabricksTestEnvironment.cs
Integrates proxy logic with the rest of the Spark-Driver. Also applies to Cloud-fetch and OAuth2 fetch.
Other drivers, like Impala driver, should be compatible with the change. However, it is not tested - so I marked in the README that it's not fully complete
To test, add the following to `DATABRICKS_TEST_CONFIG_FILE` environment variable:
```
"http_options": {
"proxy": {
"use_proxy": "true",
"proxy_host": "...",
"proxy_port":..,
"proxy_auth": "...", // if using basic auth
"proxy_uid": "...",
"proxy_pwd": "..."
},
"tls": { // you may need to enable depending on your proxy, or you need to trust the cert
"enabled": ,
"allow_self_signed": 
}
}
```
And inspect proxy traffic. Verified that it works in driver testing and Powerbi testing
> feat(csharp/src/Drivers/Databricks): Integrate ProxyConfigurations with Drivers

- CONTRIBUTING.md
The build procedure is missing a compiling step, so add `cmake --build .`.
> fix(docs): Add `cmake --build` step

- csharp/test/Drivers/Databricks/StatementTests.cs
Fix the long running status polling test. Previously was small enough to return a direct result (and hence would not start status polling)
> feat(csharp/src/Drivers/Databricks): Fix status polling test

- csharp/src/Drivers/Databricks/BaseDatabricksReader.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloadManager.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchReader.cs
- csharp/src/Drivers/Databricks/DatabricksOperationStatusPoller.cs
- csharp/src/Drivers/Databricks/DatabricksReader.cs
- csharp/test/Drivers/Databricks/StatementTests.cs
Handles shared reading logic (Status Polling logic) for DatabricksReader and CloudFetchReader. Also modifies polling lifecycle to begin during Reader initialization instead of first time `ReadNextRecordBatchAsync` is called
There is still a slight gap when we are not polling for results immediately after query execution completes ([here](https://github.com/apache/arrow-adbc/blob/main/csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs#L121)); can be addressed in a later PR
> feat(csharp/src/Drivers/Databricks): BaseDatabricksReader

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
When the user runs a query that does not return a record set, ie:
```
select * from (SELECT CAST(TRUE as BOOLEAN) as BOOLEANTYPE) as \"_\" where 0 = 1
```
the boolean column was being identified as a string column.
One example of this public issue:
https://www.reddit.com/r/PowerBI/comments/1kqhywe/comment/mttjia5/?context=3&share_id=Wr1PAx4F7KemsyQrCVnDK&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1
> fix(go/adbc/driver/snowflake): Boolean columns return as string types in an empty recordset schema

- rust/core/src/driver_manager.rs
- rust/core/src/ffi/mod.rs
- rust/core/src/lib.rs
docs(rust/core): Update URLs pointing to `adbc.h` in Rust documentation.
Fixes #2882 . Update of URLs pointing to the `adbc.h` in the Rust crate documentation, which moved in #1965 (I think).
> fix(rust/core): URLs pointing to `adbc.h` in docs

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/test/Drivers/Databricks/DatabricksConnectionTest.cs
- csharp/test/Drivers/Databricks/DatabricksTestConfiguration.cs
- csharp/test/Drivers/Databricks/DatabricksTestEnvironment.cs
- csharp/test/Drivers/Databricks/StatementTests.cs
This PR adds support for configuring multiple catalog behavior in the C# Databricks ADBC driver. It introduces a new connection parameter `adbc.databricks.enable_multiple_catalog_support` that allows users to control whether the driver should use multiple catalogs or restrict to a default catalog.
- Add new connection parameter `adbc.databricks.enable_multiple_catalog_support` to control multiple catalog behavior
- Implement parameter parsing with support for boolean values and string values "1"/"0" for compatibility with tools like PowerBI
- Add tests to verify the behavior of metadata queries with different parameter settings
Added unit tests that verify the behavior of metadata queries (GetSchemas, GetTables) with different settings of the `CanUseMultipleCatalogs` parameter. Tests …
> feat(csharp/src/Drivers/Databricks): Add configurable multiple catalog support

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- The Mashup engine will convert all property keys to lower case before opening a connection with the driver
- So, using server side property passthrough with Power BI/PQTest doesn't work, because none of the properties will start with `SSP_`
- This PR will change the prefix to `ssp_` and convert keys to lowercase so that the driver still works with properties set with `SSP_`
- Tested by setting server side property through PQTest
> fix(csharp/src/Drivers/Databricks): Fix parsing of lowercase server side properties

- docs/source/cpp/recipe/quickstart.cc
> docs: fix target name for c/c++ quickstart

- c/driver/postgresql/bind_stream.h
- c/driver/postgresql/connection.cc
- c/driver/postgresql/copy/postgres_copy_test_common.h
- c/driver/postgresql/copy/reader.h
- c/driver/postgresql/copy/writer.h
- c/driver/postgresql/postgres_type.h
- c/driver/postgresql/result_helper.h
- c/include/arrow-adbc/adbc.h
- c/validation/adbc_validation_util.cc
- go/adbc/drivermgr/arrow-adbc/adbc.h
Fixed only comments and messages.
There are no code changes. 
This PR is intended to fix typos in `c/`, but I also fix `go/adbc/drivermgr/arrow-adbc/adbc.h` because this needs to be synced with `adbc.h` in `c/`.
Closes #2923
> chore(c): fix typo

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
Increases the DefaultTemporarilyUnavailableRetryTimeout from 500s to 900s to match ODBC/JDBC driver behavior
> fix(csharp/src/Drivers/Databricks): increase default retry timeout

- go/adbc/adbc.go
- go/adbc/driver/bigquery/statement.go
- go/adbc/driver/flightsql/flightsql_statement.go
- go/adbc/driver/internal/driverbase/connection.go
- go/adbc/driver/internal/driverbase/rotating_file_writer.go
- go/adbc/driver/snowflake/bulk_ingestion.go
- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/statement.go
- go/adbc/ext.go
Fixed only comments.
There are no code changes. 
Closes #2927
> chore(go): fix typo

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksStatement.cs
- csharp/test/Drivers/Databricks/DatabricksConnectionTest.cs
- csharp/test/Drivers/Databricks/StatementTests.cs
This PR makes changes to be consistent with odbc behavior
- Does not attach default schema (from OpenSessionResp) in subsequent queries. This PR changes to be like ODBC here, just to not break anything.
- If catalog == "SPARK", do not set catalog in initial namespace; let server return default catalog
- Do not set catalog in the initial namespace.
- Do not use the OpenSessionResp catalog for subsequent queries (including metadata queries)
| Connection String Catalog/Schema                | EnableMultipleCatalogs=False                                                                 | EnableMultipleCatalogs=True                                                                  |
|--------------------------------------------------|--------------------------------------------------------------- …
> feat(csharp/src/Drivers/Databricks): Multiple catalogs with default database

- python/adbc_driver_manager/adbc_driver_manager/_lib.pyi
- python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi.py
The driver manager was leaking array streams in the case that you executed a query, *did not fetch the result*, then did another operation.  In this case, because the stream was never imported, it would silently leak.  Avoid this by explicitly/directly releasing any extant array stream before another driver operation.
> fix(python/adbc_driver_manager): don't leak array streams

- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- If DirectResults is set, then after query execution the server will automatically poll operation status, fetch results, and close the operation if all rows were fetched
- In the cases where the close operation has already succeeded in the direct results response, remove the redundant call when disposing the statement
> fix(csharp/src/Drivers/Databricks): Remove redundant statement close operation

- rust/README.md
- rust/core/src/driver_manager.rs
- rust/core/src/ffi/types.rs
- rust/core/src/lib.rs
- rust/driver/dummy/tests/driver_exporter_dummy.rs
- rust/driver/snowflake/src/duration.rs
Fixed only comments and README.
There are no code changes. 
Closes #2954
> chore(rust): fix typo

- go/adbc/driver/internal/driverbase/connection.go
- go/adbc/driver/snowflake/driver_test.go
This fix ensures the traceParent option is propagated from the Driver.Open to Database.Connect.
> fix(go/adbc/driver/internal/driverbase): Ensure to propagate the traceParent from the driver/database to connection

- .github/workflows/native-unix.yml
- .github/workflows/native-windows.yml
> ci: bump pipelines to test 3.13 instead of 3.12 or 3.11

- r/adbcdrivermanager/src/options.cc
Fixed only error messages.
Closes #2974
> chore(r): fix typo

- r/adbcsqlite/cleanup
- r/adbcsqlite/configure
> fix(r/adbcsqlite): Don't print results of compilation failure when checking for extension support

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/FeatureVersionNegotiator.cs
Includes basic versioning checks and disables pkfk for low versions.
Generally, we prefer to rely on server-side versioning checks. (Though there is some added risk of client opting into features that aren't officially supported by older clusters)
Since we may eventually change decision, includes other features for visibility.
> feat(csharp/src/Drivers/Databricks): Protocol feature negotiator

- .codespell-ignore
- .codespellrc
- .pre-commit-config.yaml
- CONTRIBUTING.md
- dev/release/rat_exclude_files.txt
> chore: add codespell

- go/adbc/driver/internal/driverbase/driver_test.go
- go/adbc/driver/internal/driverbase/statement.go
Looks like the changes and update for the Otel infrastructure introduced a mismatch with how the interface for ExecuteSchema is handled. As a result we have a failing test: https://github.com/apache/arrow-adbc/actions/runs/15828865854/job/44625340147
This change updates the interface definition to fix the tests.
> fix(go/adbc/driver/internal/driverbase): fix missing interface func

- ci/scripts/python_util.sh
- docs/source/conf.py
- python/adbc_driver_manager/adbc_driver_manager/_dbapi_backend.py
- python/adbc_driver_manager/adbc_driver_manager/dbapi.py
- python/adbc_driver_manager/tests/test_dbapi_polars_nopyarrow.py
> feat(python/adbc_driver_manager): support more APIs sans PyArrow

- .github/workflows/rust.yml
- rust/Cargo.toml
- rust/driver/datafusion/Cargo.toml
Context #2739
Closes #2524
Since datafusion tends to require newer versions of arrow than adbc_core, the version of arrow used by adbc_core will be bumped by adbc_datafusion when compiling the entire workspace.
This PullRequest separates the arrow requirements for adbc_datafusion and others.
Since the newer arrow that meets adbc_datafusion requirements will be used when the entire workspace is compiled, a job to test other than adbc_datafuion by generating a file that locks the lower requirements on CI is added.
It make sure adbc_core will work with the older arrow.
> chore(rust): separate adbc_core and adbc_datafusion arrow version requirements

- glib/example/vala/meson.build
`{build,source}_root()` are deprecated.
Fixes #3042.
> chore(glib): Use project_{build,source}_root() instead of {build,source}_root()

- docs/source/ext/sphinx_recipe/pyproject.toml
- python/adbc_driver_bigquery/pyproject.toml
- python/adbc_driver_flightsql/pyproject.toml
- python/adbc_driver_manager/pyproject.toml
- python/adbc_driver_postgresql/pyproject.toml
- python/adbc_driver_snowflake/pyproject.toml
- python/adbc_driver_sqlite/pyproject.toml
> chore(python): update license field in pyproject.toml

- go/adbc/pkg/flightsql/utils.c
- go/adbc/pkg/flightsql/utils.h
returning back function FlightSQLDriverInit
Fixes [3055](https://github.com/apache/arrow-adbc/issues/3055).
> fix(go/adbc): adding back compatibility for function FlightSQLDriverInit

- go/adbc/drivermgr/wrapper.go
Use the updated driver manager implementation to set load flags by default so that the Go Driver Manager is able to discover and load drivers via toml Manifest Files.
> feat(go/adbc/drivermgr): Set default load flags for drivermgr to load manifests

- docs/source/driver/flight_sql.rst
- docs/source/driver/installation.rst
- docs/source/driver/snowflake.rst
Close #2907
The commands listed in the README of each R package were modified by #2262, but the main site was not updated.
Installation from the R-multiverse community repository has been stable for the past several months and should be recommended to users.
> docs: update installation commands for R

- ci/scripts/python_wheel_unix_test.sh
- python/adbc_driver_manager/pyproject.toml
> build(python): enable freethreaded wheel on Linux

- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchDownloadManager.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchReader.cs
- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchResultFetcher.cs
- csharp/src/Drivers/Databricks/DatabricksCompositeReader.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksReader.cs
- csharp/test/Drivers/Databricks/CloudFetch/CloudFetchResultFetcherTest.cs
- csharp/test/Drivers/Databricks/CloudFetchE2ETest.cs
This is because there is a bug on runtime-side:
>   Sometimes TSparkDirectResults.TFetchResultsResp.TRowSet could be non-link responses (ARROW_BASED_SET), but still TSparkDirectResults.TGetResultSetMetadataResp.ResultFormat == URL_BASED_SET
This PR gets around that by directly inspecting the results. Since we do not always have DirectResults, we make an additional FetchResult call to determine whether to use `CloudFetchReader` or arrow-based `DatabricksReader`. Only if the result contains links does it decide to use `CloudFetchReader`.
This test does not pass in 11.3, 10.4 DBR until this commit.
dotnet test --filter "FullyQualifiedName~LZ4DecompressionCapabilityTest"
Remaining work: need to update status polling to start earlier, ideally should be managed by new DatabricksCompositeReader
> feat(csharp/src/Drivers/Databricks): Fix for older DBR versions incorrect ResultFormat

- docs/source/driver/snowflake.rst
- go/adbc/driver/snowflake/bulk_ingestion.go
fixes #2793 by checking for a concurrency of 0 and setting it to unlimited.
> fix(go/adbc/driver/snowflake): fix copy concurrency 0

- .github/workflows/r-basic.yml
- r/adbcbigquery/src/Makevars.in
- r/adbcflightsql/src/Makevars.in
- r/adbcsnowflake/src/Makevars.in
> fix(r/adbcbigquery,r/adbcflightsql,r/adbcsnowflake): fix warnings on R CMD check for  Go-based drivers

- dev/release/verify-release-candidate.sh
> chore(dev/release): add Python 3.13 to the default wheel test targets

- CONTRIBUTING.md
The mixing of `cd` and `pushd` caught my attention (especially line 232), so I am wondering if it is worth replacing `cd` with `pushd`.
> docs: consistent use of `pushd` instead of `cd` in the contributing guide

- python/adbc_driver_bigquery/adbc_driver_bigquery/__init__.py
This enum has an incorrect string value, meaning that the example in readme.md does not work.
We need to change the string value to `adbc.bigquery.sql.auth_credentials`, which I can confirm works locally.
See here for reference:
https://github.com/apache/arrow-adbc/commit/e7e2519fbd330f159d82fd1bed651e67f58b26d1#diff-4b8bab909f2ed237b907b8ed07148ac196124744850cae59fd4b202a01906091R25-R41
> fix(python/adbc_driver_bigquery): correct string value of credential enum

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/TracingDelegatingHandler.cs
- csharp/test/Drivers/Databricks/DatabricksConnectionTest.cs
- csharp/test/Drivers/Databricks/DatabricksTestConfiguration.cs
- csharp/test/Drivers/Databricks/DatabricksTestEnvironment.cs
- csharp/test/Drivers/Databricks/TracingDelegatingHandlerTest.cs
- Adds W3C trace context propagation to the Databricks C# driver via HTTP headers
- Makes trace propagation configurable with options for enablement, header names, and trace state
- Integrates with existing ADBC tracing infrastructure to support distributed tracing
This PR implements W3C Trace Context (traceparent/tracestate) propagation
for the Databricks C# driver. When distributed tracing is enabled, the
driver now propagates trace context to Databricks servers, enabling
end-to-end request tracing across the distributed system.
- Added `TracingDelegatingHandler` to inject trace headers into HTTP requests
- Integrated handler into the existing HTTP pipeline in `DatabricksConnection`
- Added configuration options:
- `adbc.databricks.trace_propagation.enabled` (default: true)
- …
> feat(csharp/src/Drivers/Databricks): Add W3C trace context

- csharp/src/Drivers/Databricks/RetryHttpHandler.cs
- csharp/test/Drivers/Databricks/RetryHttpHandlerTest.cs
This PR set the `SqlState` of the timeout exception raised in Databricks `RetryHttpHandler` to align SqlState used in same exception in other Databricks drivers including JDBC. 
- Set the `SqlState` of the timeout exception raised in Databricks `RetryHttpHandler`
- Fixed a bug in the unit test `RetryHttpHandlerTest`
Fix the failure in unit test `RetryHttpHandlerTest` and align the error message with other Databricks drivers.
- Unt test RetryHttpHandlerTest
- End-to-end test
> fix(csharp/src/Drivers/Databricks): Set the SqlState of the exception in RetryHttpHandler

- csharp/src/Drivers/Databricks/CloudFetch/CloudFetchResultFetcher.cs
- Fixed failing unit tests in CloudFetchResultFetcherTest by correcting the conditional logic for processing initial results
- The fetcher now properly handles initial results regardless of the `HasDirectResults` flag state
Two unit tests were failing:
- `InitialResults_ProcessesInitialResultsCorrectly`
- `InitialResults_WithMoreRows_ContinuesFetching`
The issue was in the condition that checks whether to process direct/initial results. The previous logic required
`_statement.HasDirectResults` to be true even when processing initial results passed to the constructor, which
prevented the initial results from being processed in test scenarios.
Changed the conditional logic from:
```csharp
if (_statement.HasDirectResults &&
(_statement.DirectResults?.ResultSet?.Results?.ResultLinks?.Count > …
```
> fix(csharp/src/Drivers/Databricks): fix CloudFetchResultFetcher initial results processing logic

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
FeatureVersionNegotiator introduced a bug where user-set enablePKFK is overridden by server negotiation logic. This means that if user specifies enablePKFK = false, but server version is high enough, it will override and set enablePKFK = true. 
ShouldReturnEmptyPkFkResult_WorksAsExpected fully passes after this change
> feat(csharp/src/Drivers/Databricks): Fix EnablePkFk

- .github/workflows/dev_pr.yml
> ci: don't check for pings in PR body when it's Dependabot

- glib/adbc-arrow-glib/statement.c
- glib/adbc-arrow-glib/statement.h
- glib/adbc-glib/statement.c
- glib/adbc-glib/statement.h
- glib/test/test-arrow-statement.rb
- glib/test/test-statement.rb
- ruby/lib/adbc/statement.rb
- ruby/test/test-statement.rb
* Add `gadbc_statement_get_parameter_schema()`
* Add `gadbc_arrow_statement_get_parameter_schema()`
* Adjust API in Ruby
Fixes #3117.
> feat(glib): add AdbcStatementGetParameterSchema() bindings

- csharp/src/Apache.Arrow.Adbc/Apache.Arrow.Adbc.csproj
- csharp/src/Client/Apache.Arrow.Adbc.Client.csproj
- csharp/src/Drivers/Apache/Apache.Arrow.Adbc.Drivers.Apache.csproj
- csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj
- csharp/src/Drivers/Databricks/Apache.Arrow.Adbc.Drivers.Databricks.csproj
- csharp/src/Drivers/FlightSql/Apache.Arrow.Adbc.Drivers.FlightSql.csproj
- csharp/src/Drivers/Interop/FlightSql/Apache.Arrow.Adbc.Drivers.Interop.FlightSql.csproj
- csharp/src/Drivers/Interop/Snowflake/Apache.Arrow.Adbc.Drivers.Interop.Snowflake.csproj
- csharp/test/SmokeTests/Interop/FlightSql/Apache.Arrow.Adbc.SmokeTests.Drivers.Interop.FlightSql.csproj
- dev/release/post-07-csharp.sh
- Updates the drivers to .NET 8 because the System.Diagnostics.DiagnosticSource package requires it, and .NET 6 support ended last year.
- Updates the publish script to include all drivers now
> feat(csharp/src/Drivers): update drivers to .NET 8

- csharp/src/Drivers/Databricks/DatabricksStatement.cs
When `DESC TABLE EXTENDED {fullTableName} AS JSON` fails to run, we will fallback base class `GetColumnsExtendedAsync` which calls 3 metadata query to get the info, but the current check is based on the error message, which is not accurate, instead, we can check the `SqlState` = `42601` which is the error of SQL syntax error, it means the command is not supported by the runtime, then we can fallback to the base class 
- Update the fallback condition check in `Databricks` `GetColumnsExtendedAsync`
- End-to-end test with the runtime does not support the command
> fix(csharp/src/Drivers/Databricks): Change fallback check of Databricks.GetColumnsExtendedAsync

- go/adbc/pkg/Makefile
When running from the PowerShell script as part of an ADO pipeline, the line
```
GIT_VERSION=$(shell git tag ...
```
was generating the error:
```
EXEC : error : malformed object name '--sort=-v:refname' [C:\__w\1\s\arrow-adbc\csharp\src\Drivers\Interop\FlightSql\Apache.Arrow.Adbc.Drivers.Interop.FlightSql.csproj]
```
This change swaps some of the commands but also has a separate PowerShell command for the Windows OS instead of the shell command.
> fix(go/adbc/pkg): add PowerShell option to run when executing in a Windows-based ADO pipeline

- .codespell-dictionary
- .codespellrc
- csharp/src/Drivers/FlightSql/FlightSqlDriver.cs
- dev/release/rat_exclude_files.txt
Adding a user dictionary allows detection of a typo `Arrpw`.
```console
$ pre-commit run codespell --all-files
codespell................................................................Failed
- hook id: codespell
- exit code: 65
csharp/src/Drivers/FlightSql/FlightSqlDriver.cs:23: Arrpw ==> Arrow
```
Closes #3128
> chore: fix typo

- .pre-commit-config.yaml
- go/adbc/drivermgr/vendored/toml++/toml.hpp
- go/adbc/drivermgr/wrapper.go
The `drivermgr` package referenced the c/vendor directory in the CGO building which doesn't work as that isn't within the Go module itself and wouldn't get included when the module is served as a dependency. We need to properly vendor the toml++ header file in the Go source so that it is delivered and packaged with the module properly.
> fix(go/adbc/drivermgr): properly vendor toml++

- csharp/src/Drivers/Databricks/BaseDatabricksReader.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/DatabricksStatement.cs
- csharp/test/Drivers/Databricks/E2E/StringValueTests.cs
Databricks adds `RunAsync` (default is false) option for all the thrift operations, when it is set as `true`, the operation runs async at the backend and the status can be polled by calling getStatus, it helps Databricks backend to better manage capacity and load on client requests. Furthermore, it can avoid the unnecessary retry on thrift operation (e.g. TExecuteStatementReq) when the warehouse is stopped or unavailable, the backend will returns 503 error when `RunAsync` is false and client has to retry on this thrift operation till the warehouse is up, this generates lots of queries with 503 errors in the Databricks query history and consume more resources. When `RunAsync=true`, server will return 200 with query state `PENDING`, the client will poll the status till the warehouse is up, …
> feat(csharp/test/Drivers/Databricks): Enable RunAsync option in TExecuteStatementReq

- rust/Cargo.lock
- rust/driver/datafusion/Cargo.toml
- rust/driver/datafusion/README.md
- rust/driver/datafusion/src/lib.rs
- rust/driver/datafusion/tests/test_datafusion.rs
- Bumps `datafusion-*` to 48.0.1 and `arrow-*` to 55.2.
- Disables default features of `datafusion` and `datafusion-substrait`
- Put C driver export behind `ffi` feature flag
- Closes #3144
> chore(rust/driver/datafusion)!: update to datafusion 48

- c/driver/bigquery/README.md
- c/driver/flightsql/README.md
- c/driver/postgresql/README.md
- c/driver/snowflake/README.md
- c/driver/sqlite/README.md
- c/integration/duckdb/README.md
- csharp/src/Drivers/Apache/Hive2/README.md
- csharp/src/Drivers/Apache/Impala/README.md
- csharp/src/Drivers/Apache/Spark/README.md
- csharp/src/Drivers/BigQuery/readme.md
- csharp/src/Drivers/Databricks/readme.md
- csharp/src/Drivers/FlightSql/README.md
- docs/source/conf.py
- docs/source/driver/duckdb.rst
- docs/source/driver/flight_sql.rst
- docs/source/driver/jdbc.rst
- docs/source/driver/postgresql.rst
- docs/source/driver/snowflake.rst
- docs/source/driver/sqlite.rst
- docs/source/driver/status.rst
- docs/source/ext/adbc_misc.py
- java/driver/flight-sql/README.md
- java/driver/jdbc/README.md
- python/adbc_driver_bigquery/adbc_driver_bigquery/__init__.py
- rust/driver/datafusion/README.md
> docs: generate driver status from README badges

- docs/source/format/driver_manifests.rst
Minor follow-up edits to https://github.com/apache/arrow-adbc/pull/3176. Some syntax fixes, some editorial.
> docs: minor edits for first version of driver manager docs

- csharp/src/Drivers/Databricks/RetryHttpHandler.cs
- csharp/test/Drivers/Databricks/Unit/RetryHttpHandlerTest.cs
Follow up of https://github.com/apache/arrow-adbc/pull/3177#discussion_r2220493096
- Added support for additional HTTP status codes: 408 (Request Timeout), 502 (Bad Gateway), and 504 (Gateway Timeout), in addition to the existing 503 (Service Unavailable)
- Implemented exponential backoff with jitter when no Retry-After header is present
Unit tests
`dotnet test --filter "FullyQualifiedName~RetryHttpHandlerTest"`
```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v3.1.1+bf6400fd51 (64-bit .NET 8.0.7)
[xUnit.net 00:00:00.06]   Discovering: Apache.Arrow.Adbc.Tests.Drivers.Databricks
[xUnit.net 00:00:00.15]   Discovered:  Apache.Arrow.Adbc.Tests.Drivers.Databricks
[xUnit.net 00:00:00.16]   Starting:    Apache.Arrow.Adbc.Tests.Drivers.Databricks
[xUnit.net 00:00:25.28]   Finished: …
```
> fix(csharp/test/Drivers/Databricks): Enrich RetryHttpHandler with other status codes

- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
When the client calls `HiveServer2Statement` to execute metadata query (e.g. GetCatalogsAsync, GetSchemasAsync), it won't set `_directResults`, which leads to a unnecessary thrift call (`CloseOperation`) in its `HiveServer2Statement.Dispose`, this is because it will make a blocking call `CloseOperation` if `_directResults=null`  (see code [here](https://github.com/apache/arrow-adbc/blob/main/csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs#L378)), it introduces 100ms-200ms latency for every metadata call/query
Set `HiveServer2Statement._directResults` from resp.DirectResult in every metadata API in `HiveServer2Statement`, thus thrift `CloseOperation`  won't be called in `Dispose` if metadata query/option returns a successful `DirectResult`.
- All the E2E testing on Databricks …
> fix(csharp/src/Drivers/Apache/Hive2): Remove unnecessary CloseOperation in Statement.Dispose when query is metadata query

- csharp/src/Drivers/BigQuery/BigQueryParameters.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/src/Drivers/BigQuery/readme.md
- csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs
- csharp/test/Drivers/BigQuery/DriverTests.cs
- change to use _bqadbc_temp_tables as the default dataset if large record sets are needed
- removes the created_by tag, which was having its own issues with the `-SNAPSHOT+` content was included in the file version. Since the tables are now in the _bqadbc_temp_tables dataset, it shouldn't be necessary to indicate what driver created them
- adds some testing for parallelizing queries to do scale testing
> fix(csharp/src/Drivers/BigQuery): Adjust default dataset id

- csharp/test/Drivers/Databricks/E2E/StatementTests.cs
This test does not pass, since catalog from OpenSessionResponse is used as catalog, if user does not explictly set catalog as a metadata request parameter
> fix(csharp/test/Drivers/Databricks): Fix Pkfk Testcase

- go/adbc/driver/flightsql/utils.go
- go/adbc/driver/snowflake/driver.go
- go/adbc/pkg/_tmpl/driver.go.tmpl
- go/adbc/pkg/bigquery/driver.go
- go/adbc/pkg/flightsql/driver.go
- go/adbc/pkg/panicdummy/driver.go
- go/adbc/pkg/snowflake/driver.go
- python/adbc_driver_flightsql/tests/test_errors.py
> fix(go/adbc): Forward SQLSTATE and vendor code

- csharp/src/Drivers/Databricks/DatabricksStatement.cs
Sometimes Databricks DBR or SQL warehouse fails to execute `DESC TABLE EXTENDED` due to some internal error on data type parsing and returns SQL State `20000 `. In this case, we also want to fallback to the `HiveStatement2.GetColumnsExtendedAsync`
Add the fallback condition check on `SqlState==20000` in `Databricks GetColumnsExtendedAsync`
- E2E test
> fix(csharp/src/Drivers/Databricks): Add another fallback check of GetColumnsExtendedAsync

- csharp/src/Drivers/Databricks/Auth/JwtTokenDecoder.cs
- csharp/src/Drivers/Databricks/Auth/MandatoryTokenExchangeDelegatingHandler.cs
- csharp/src/Drivers/Databricks/Auth/TokenExchangeClient.cs
- csharp/src/Drivers/Databricks/Auth/TokenRefreshDelegatingHandler.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/test/Drivers/Databricks/E2E/Auth/TokenExchangeTests.cs
- csharp/test/Drivers/Databricks/Unit/Auth/JwtTokenDecoderTests.cs
- csharp/test/Drivers/Databricks/Unit/Auth/MandatoryTokenExchangeDelegatingHandlerTests.cs
- csharp/test/Drivers/Databricks/Unit/Auth/TokenExchangeClientTests.cs
- csharp/test/Drivers/Databricks/Unit/Auth/TokenRefreshDelegatingHandlerTests.cs
Databricks will eventually require that all non-inhouse OAuth tokens be exchanged for Databricks OAuth tokens before accessing resources. This change implements mandatory token exchange before sending Thrift requests. This check and exchange is performed in the background for now to reduce latency, but it will eventually need to be blocking if non-inhouse OAuth tokens will fail to access Databricks resources in the future. 
1. JWT Token Decoder - Decodes JWT tokens to inspect the issuer claim and determine if token exchange is necessary
2. MandatoryTokenExchangeDelegatingHandler - HTTP handler that intercepts requests and performs token exchange when required
3. TokenExchangeClient - Handles the token exchange logic with the same /oidc/v1/token endpoint as token refresh, with slightly …
> feat(csharp/test/Drivers/Databricks): Add mandatory token exchange

- docs/source/format/specification.rst
Clarifies the relation between this document and the authoritative definition of the ADBC API.
> docs: clarify relationship specification.rst to adbc.h

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
In PR https://github.com/apache/arrow-adbc/pull/3171, `RunAsync` option in `TExecuteStatementReq` was added and exposed via connection parameter `adbc.databricks.enable_run_async_thrift`, but it is not enabled by default. This is turned on by default in other Databricks drivers, we should turn in on by default in ADBC as well.
- Set `DatabricksConnection:_runAsyncInThrift` default value to `true`
- PBI PQTest with all the test cases
> fix(csharp/src/Drivers/Databricks): Set enable_run_async_thrift default true

- go/adbc/README.md
Improves the existing go pkgsite by adding a README.
This is an alternative to https://github.com/apache/arrow-adbc/pull/3199.
> docs: improve go docs by adding a readme

- csharp/src/Drivers/BigQuery/RetryManager.cs
Current error messages do not contain details for what occurred, only a message like:
`Cannot execute <ReadChunkWithRetries>b__0 after 5 tries`
This adds the Message of the last exception that occurred as well.
> fix(csharp/src/Drivers/BigQuery): add details for retried error message

- rust/driver_manager/src/lib.rs
Replicates the change in https://github.com/apache/arrow-adbc/pull/3250 to the Rust Driver Manager. Follow-on to #3247 
Modifies the behavior of GetSearchPaths so macOS doesn't follow other Unix-likes but instead uses the more conventional /Library/Application Support/ADBC. /etc/ isn't really a thing on macOS.
Tested manually by debugging the test with and without `/Library/Application Support/ADBC` existing and verifying the right branch gets hit. I'm not too worried exercising this in CI but we could.
> fix(rust/driver_manager): modify SYSTEM path behavior on macOS

- csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
Dynamic libraries implemented in Go cannot safely be unloaded. Prevent this by default but add a flag to opt-into unloading the library.
> fix(csharp/src/Apache.Arrow.Adbc/C): Stop trying to unload dynamic libraries

- go/adbc/driver/bigquery/record_reader.go
> feat(go/adbc/driver/bigquery): error if we lack readSessionUser

- go/adbc/driver/bigquery/connection.go
> fix(go/adbc/driver/bigquery): accept old auth option value

- csharp/src/Drivers/Databricks/DatabricksConfiguration.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/test/Drivers/Databricks/Unit/DatabricksConfigurationTest.cs
Introduces robust configuration loading from JSON files via environment variables with intelligent property merging and configurable precedence control.
In the system variable create a new record with name "DATABRICKS_CONFIG_FILE" and point to a local json file which hold the driver config properties. The driver config file will be loaded alongside with PowerBI.
- **Default environment variable**: `DATABRICKS_CONFIG_FILE` automatically loaded in constructor
- **Standard ADBC parameter**: The keys are standard adbc parameter: https://github.com/apache/arrow-adbc/blob/main/csharp/src/Drivers/Databricks/readme.md
```json
{
"adbc.databricks.driver_config_take_precedence": "true",
"adbc.databricks.enable_pk_fk": "false"
}
```
- **Automatic merging**: Environment config + constructor properties …
> feat(csharp/src/Drivers/Apache): add env variable config override for databricks

- .github/dependabot.yml
e.g. https://github.com/apache/arrow-adbc/pull/3305 doesn't work because datafusion requires arrow 55.
> chore: split arrow and datafusion dependabot group

- .github/dependabot.yml
Reverts apache/arrow-adbc#3328
Looks like it doesn't work https://github.com/apache/arrow-adbc/network/updates/1084373265:
```
Caused by:
error inheriting `edition` from workspace root manifest's `workspace.package.edition`
```
I guess we'll just handle these bumps manually for now.
> chore: revert split arrow and datafusion dependabot group

- csharp/src/Drivers/Apache/Spark/SparkConnection.cs
- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksStatement.cs
ExecuteStatementReq only accepts configuration after dbr 7.0, so timestampasstring did not apply to dbr < 7.0. 
The fix is to move it to Session configuration where possible
Verified it works by running StatementTests CanExecuteTimestampQuery on dbr 6.6 (fails before)
> fix(csharp/src/Drivers/Databricks): [PECO-2396] Fix timestamp for dbr 6.6 - Set timestamp configuration on OpenSessionReq

- go/adbc/driver/bigquery/connection.go
This is also documented officially https://cloud.google.com/bigquery/docs/reference/storage#arrow_schema_details see `TIMESTAMP`
> fix(go/adbc/driver/bigquery): fix timestamp arrow type to use micro seconds

- rust/driver/snowflake/src/database/builder.rs
Following #3366, this also adds the added auth types to the Rust driver.
> feat(rust/driver/snowflake): add `pat` and `wif` auth types

- docs/source/driver/bigquery.rst
Merging https://github.com/apache/arrow-adbc/pull/3452 caused the docs build to fail in https://github.com/apache/arrow-adbc/actions/runs/17883091089/job/50853293450. I expect this is due to case sensitivity so I think this change should fix the issue.
> docs: fix path case in references in bigquery.rst

- rust/core/Cargo.toml
Since we've split functionality driver manager and driver exporter into separate packages (#3106), we also need to update the package description.
> chore(rust/core): fix package description

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
- csharp/src/Drivers/Databricks/DatabricksParameters.cs
- csharp/src/Drivers/Databricks/Reader/DatabricksCompositeReader.cs
- csharp/test/Drivers/Databricks/E2E/DatabricksConnectionTest.cs
- csharp/test/Drivers/Databricks/E2E/DatabricksTestConfiguration.cs
- csharp/test/Drivers/Databricks/E2E/DatabricksTestEnvironment.cs
- csharp/test/Drivers/Databricks/Unit/DatabricksOperationStatusPollerTests.cs
Added support for the Fetch heartbeat interval connection param. The default values are kept same as before. Users can now configure this param.
[PECO-2736](https://databricks.atlassian.net/browse/PECO-2736)
> feat(csharp/src/Drivers/Databricks): Added support for user-configurable Fetch heartbeat interval param

- r/adbcdrivermanager/R/helpers.R
- r/adbcdrivermanager/man/read_adbc.Rd
- r/adbcsqlite/tests/testthat/test-adbcsqlite-package.R
> fix(r/adbcdrivermanager): support `replace` and `create_append` ingest mode in `write_adbc()`

- python/adbc_driver_manager/setup.py
> build(python/adbc_driver_manager): enable conda support properly

- csharp/src/Drivers/BigQuery/BigQueryConnection.cs
- csharp/src/Drivers/BigQuery/BigQueryParameters.cs
- csharp/src/Drivers/BigQuery/BigQueryStatement.cs
- csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs
- csharp/test/Drivers/BigQuery/BigQueryTestingUtils.cs
In the current iteration, no DefaultLocation is specified for the internal BigQueryClient. Since this is not specified, the BigQuery API makes this default to "US" which is causing failures for some users. This PR adds a new parameter to set the DefaultLocation for the BigQueryClient, which then uses that same value for creating datasets and other location-based activitities.
> feat(csharp/src/Drivers/BigQuery): Add support for specifying a location

- .github/workflows/csharp.yml
- .github/workflows/native-unix.yml
- .github/workflows/nightly-verify.yml
- .github/workflows/packaging.yml
- .github/workflows/rust.yml
- .github/workflows/verify.yml
https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
removed all references to `maco-13` except one
https://github.com/apache/arrow-adbc/blob/66461304b423b8deea75f4575a169a6cb4d76cf4/.github/workflows/packaging.yml#L559-L564
> ci: macos-13 is deprecated

- go/adbc/driver/snowflake/driver_test.go
- go/adbc/driver/snowflake/record_reader.go
When use_high_precision is false, the type for NUMBER columns with non-zero scale are incorrectly returned as Int64 instead of Float64, causing data discrepancy.
This seems to be a corner case, affecting schema only operations at the client while data path seems to be good.
> fix(go/adbc/driver/snowflake): return arrow numeric type correctly when use_high_precision is false

- csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
- csharp/src/Drivers/Databricks/DatabricksStatement.cs
- csharp/src/Drivers/Databricks/Reader/CloudFetch/CloudFetchDownloadManager.cs
- csharp/src/Drivers/Databricks/readme.md
Used connection param of batchSize for cloudFetch. Changed the default value of the param to 2 million instead of 50k.
[PECO-2732](https://databricks.atlassian.net/browse/PECO-2732)
> feat(csharp/src/Drivers/Databricks): Used connection param of batchSize for cloudFetch

- csharp/src/Drivers/Databricks/DatabricksConnection.cs
Disable `UseDescTableExtended` (use `DESC TABLE AS JOIN` to get metadata) by default in the Databricks Driver, so it will not call `DESC TABLE AS JSON` to get the meta data in Power BI by default. But customer can turn it on by setting `UseDescTableExtended=1` as the connection property in Power BI or setting `adbc.databricks.use_desc_table_extended=true` as ADBC connection properties.
- Set `DatabricksConnection:_useDescTableExtended` default value as `false`
- Unit test and E2E test
> fix(csharp/test/Drivers/Databricks): Disable UseDescTableExtended by default

- docs/source/conf.py
Replace "Apache feather logo" with "Apache logo" just like in https://github.com/apache/arrow/pull/47647.
> docs: update docs site footer for new ASF logo
