.github/workflows/dev.yml
This only runs pre-commit. Another PR will be needed to set up actual unit tests.
=> Set up pre-commit CI pipeline

adbc.h, adbc_driver_manager/adbc_driver_manager.cc, adbc_driver_manager/adbc_driver_manager.h, adbc_driver_manager/adbc_driver_manager_test.cc, drivers/flight_sql/flight_sql.cc, drivers/flight_sql/flight_sql_test.cc, drivers/sqlite/sqlite.cc, drivers/sqlite/sqlite_test.cc, drivers/test_util.h, drivers/util.h
=> Refactor initialization for consistency

.github/workflows/java.yml, .gitignore, .pre-commit-config.yaml, java/core/pom.xml, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcDatabase.java, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcDriver.java, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcException.java, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatement.java, java/core/src/main/java/org/apache/arrow/adbc/core/PartitionDescriptor.java, java/driver-manager/pom.xml, java/driver-manager/src/main/java/org/apache/arrow/adbc/drivermanager/AdbcDriverManager.java, java/driver/derby/pom.xml, java/driver/derby/src/main/java/org/apache/arrow/adbc/driver/derby/DerbyConnection.java, java/driver/derby/src/main/java/org/apache/arrow/adbc/driver/derby/DerbyDatabase.java, java/driver/derby/src/main/java/org/apache/arrow/adbc/driver/derby/DerbyDriver.java, java/driver/derby/src/main/java/org/apache/arrow/adbc/driver/derby/DerbyStatement.java, java/driver/derby/src/main/java/org/apache/arrow/adbc/driver/derby/JdbcArrowReader.java, java/driver/derby/src/test/java/org/apache/arrow/adbc/driver/derby/DerbyDatabaseTest.java, java/pom.xml
Next steps:
- Flight SQL driver
- JNI ADBC driver
=> Sketch out ADBC Java APIs

.github/workflows/cpp.yml
Also fixes the tests not actually getting built/run!
=> Add basic CI for MacOS/Windows

adbc.h, adbc_driver_manager/adbc_driver_manager.cc, drivers/flight_sql/flight_sql.cc, drivers/sqlite/sqlite.cc
Adds a wider set of error codes and describes what they're meant to be used for.
Fixes #20.
=> Improve error code table

adbc_driver_manager/CMakeLists.txt, cmake_modules/AdbcDefines.cmake
Right now we only install the shared library.
=> Install the headers along with the driver manager

adbc_driver_manager/CMakeLists.txt, adbc_driver_manager/adbc_driver_manager.cc, adbc_driver_manager/adbc_driver_manager_test.cc, drivers/sqlite/CMakeLists.txt, drivers/sqlite/sqlite.cc, drivers/sqlite/sqlite_test.cc, validation/adbc_validation.c, validation/adbc_validation.h
This is a set of self-contained tests that can be linked in and called from another test suite. Right now they don't deal with any actual data.
=> Add C driver validation suite

java/core/src/main/java/org/apache/arrow/adbc/core/AdbcConnection.java, java/core/src/main/java/org/apache/arrow/adbc/core/StandardSchemas.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/FixedJdbcStatement.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcArrowReader.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnection.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriverUtil.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcMetadataBuilder.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcStatement.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/RootArrowReader.java, java/driver/jdbc/src/test/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnectionMetadataTest.java, java/driver/testsuite/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java, java/pom.xml
Not all of the metadata is currently mapped and there are some more cases to consider in the future.
Fixes #33.
=> Implement metadata methods for JDBC

c/driver_manager/adbc_driver_manager.cc, c/drivers/sqlite/sqlite.cc, c/drivers/sqlite/sqlite_test.cc
- The SQLite catalog is called "main"
- Fix a couple bugs and note areas of improvement
=> [C] Fix compatibility issues noticed with Ibis

adbc.h, c/driver_manager/adbc_driver_manager.cc, c/drivers/sqlite/sqlite.cc, c/validation/adbc_validation.c, java/core/pom.xml, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatement.java, java/driver-manager/pom.xml, java/driver/flight-sql-validation/pom.xml, java/driver/flight-sql/pom.xml, java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlStatement.java, java/driver/jdbc-util/pom.xml, java/driver/jdbc-validation-derby/pom.xml, java/driver/jdbc-validation-postgresql/pom.xml, java/driver/jdbc/pom.xml, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcStatement.java, java/driver/validation/pom.xml, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractStatementTest.java, java/pom.xml, java/sql/pom.xml
=> [Format][C][Java] Add method to get parameter schema

.asf.yaml
Copied from Arrow's .asf.yaml.
=> MINOR: Make issue notifications less noisy

c/vendor/nanoarrow/nanoarrow.c, c/vendor/nanoarrow/nanoarrow.h, c/vendor/vendor_nanoarrow.sh, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/poetry.lock, python/adbc_driver_manager/pyproject.toml
=> [Python] Implement partitioned data interface

c/cmake_modules/AdbcDefines.cmake, c/driver_manager/CMakeLists.txt, c/driver_manager/adbc-driver-manager.pc.in
=> [C] Add support for pkg-config

adbc.h, c/driver_manager/adbc_driver_manager.cc, c/driver_manager/adbc_driver_manager_test.cc, c/drivers/flight_sql/flight_sql.cc, c/drivers/postgres/postgres.cc, c/drivers/sqlite/sqlite.cc, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/adbc_driver_manager/tests/test_dbapi.py, python/adbc_driver_manager/adbc_driver_manager/tests/test_lowlevel.py
=> [C] Specify a standard entrypoint name

.github/workflows/cpp.yml, ruby/Gemfile, ruby/README.md, ruby/Rakefile, ruby/dependency-check/Rakefile, ruby/lib/adbc.rb, ruby/lib/adbc/connection.rb, ruby/lib/adbc/database.rb, ruby/lib/adbc/loader.rb, ruby/lib/adbc/version.rb, ruby/red-adbc.gemspec, ruby/test/helper.rb, ruby/test/run.rb, ruby/test/test-connection.rb
=> [Ruby] Add minimum bindings

CONTRIBUTING.md, c/driver_manager/README.md, c/drivers/flight_sql/README.md, c/drivers/postgres/CMakeLists.txt, c/drivers/sqlite/README.md, ci/conda_env_cpp.txt, python/adbc_driver_manager/README.md, python/adbc_driver_postgres/README.md, python/adbc_driver_postgres/pyproject.toml
I ran into some Meson issues so the instructions for GLib/Ruby are incomplete.
Fixes #100.
=> [Docs] Update CONTRIBUTING.md

c/driver_manager/adbc_driver_manager_test.cc, c/drivers/postgres/postgres_test.cc, c/drivers/postgres/statement.cc, c/drivers/postgres/type.cc, c/drivers/sqlite/sqlite_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h
=> [C] Validate statement behaviors in test suite

.github/workflows/cpp.yml, ruby/.gitignore, ruby/red-adbc.gemspec
=> [Ruby] Don't use ../ for RubyGems packaging

c/validation/adbc_validation.cc
Arrow's build process uses precompiled headers which causes a name clash
=> [C] Don't conflict with Arrow macros

adbc.h
The content will be added to the docs instead in #138.
=> docs(format): remove doxygen content

.github/workflows/cpp.yml, .github/workflows/dev.yml, .github/workflows/dev_pr.yml, .github/workflows/dev_pr/title_check.js, .github/workflows/go.yml, .github/workflows/java.yml
Similar to https://github.com/apache/arrow/pull/14155
=> ci: update action versions, restrict token scopes

.github/workflows/packaging-wheels.yml
Fix a typo in a condition, and add a step to show the input parameters.
=> ci(c/driver_manager,c/driver/postgres): fix manually dispatched wheel builds

ci/scripts/python_wheel_unix_build.sh, ci/vcpkg/triplets/x64-linux-static-release.cmake, ci/vcpkg/triplets/x64-osx-static-release.cmake
=> ci: fix vcpkg triplets

c/driver/postgres/README.md, c/driver/postgres/util.h
...basically, what it took for me to build and run all the tests 🙂
=> fix(c/driver/postgres): Fix duplicate symbols; add note about PKG_CONFIG_PATH

ci/scripts/python_wheel_windows_build.bat
=> ci: use delvewheel for Windows wheels

.github/workflows/cpp.yml, .github/workflows/go.yml, ci/scripts/cpp_build.sh, ci/scripts/cpp_test.sh, ci/scripts/glib_build.sh, ci/scripts/glib_test.sh, ci/scripts/go_build.sh, ci/scripts/go_test.sh, ci/scripts/python_build.sh, ci/scripts/python_test.sh
=> ci(c): factor out build scripts

python/adbc_driver_manager/pyproject.toml, python/adbc_driver_postgres/adbc_driver_postgres/__init__.py, python/adbc_driver_postgres/pyproject.toml, python/adbc_driver_sqlite/adbc_driver_sqlite/__init__.py, python/adbc_driver_sqlite/pyproject.toml
=> chore(c/driver/postgres,c/driver/sqlite): fix DeprecationWarning in Python bindings

.env, .github/workflows/packaging-wheels.yml
Also enable 3.11 builds.
Fixes #202.
=> ci: update vcpkg version

dev/release/04-java-upload.sh
This depends on https://github.com/apache/arrow/pull/14830 .
=> chore: add support for uploading Java artifacts

c/driver/postgres/AdbcDriverPostgresConfig.cmake.in, c/driver/postgres/CMakeLists.txt, c/driver/postgres/adbc-driver-postgres.pc.in, c/driver/sqlite/AdbcDriverSqliteConfig.cmake.in, c/driver/sqlite/CMakeLists.txt, c/driver/sqlite/adbc-driver-sqlite.pc.in
=> feat(c/driver/postgres,c/driver/sqlite): add pkg-config/CMake definitions

.github/workflows/cpp.yml, c/driver_manager/adbc_driver_manager.cc, c/driver_manager/adbc_driver_manager_test.cc, c/validation/adbc_validation_util.h
=> test(c/driver_manager): test two drivers in-process

.github/workflows/cpp.yml, ci/scripts/glib_test.sh, glib/Gemfile, ruby/Gemfile
=> chore(glib,ruby): unpin red-arrow

docs/source/_static/css/custom.css, docs/source/conf.py, docs/source/driver/cpp/flight_sql.rst
Corresponds to https://github.com/apache/arrow/pull/14082
=> docs(c/driver/flight_sql): document new driver options

ci/scripts/docs_build.sh, docs/source/conf.py, docs/source/contributing.rst, docs/source/driver/cpp/flight_sql.rst, docs/source/driver/cpp/postgresql.rst, docs/source/driver/cpp/sqlite.rst, docs/source/index.rst, docs/source/nightly.rst, docs/source/python/index.rst, docs/source/python/quickstart.rst
=> docs: add basic installation instructions and tutorial

python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/tests/test_dbapi.py
=> feat(c/driver_manager): allow Arrow data as parameters in DBAPI layer

c/cmake_modules/AdbcDefines.cmake, c/cmake_modules/AdbcVersion.cmake, c/driver/postgresql/CMakeLists.txt, c/driver/postgresql/database.cc, c/driver/postgresql/statement.cc, c/driver/postgresql/statement.h, c/driver/postgresql/type.h, c/driver/sqlite/CMakeLists.txt, c/driver/sqlite/sqlite.c, c/driver/sqlite/sqlite_test.cc, c/driver/sqlite/statement_reader.c, c/driver/sqlite/statement_reader.h, c/driver/sqlite/utils.c, c/validation/AdbcValidationConfig.cmake.in, c/validation/CMakeLists.txt, c/validation/adbc_validation.cc, c/validation/adbc_validation_util.cc, c/validation/adbc_validation_util.h, c/vendor/nanoarrow/nanoarrow.c, c/vendor/nanoarrow/nanoarrow.h, c/vendor/nanoarrow/nanoarrow.hpp
As discussed in apache/arrow#14082.
=> chore: add CMake config for validation suite, update nanoarrow

.pre-commit-config.yaml, dev/release/rat_exclude_files.txt
=> ci: run rat in pre-commit

.github/workflows/packaging.yml, .gitignore, ci/linux-packages/Rakefile, ci/linux-packages/yum/almalinux-8/Dockerfile, ci/linux-packages/yum/almalinux-9/Dockerfile, ci/linux-packages/yum/apache-arrow-adbc.spec.in, dev/release/verify-yum.sh
=> chore: add support for AlmaLinux packages

dev/release/utils-prepare.sh
For some reason Maven didn't update all of the package versions just now.
=> chore(dev/release): make sure Maven updates all versions

dev/release/02-source.sh
=> chore(dev/release): fix unbound variable in 02-source.sh

.github/workflows/verify.yml, dev/release/02-source.sh, dev/release/verify-release-candidate.sh
=> chore(dev/release): fix URLs in verification

.github/workflows/packaging.yml
=> chore: fix upload pattern for GitHub release

.github/workflows/packaging.yml
=> chore(dev/release): fix upload stage for Linux packages

dev/release/03-binary-sign.sh
=> chore(dev/release): use correct URLs for verification

dev/release/verify-release-candidate.ps1
=> chore(dev/release): implement RC verification for Windows

.gitattributes, python/adbc_driver_manager/adbc_driver_manager/_static_version.py, python/adbc_driver_postgresql/adbc_driver_postgresql/_static_version.py, python/adbc_driver_sqlite/adbc_driver_sqlite/_static_version.py
=> chore: update .gitattributes with export-subst directives

.github/workflows/verify.yml, dev/release/verify-release-candidate.sh
=> chore(dev/release): skip APT/Yum verifications without Docker

ci/scripts/java_build.sh
=> chore(dev/release): make local Maven repository detection more portable

ci/scripts/glib_test.sh
=> chore(dev/release): install gem into build directory in verification

.github/workflows/packaging.yml
=> ci: fix typo in Gemfury upload step

c/driver/postgresql/util.h, ci/scripts/glib_test.sh
=> fix(c/driver/postgresql): define ntohll etc for macOS 10.9

ci/scripts/java_jar_upload.sh
=> ci: retry Gemfury uploads

ci/scripts/python_sdist_test.sh, ci/scripts/python_wheel_unix_build.sh, ci/scripts/python_wheel_unix_test.sh, ci/scripts/python_wheel_windows_build.bat, ci/scripts/python_wheel_windows_test.bat, python/adbc_driver_postgresql/README.md, python/adbc_driver_postgresql/pyproject.toml, python/adbc_driver_sqlite/README.md, python/adbc_driver_sqlite/pyproject.toml
=> fix(python): add driver -> driver manager dependency

ci/scripts/gemfury_clean.rb
=> ci: change Gemfury cleaning logic to be time-based

docs/source/development/releasing.rst, docs/source/index.rst
=> docs: add RC verification instructions

docs/source/development/releasing.rst
=> docs: simplify RC verification instructions

ci/scripts/glib_test.sh, dev/release/verify-release-candidate.sh
Use local install directory when using bundler
Addressing:
https://github.com/apache/arrow-adbc/issues/343
=> fix(dev/release): Update install location for Ruby gems and bundler

c/driver/postgresql/database.cc, c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc, c/driver/postgresql/type.cc, c/driver/postgresql/type.h, c/driver/postgresql/util.h
=> feat(c/driver/postgresql): expand type support

go/adbc/driver/flightsql/record_reader.go, go/adbc/go.mod, go/adbc/go.sum
=> fix(go/adbc/driver/flightsql): implement RecordReader.Err

go/adbc/driver/flightsql/flightsql_statement.go, go/adbc/driver/flightsql/utils.go, go/adbc/go.mod, go/adbc/go.sum, go/adbc/pkg/_tmpl/driver.go.tmpl, go/adbc/pkg/flightsql/driver.go
=> fix(go/adbc/driver/flightsql): bind ExecuteUpdate, BindStream

python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/tests/test_lowlevel.py
=> feat(python/adbc_driver_manager): add more sanity checking

go/adbc/driver/flightsql/record_reader_test.go
=> test(go/adbc/driver/flightsql): add tests for DoGet fallback

ci/conda/build-python.bat, ci/conda/build-python.sh, ci/conda/meta.yaml
- Don't bundle the shared library
- Don't rebuild it per Python version
Fixes #388.
=> fix(ci): make sure Conda packages are properly noarch

c/driver/flightsql/sqlite_flightsql_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h, go/adbc/driver/flightsql/flightsql_adbc.go
Punts in implementing column constraint (primary key/foreign key/unique constraint) info.
Part of #380.
=> feat(go/adbc/driver/flightsql): implement GetObjects

docs/source/driver/go/flight_sql.rst, go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go, go/adbc/driver/flightsql/flightsql_statement.go
=> feat(go/adbc/driver/flightsql): bump max incoming message size

.github/workflows/packaging.yml, ci/scripts/python_conda_clean.sh
=> chore(ci): remove existing Conda packages before upload

dev/release/06-binary-verify.sh, dev/release/post-09-website.sh, dev/release/utils-prepare.sh, docs/source/development/releasing.rst
=> chore(dev/release): add vote email template

docs/source/driver/installation.rst, docs/source/index.rst
=> docs: add top-level installation page

docs/source/driver/cpp/index.rst, docs/source/driver/go/index.rst, docs/source/driver/status.rst, docs/source/format/specification.rst, docs/source/index.rst
=> docs: add status page/feature matrix

ci/scripts/java_jar_upload.sh
=> chore(ci): fix upload of POM-only Java artifact

dev/release/verify-release-candidate.ps1, dev/release/verify-release-candidate.sh
=> chore(dev/release): disable Flight SQL C++ tests in verification

.gitattributes, .github/workflows/nightly-verify.yml, .github/workflows/verify.yml, .pre-commit-config.yaml, dev/release/verify-release-candidate.ps1, dev/release/verify-release-candidate.sh, docs/source/development/releasing.rst
=> ci: set up nightly verification build

dev/release/verify-release-candidate.sh
=> chore(dev/release): fix wheel verification

c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc, c/driver/sqlite/sqlite.c, c/driver/sqlite/sqlite_test.cc, c/driver/sqlite/statement_reader.c, c/validation/adbc_validation.cc, c/validation/adbc_validation_util.cc, c/validation/adbc_validation_util.h, c/vendor/nanoarrow/nanoarrow.c, c/vendor/nanoarrow/nanoarrow.h
Also updates Nanoarrow.
Fixes #453.
=> fix(c/driver/sqlite): fix nullability of GetInfo schema

go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go
=> fix(go/adbc/driver/flightsql): don't require GetSqlInfo support

ci/linux-packages/apt/debian-bookworm/Dockerfile, ci/scripts/glib_test.sh
=> ci: make tests more robust to red-arrow/arrow-c-glib upgrades 

go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go, go/adbc/driver/flightsql/flightsql_statement.go, go/adbc/driver/flightsql/utils.go
=> fix(go/adbc/driver/flightsql): fix stream timeout interceptor

go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go
=> feat(go/adbc/driver/flightsql): add user-agent for driver

docs/source/development/releasing.rst
=> docs(dev/release): add conda-forge to post-release process

.github/workflows/nightly-website.yml
=> ci: don't deploy website on RC tags

.github/workflows/packaging.yml
=> ci: don't build Conda packages for RCs

dev/release/06-binary-verify.sh
* Run the verification script from main (so we always get the most up-to-date one)
* Fix the link to the closed issues
Fixes #449.
Fixes #450.
=> chore(dev/release): verify using main, not tag

.asf.yaml, README.md, docs/source/faq.rst, docs/source/index.rst
=> docs: update README and add FAQ

go/adbc/driver/flightsql/utils.go
=> fix(go/adbc/driver/flightsql): properly map error codes

go/adbc/driver/flightsql/flightsql_adbc_test.go, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/tests/test_lowlevel.py
=> fix(python/adbc_driver_manager): properly map error codes

go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go
=> feat(go/adbc/driver/flightsql): support domain sockets

.github/workflows/packaging.yml, docs/source/python/api/adbc_driver_flightsql.rst, docs/source/python/api/adbc_driver_manager.rst, docs/source/python/api/adbc_driver_sqlite.rst, python/adbc_driver_flightsql/adbc_driver_flightsql/__init__.py, python/adbc_driver_flightsql/tests/conftest.py, python/adbc_driver_flightsql/tests/test_lowlevel.py, python/adbc_driver_manager/adbc_driver_manager/__init__.py, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_sqlite/adbc_driver_sqlite/__init__.py, python/adbc_driver_sqlite/tests/test_lowlevel.py
=> feat(python): add enums for common options

c/cmake_modules/GoUtils.cmake, ci/linux-packages/apt/debian-bookworm/Dockerfile, ci/linux-packages/apt/debian-bullseye/Dockerfile, ci/linux-packages/apt/ubuntu-jammy/Dockerfile, ci/linux-packages/debian/control, ci/linux-packages/debian/libadbc-driver-flightsql-dev.install, ci/linux-packages/debian/libadbc-driver-flightsql003.install, ci/linux-packages/debian/rules, dev/release/verify-apt.sh
=> feat(deb): add libadbc-driver-flightsql

glib/adbc-glib/statement.c, glib/adbc-glib/statement.h, glib/adbc-glib/version.h.in, glib/test/test-statement.rb, ruby/lib/adbc/connection.rb, ruby/lib/adbc/loader.rb, ruby/lib/adbc/statement.rb, ruby/test/test-statement.rb
=> feat(glib): add gadbc_statement_bind() and ingest related bindings

ci/linux-packages/Rakefile, ci/linux-packages/yum/almalinux-8/Dockerfile, ci/linux-packages/yum/almalinux-9/Dockerfile, ci/linux-packages/yum/apache-arrow-adbc.spec.in, dev/release/verify-yum.sh
=> feat(rpm): add adbc-driver-flightsql

docs/source/_static/version.js
=> feat(docs): maintain relative URL when switching versions

glib/adbc-glib/statement.c, glib/adbc-glib/statement.h, glib/test/test-statement.rb, ruby/lib/adbc/statement.rb, ruby/test/test-statement.rb
=> feat(glib): add gadbc_statement_bind_stream()

python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/tests/test_dbapi.py, python/adbc_driver_manager/tests/test_lowlevel.py
=> feat(python/adbc_driver_manager): expose StatementGetParameterSchema

glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/test-connection.rb
=> feat(glib): add gadbc_connection_get_table_types()

c/driver/flightsql/sqlite_flightsql_test.cc, c/driver/postgresql/postgresql_test.cc, c/driver/sqlite/sqlite_test.cc, c/driver_manager/adbc_driver_manager_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h, c/validation/adbc_validation_util.h
=> test(c/driver): improve coverage of types in select/ingest

ci/conda_env_python.txt, ci/scripts/python_util.sh, ci/scripts/python_wheel_windows_test.bat, python/adbc_driver_postgresql/pyproject.toml, python/adbc_driver_postgresql/tests/conftest.py, python/adbc_driver_postgresql/tests/test_dbapi.py, python/adbc_driver_postgresql/tests/test_lowlevel.py, python/adbc_driver_postgresql/tests/test_polars.py
=> test(python/adbc_driver_postgres): add polars integration test

java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcConnection.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java
=> fix(java/driver/jdbc): check for existence when getting table schema

glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/test-connection.rb, ruby/lib/adbc/connection.rb, ruby/test/test-connection.rb
=> feat(glib): add gadbc_connection_get_info()

glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/helper.rb, glib/test/test-connection.rb, glib/test/test-statement.rb
=> feat(glib): add gadbc_connection_get_table_schema()

.github/workflows/java.yml, java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlConnectionMetadataTest.java, java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlQuirks.java, java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/package-info.java, java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlConnection.java, java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlDriver.java, java/driver/flight-sql/src/main/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlStatement.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractPartitionDescriptorTest.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractStatementTest.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/ArrowAssertions.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/SqlTestUtil.java
Requires https://github.com/apache/arrow/pull/34776.
Fixes #534.
=> feat(java/driver/flight-sql): allow passing BufferAllocator

glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/test-connection.rb
=> feat(glib): add gadbc_connection_set_read_only()

glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/helper.rb, glib/test/test-connection.rb, glib/test/test-isolation-level.rb, ruby/lib/adbc/loader.rb, ruby/test/test-isolation-level.rb
=> feat(glib): add gadbc_connection_set_isolation_level()

go/adbc/driver/flightsql/flightsql_adbc.go, go/adbc/driver/flightsql/flightsql_adbc_test.go, go/adbc/go.mod, go/adbc/go.sum, go/adbc/validation/validation.go
=> fix(go/adbc/driver/flightsql): use updated authorization header from server

ruby/lib/adbc/statement.rb, ruby/test/test-statement.rb
=> feat(ruby): add support for statement.ingest("table", table)

glib/adbc-glib/error.c
=> feat(glib): add support for no AdbcError error case

.github/workflows/integration.yml, ci/docker/dremio-init.dockerfile, ci/scripts/integration/dremio/bootstrap.sh, docker-compose.yml
=> ci: spin up dremio using docker compose

java/driver/jdbc-validation-derby/src/test/java/org/apache/arrow/adbc/driver/jdbc/derby/DerbyConnectionTest.java, java/driver/jdbc/pom.xml, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDataSourceDatabase.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/JdbcDriver.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/UrlDataSource.java, java/driver/jdbc/src/test/java/org/apache/arrow/adbc/driver/jdbc/JdbcDatabaseTest.java
=> feat(java/driver/jdbc): create AdbcDatabase from javax.sql.DataSource

.github/workflows/java.yml
=> ci: test Java against PostgreSQL

java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlConnectionMetadataTest.java, java/driver/flight-sql-validation/src/test/java/org/apache/arrow/adbc/driver/flightsql/FlightSqlQuirks.java, java/driver/jdbc-validation-derby/src/test/java/org/apache/arrow/adbc/driver/jdbc/derby/DerbyQuirks.java, java/driver/jdbc-validation-postgresql/src/test/java/org/apache/arrow/adbc/driver/jdbc/postgresql/PostgresqlQuirks.java, java/driver/jdbc/src/main/java/org/apache/arrow/adbc/driver/jdbc/ObjectMetadataBuilder.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/AbstractConnectionMetadataTest.java, java/driver/validation/src/main/java/org/apache/arrow/adbc/driver/testsuite/SqlValidationQuirks.java
=> feat(java/driver/jdbc): support catalogPattern in getObjects

glib/Gemfile, glib/adbc-glib/connection.c, glib/adbc-glib/connection.h, glib/test/test-connection.rb, glib/test/test-isolation-level.rb
=> feat(glib): add gadbc_connection_get_objects()

c/CMakeLists.txt, c/driver/common/CMakeLists.txt, c/driver/flightsql/CMakeLists.txt, c/driver/postgresql/CMakeLists.txt, c/driver/sqlite/CMakeLists.txt, c/driver_manager/CMakeLists.txt, ci/scripts/cpp_test.sh, ci/scripts/python_wheel_windows_build.bat
=> ci: make sure cpp_test.sh flags still work for verification

go/adbc/driver/flightsql/flightsql_adbc_test.go, go/adbc/driver/snowflake/driver.go, go/adbc/driver/snowflake/driver_test.go, go/adbc/driver/snowflake/statement.go, go/adbc/go.mod, go/adbc/validation/validation.go
Fixes #631 and cleans up an issue with simultaneous testing.
=> fix(go/adbc/driver/snowflake): some more cleanup

.github/workflows/native-windows.yml, c/cmake_modules/AdbcDefines.cmake, ci/conda_env_cpp.txt, ci/scripts/cpp_build.ps1
=> ci: use bundled googletest on Windows

ci/scripts/python_wheel_windows_build.bat
=> ci: copy Windows wheels to final path

c/driver/common/utils.c, c/validation/adbc_validation.cc
=> refactor(c): fix some build warnings

go/adbc/driver/snowflake/connection.go
=> fix(go/adbc/driver/snowflake): Skip shared dbs that have no data or we can't access

dev/release/utils-prepare.sh, dev/release/verify-release-candidate.sh, r/adbcdrivermanager/DESCRIPTION, r/adbcpostgresql/DESCRIPTION, r/adbcsnowflake/DESCRIPTION, r/adbcsqlite/DESCRIPTION
Ok! I checked the logs to make sure that all the drivers are actually running and passing CMD check. Again, I'm punting on Windows. As part of verification I run the bash verification script on Git bash on Windows which works for the R portion...obviously it's better if it's in the Powershell version but I don't have the bandwidth to make that happen before 0.4.
=> chore(r): Clean up R verification tasks + ensure all drivers are verified

c/driver/snowflake/snowflake_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h, c/validation/adbc_validation_util.cc, go/adbc/driver/snowflake/record_reader.go
=> fix(c/driver/snowflake): fix validation test failures

ci/scripts/python_util.sh, ci/scripts/python_wheel_unix_build.sh
=> ci: re-enable Snowflake driver on aarch64

ci/scripts/python_wheel_windows_build.bat
=> ci: fix DLL names in build script

c/driver/postgresql/connection.cc
Not quite what is being done in https://github.com/apache/arrow-adbc/blob/main/go/adbc/driver/internal/shared_utils.go but I think gets us closer
=> refactor(c/driver/postgresql): Postgres class helper for GetObjects

c/driver_manager/CMakeLists.txt, c/driver_manager/adbc_driver_manager.cc, c/driver_manager/adbc_driver_manager_test.cc, c/driver_manager/adbc_version_100.c, c/driver_manager/adbc_version_100.h, c/driver_manager/adbc_version_100_compatibility_test.cc
=> test(c): add backwards compatibility tests for 1.1.0/1.0.0

r/adbcdrivermanager/R/helpers.R
to keep happy path on a normal indent level.
=> chore(r/adbcdrivermanager): Early exit

.github/workflows/java.yml
=> ci: test later Java versions

c/driver/sqlite/statement_reader.c, python/adbc_driver_flightsql/adbc_driver_flightsql/dbapi.py, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_postgresql/adbc_driver_postgresql/dbapi.py, python/adbc_driver_snowflake/adbc_driver_snowflake/dbapi.py, python/adbc_driver_sqlite/adbc_driver_sqlite/dbapi.py, python/adbc_driver_sqlite/tests/test_dbapi.py
=> feat(python/adbc_driver_manager): add autocommit, executescript

java/core/src/main/java/org/apache/arrow/adbc/core/AdbcException.java, java/core/src/main/java/org/apache/arrow/adbc/core/AdbcStatusCode.java
=> chore(java/core): document the status codes

docs/source/cpp/quickstart.rst, docs/source/cpp/recipe/CMakeLists.txt, docs/source/cpp/recipe/quickstart.cc, docs/source/ext/adbc_cookbook.py
=> docs: add a C++ quickstart

.github/workflows/dev_pr.yml, .github/workflows/dev_pr/title_check.js
=> ci: validate commit format more strictly

go/adbc/pkg/_tmpl/driver.go.tmpl, go/adbc/pkg/flightsql/driver.go, go/adbc/pkg/panicdummy/driver.go, go/adbc/pkg/snowflake/driver.go, python/adbc_driver_flightsql/tests/conftest.py, python/adbc_driver_flightsql/tests/test_dbapi.py
=> fix(go/adbc/pkg): allow ConnectionSetOptions before Init

LICENSE.txt
=> chore: update LICENSE.txt with new Go dependencies

dev/release/utils-prepare.sh
=> chore(dev/release): include Rust, C♯ in version bump

dev/release/verify-release-candidate.sh
=> fix(dev/release): add missing duckdb dependency

.github/workflows/native-unix.yml
=> chore(r): Pin pkgbuild to work around bug in latest released version

csharp/src/Apache.Arrow.Adbc/Apache.Arrow.Adbc.csproj, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs, csharp/src/Apache.Arrow.Adbc/C/NativeLibrary.cs
=> refactor(csharp): cleanup load of imported drivers

go/adbc/driver/flightsql/record_reader.go, go/adbc/driver/snowflake/driver.go, go/adbc/driver/snowflake/record_reader.go
Found these when trying to do some performance testing.
=> fix(go/adbc/driver/snowflake): fix potential deadlock and error handling

ci/scripts/python_wheel_windows_build.bat, dev/release/utils-prepare.sh
=> chore(dev/release): fix file paths used in Windows wheel build

c/cmake_modules/GoUtils.cmake, ci/scripts/python_wheel_windows_build.bat, dev/release/utils-prepare.sh
=> build(c): properly install missing symlink on Windows

go/adbc/driver/flightsql/flightsql_adbc_server_test.go, go/adbc/utils/utils.go
=> fix(go/adbc): fix crash on map type

c/driver/postgresql/connection.cc
Just discovered that libpq provides a function to query the current database; figured easier to use than our current implementation
https://www.postgresql.org/docs/current/libpq-status.html
=> refactor(c/driver/postgresql): Simplify current database querying

.github/workflows/integration.yml, python/adbc_driver_postgresql/tests/test_polars.py
=> test(python/adbc_driver_postgresql): fix Polars integration test

go/adbc/driver/snowflake/record_reader.go
=> fix(go/adbc/driver/snowflake): fix failing integration tests

go/adbc/driver/snowflake/driver_test.go, go/adbc/driver/snowflake/record_reader.go, go/adbc/driver/snowflake/statement.go, go/adbc/go.mod, go/adbc/go.sum
Currently relies on https://github.com/apache/arrow/pull/36569 being merged first.
=> fix(go/adbc/driver/snowflake): Fix integration tests by fixing timestamp handling

CONTRIBUTING.md
=> docs: add more instructions to CONTRIBUTING.md

docs/source/faq.rst
=> docs: add FAQ about SQL dialect

.github/workflows/native-unix.yml, ci/scripts/cpp_recipe.sh, docs/source/cpp/recipe/CMakeLists.txt
=> ci: test C++ recipes

dev/release/02-sign.sh, docs/source/development/releasing.rst
=> chore(dev/release): fix changelog in GitHub release

python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py, python/adbc_driver_snowflake/adbc_driver_snowflake/dbapi.py
=> fix(python/adbc_driver_snowflake): allow connecting without URI

.github/workflows/integration.yml, ci/scripts/python_build.sh
=> ci: don't implicitly install Python driver manager from PyPI

c/driver/snowflake/snowflake_test.cc, c/driver/sqlite/statement_reader.c, python/adbc_driver_manager/tests/test_duckdb.py, python/adbc_driver_postgresql/tests/test_polars.py
=> chore(c/driver/snowflake,python): fix failing typechecks and tests

go/adbc/driver/flightsql/flightsql_adbc_test.go, go/adbc/go.mod, go/adbc/go.sum
=> chore: bump to arrow-go v13

docs/source/cpp/driver_manager.rst, docs/source/driver/installation.rst
=> docs: add APT/Yum repositories to installation pages

.github/workflows/integration.yml, .github/workflows/java.yml, .github/workflows/native-unix.yml, c/driver/postgresql/README.md, c/driver_manager/adbc_driver_manager.cc, ci/docker/flightsql-test.dockerfile, docker-compose.yml, go/adbc/adbc.go, go/adbc/driver/flightsql/cmd/testserver/main.go, go/adbc/drivermgr/adbc_driver_manager.cc, go/adbc/pkg/_tmpl/driver.go.tmpl, go/adbc/pkg/_tmpl/utils.h.tmpl, go/adbc/pkg/flightsql/driver.go, go/adbc/pkg/flightsql/utils.h, go/adbc/pkg/panicdummy/driver.go, go/adbc/pkg/panicdummy/utils.h, go/adbc/pkg/snowflake/driver.go, go/adbc/pkg/snowflake/utils.h, python/adbc_driver_flightsql/tests/conftest.py, python/adbc_driver_flightsql/tests/test_dbapi.py
=> fix(go/adbc): don't include NUL in error messages

dev/release/rat_exclude_files.txt, r/adbcdrivermanager/NEWS.md, r/adbcflightsql/.Rbuildignore, r/adbcflightsql/NEWS.md, r/adbcflightsql/README.Rmd, r/adbcflightsql/README.md, r/adbcflightsql/cran-comments.md, r/adbcpostgresql/.Rbuildignore, r/adbcpostgresql/NEWS.md, r/adbcpostgresql/README.Rmd, r/adbcpostgresql/README.md, r/adbcpostgresql/cran-comments.md, r/adbcsqlite/.Rbuildignore, r/adbcsqlite/NEWS.md, r/adbcsqlite/README.Rmd, r/adbcsqlite/README.md, r/adbcsqlite/cran-comments.md
For #1009, #1010, #1011, and #1012.
Ideally I would have done these chores before 0.6.0; however, because three of these are first-time CRAN submissions that require a human, there will probably be a few more PRs that need to be picked into that branch.
=> chore(r): Package-level CRAN preparation chores

go/adbc/driver/snowflake/driver_test.go, go/adbc/driver/snowflake/record_reader.go
=> fix(go/adbc/driver/snowflake): properly handle time fields

docs/source/driver/snowflake.rst
=> docs: describe how to use SSO with Snowflake

c/driver_manager/adbc_driver_manager.cc, c/driver_manager/adbc_driver_manager_test.cc, go/adbc/drivermgr/adbc_driver_manager.cc
=> fix(c/driver_manager): fix crash when error is null

c/driver/postgresql/connection.cc, c/driver/postgresql/statement.cc, c/driver/sqlite/sqlite.c, c/integration/duckdb/duckdb_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h, go/adbc/driver/snowflake/driver.go, python/adbc_driver_postgresql/tests/test_lowlevel.py, python/adbc_driver_sqlite/tests/test_lowlevel.py
=> fix(c/driver): return NOT_FOUND for GetTableSchema

CONTRIBUTING.md, ci/conda_env_docs.txt, docs/source/conf.py
=> docs: statically render mermaid diagrams to avoid pop-in

.github/workflows/nightly-verify.yml, .github/workflows/packaging.yml
=> ci: don't run cron actions on forks

CONTRIBUTING.md, c/CMakePresets.json
=> build: add basic CMake presets

c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc, c/driver/sqlite/sqlite_test.cc, c/driver_manager/adbc_driver_manager_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h
closes https://github.com/apache/arrow-adbc/issues/1015
=> feat(c/driver/postgresql): Support Ingesting LARGE_STRING types

.github/workflows/java.yml, docker-compose.yml, java/driver/jdbc-validation-mssqlserver/pom.xml
=> ci: enable Java integration tests

c/driver/postgresql/postgres_copy_reader.h, c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc, r/adbcpostgresql/bootstrap.R
=> refactor(c/driver/postgresql): hardcode overflow checks

.github/workflows/integration.yml, .github/workflows/native-unix.yml, .github/workflows/native-windows.yml, .github/workflows/packaging.yml, ci/conda/meta.yaml, ci/conda_env_cpp.txt, ci/docker/python-wheel-manylinux.dockerfile, ci/linux-packages/apt/ubuntu-jammy/Dockerfile, ci/linux-packages/debian/control, ci/linux-packages/debian/rules, dev/release/verify-release-candidate.ps1, dev/release/verify-release-candidate.sh, r/adbcflightsql/tools/download-go.R, r/adbcsnowflake/tools/download-go.R
=> chore(go): bump to 1.19 minimum

c/driver/snowflake/snowflake_test.cc
=> test(c/driver/snowflake): fix or skip failing tests

python/adbc_driver_flightsql/adbc_driver_flightsql/__init__.py
Fixes https://github.com/apache/arrow-adbc/issues/1068.
=> feat(python/adbc_driver_flightsql): add adbc.flight.sql.client_option.authority to DatabaseOptions

ci/conda_env_python.txt, ci/scripts/python_sdist_test.sh, ci/scripts/python_wheel_unix_test.sh, ci/scripts/python_wheel_windows_test.bat, go/adbc/driver/flightsql/cmd/testserver/main.go, go/adbc/driver/flightsql/flightsql_adbc_server_test.go, go/adbc/driver/flightsql/utils.go, python/adbc_driver_flightsql/pyproject.toml, python/adbc_driver_flightsql/tests/test_dbapi.py, python/adbc_driver_flightsql/tests/test_errors.py, python/adbc_driver_manager/adbc_driver_manager/_lib.pxd, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/adbc_driver_manager/_reader.pyx
=> test(python/adbc_driver_flightsql): test Flight SQL & error details

r/adbcdrivermanager/R/helpers.R, r/adbcdrivermanager/man/read_adbc.Rd, r/adbcsqlite/tests/testthat/test-adbcsqlite-package.R
=> feat(r): Implement temporary table option in R driver manager

c/driver/postgresql/postgres_copy_reader.h
Meant to include this in the Handle PR
=> refactor(c/driver/postgresql): Remove unnecessary destructor

c/integration/duckdb/CMakeLists.txt
=> chore(c/integration/duckdb): update to DuckDB 0.9.0

c/driver_manager/adbc_driver_manager.cc, go/adbc/driver/flightsql/flightsql_database.go, go/adbc/drivermgr/adbc_driver_manager.cc
=> feat(go/adbc/driver/flightsql): log new connections

README.md, docs/source/development/nightly.rst, docs/source/driver/installation.rst, docs/source/faq.rst
=> docs: add FAQs about releases

go/adbc/driver/snowflake/driver_test.go, go/adbc/driver/snowflake/record_reader.go
=> fix(go/adbc/driver/snowflake): proper timezone for timestamp_ltz

c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc, python/adbc_driver_postgresql/tests/test_dbapi.py
=> fix(c/driver/postgresql): only clear schema option if needed

docs/source/java/api/adbc_driver_manager.rst, docs/source/java/api/index.rst, docs/source/java/driver_manager.rst, docs/source/java/quickstart.rst
Cleaned up branch of https://github.com/apache/arrow-adbc/pull/1188
=> docs(java): First step into adding Java docs (quickstart, driver manager summary, etc.)

.pre-commit-config.yaml, c/CMakeLists.txt, c/driver/postgresql/CMakeLists.txt, c/driver/postgresql/postgresql_benchmark.cc, ci/build_support/run-test.sh
Pretty hacked together but I think is a workable foundation
=> feat(c/driver/postgresql): INSERT benchmark for postgres

r/adbcpostgresql/src/.gitignore, r/adbcpostgresql/src/common/.gitignore, r/adbcsqlite/src/common/.gitignore
Eventually I would like to find a way for changes in vendored files to better synchronize them; however, they don't change very often so I think this is OK in the meantime.
=> chore(r): Update gitignore to reflect changes to vendored files

.github/workflows/integration.yml
=> ci: test PostgreSQL 16

CONTRIBUTING.md, LICENSE.txt, docs/source/development/releasing.rst
=> chore: regenerate LICENSE.txt

.github/workflows/packaging.yml
=> ci: fix packaging workflow

dev/release/verify-release-candidate.sh
=> fix(dev/release): install missing protobuf for Python test

c/vendor/sqlite3/sqlite3.h, c/vendor/vendor_sqlite3.sh
No particular issue with the current version but I noticed a few releases had gone by since the initial vendor step.
=> chore(c/vendor): Update version of vendored sqlite3 in the repo

go/adbc/driver/snowflake/connection.go
If a share isn't associated with a database then SELECT DATABASE_NAME FROM INFORMATION_SCHEMA.DATABASES call will not list it and therefore it doesn't seem necessary to call SHOW SHARES LIKE '%database_name%' to get a list and check if a DB isn't created for it. Therefore, those checks were removed.
I have created another PR: https://github.com/apache/arrow-adbc/pull/1299 with additional tests for `GetObjects`.
| Test | Before | After | % Improvement |
|-----|---------------------|------------------|-------------------|
| CanGetObjectsAll | 17.6 s | 3 s | 82.5  |
| CanGetObjectsCatalogs | 503 ms | 333 ms | 33.80 | 
| CanGetObjectsCatalogsWithPattern | 421 ms | 369 ms | 12.35 | 
| CanGetObjectsDbSchemas | 4.4 s | 694 ms | 84.36 |
| CanGetObjectsDbSchemasWithPattern | 4 s | 807 ms | 79.825 …
=> perf: GetObjects call is slow even when filters are provided

csharp/src/Client/AdbcConnection.cs, csharp/src/Drivers/BigQuery/BigQueryConnection.cs, csharp/src/Drivers/BigQuery/BigQueryInfoArrowStream.cs, csharp/test/Drivers/BigQuery/ClientTests.cs, csharp/test/Drivers/Snowflake/ClientTests.cs
Adds support for MetaDataCollection, Restrictions, Catalogs, Schemas, TableTypes, Tables and Columns.
=> feat(csharp/Client): Implement support for primary schema collections

go/adbc/driver/snowflake/record_reader.go
=> fix(go/adbc/driver/snowflake): Fix race condition in record reader

csharp/src/Drivers/BigQuery/BigQueryConnection.cs, csharp/test/Drivers/BigQuery/ClientTests.cs
=> fix(csharp/src/Drivers/BigQuery): Fix failure when returning empty schema data from BigQuery

ci/scripts/docs_build.sh
=> docs: fix path in build script

docs/source/driver/postgresql.rst, docs/source/driver/status.rst, docs/source/python/recipe/postgresql.rst, docs/source/python/recipe/postgresql_create_temp_table.py, docs/source/python/recipe/postgresql_get_query_schema.py, python/adbc_driver_manager/adbc_driver_manager/dbapi.py
=> docs: update driver implementation status

c/driver/postgresql/postgresql_test.cc, c/driver/postgresql/statement.cc
=> feat(c/driver/postgresql): set rows_affected appropriately

c/driver/postgresql/connection.cc, c/driver/postgresql/postgresql_test.cc, c/validation/adbc_validation.cc, c/validation/adbc_validation.h, ci/conda_env_cpp_lint.txt, docs/source/python/recipe/postgresql_get_table_schema.py
=> fix(c/driver/postgresql): support catalog arg of GetTableSchema

docs/source/driver/postgresql.rst
=> docs: improve PostgreSQL type support table

docs/source/csharp/index.rst, docs/source/faq.rst, docs/source/index.rst
=> docs: improve landing page

go/adbc/driver/snowflake/driver_test.go
=> test(go/adbc/driver/snowflake): skip failing test

.github/workflows/native-unix.yml, .github/workflows/native-windows.yml, .github/workflows/nightly-verify.yml, .github/workflows/nightly-website.yml, .github/workflows/packaging.yml
This reverts commit e8224bfc8f6748e3a14baf3c9ebb70e72f273829.
Fixes #1424.
=> chore: revert actions/download-artifact from 4 to 3

dev/release/verify-release-candidate.sh
=> fix(dev/release,go): ensure temporary directory removable

ci/scripts/glib_build.sh
=> fix(dev/release,glib): set library path to run example

java/pom.xml
=> chore(java): bump Arrow dependency version

csharp/src/Client/AdbcColumn.cs, csharp/src/Client/AdbcCommand.cs, csharp/src/Client/AdbcDataReader.cs, csharp/src/Client/SchemaConverter.cs, csharp/src/Drivers/BigQuery/BigQueryConnection.cs, csharp/src/Drivers/BigQuery/BigQueryParameters.cs, csharp/src/Drivers/BigQuery/BigQueryStatement.cs, csharp/src/Drivers/BigQuery/readme.md, csharp/src/Drivers/Interop/Snowflake/SnowflakeDriverLoader.cs, csharp/test/Drivers/BigQuery/BigQueryTestConfiguration.cs, csharp/test/Drivers/BigQuery/BigQueryTestingUtils.cs, csharp/test/Drivers/BigQuery/ClientTests.cs
- Adds a new parameter value to exclude the additional calls to obtain table constraints
- Fixes some common nits about spacing
=> feat(csharp/src/Drivers/BigQuery): add override for excluding table constraints

.env, .github/workflows/packaging.yml
=> ci: update vcpkg version to keep up with upstream

go/adbc/driver/flightsql/flightsql_statement.go
=> fix(go/adbc/driver/flightsql): use atomic for progress

c/vendor/nanoarrow/nanoarrow.c, c/vendor/nanoarrow/nanoarrow.h, c/vendor/nanoarrow/nanoarrow.hpp, c/vendor/vendor_nanoarrow.sh
Updates the vendored nanoarrow to the 0.4.0 release!
=> chore(c/vendor): Update vendored nanoarrow

docs/source/faq.rst, docs/source/glossary.rst
=> docs: expand glossary

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/question.yml
=> chore: set up issue/PR templates

.env, docs/source/driver/postgresql.rst, docs/source/driver/sqlite.rst
=> docs: list SQLite/libpq versions in docs

.github/workflows/dev_pr.yml, .github/workflows/dev_pr/milestone.sh
=> ci: set milestone on issues linked to PRs

go/adbc/driver/flightsql/flightsql_adbc_server_test.go
=> test(go/adbc/driver/flightsql): test for errors during polling

.github/workflows/native-unix.yml, ci/scripts/python_build.sh, docker-compose.yml, docs/source/driver/flight_sql.rst, docs/source/python/recipe/flight_sql.rst, docs/source/python/recipe/flightsql_dremio_connect.py, docs/source/python/recipe/flightsql_sqlite_connect.py, docs/source/python/recipe/flightsql_sqlite_options.py, docs/source/python/recipe/index.rst
=> docs: add Flight SQL driver recipes

csharp/src/Client/SchemaConverter.cs
fixes https://github.com/apache/arrow-adbc/issues/1565
=> fix(csharp/src/Client/SchemaConverter): add check for keys on precision and scale

CONTRIBUTING.md
=> docs(java): show how to build with ErrorProne/Checker Framework

c/driver/snowflake/snowflake_test.cc
=> test(go/adbc/driver/snowflake): properly skip tests w/o creds

.github/workflows/nightly-verify.yml, .github/workflows/verify.yml
=> chore(ci): fix verification jobs

docs/source/development/releasing.rst
=> docs: add R packages to post-release checklist

.github/workflows/integration.yml, .github/workflows/native-unix.yml, .github/workflows/nightly-verify.yml, .github/workflows/verify.yml
=> ci: work around ASAN issue

.github/workflows/packaging.yml, csharp/Directory.Build.props, dev/release/post-07-csharp.sh, dev/release/utils-prepare.sh, docs/source/development/releasing.rst
=> chore: set up rest of C#/.NET release process

.github/workflows/native-unix.yml, .github/workflows/packaging.yml
=> ci: use native GitHub Actions M1 runner

docs/source/cpp/recipe/quickstart.cc, docs/source/glossary.rst
=> docs: add glossary terms for statement/connection/database

.github/workflows/dev.yml, .github/workflows/dev_pr.yml, .github/workflows/dev_pr/title_check.py
=> ci: fix PR title checker

ci/conda_env_python.txt
=> ci: require newer node for pyright

.github/workflows/nightly-verify.yml, r/adbcsqlite/src/Makevars.in
See "Newer C++ features with old SDK" in
https://conda-forge.org/docs/maintainer/knowledge_base/
=> chore: fix R build on macOS in verification

csharp/src/Apache.Arrow.Adbc/C/CAdbcDriver.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs
Fixes memory leaks. Resolves #1690.
=> fix(csharp): Resolve memory leaks described by #1690

r/adbcdrivermanager/README.Rmd, r/adbcdrivermanager/README.md, r/adbcpostgresql/README.Rmd, r/adbcpostgresql/README.md, r/adbcsqlite/README.Rmd, r/adbcsqlite/README.md
Just a pass through all the READMEs to generally align them with how people are most likely to interact with them at first glance!
=> docs(r): Update READMEs for R packages

dev/release/utils-prepare.sh
=> fix(dev/release): correct C# version bump regex

.github/workflows/nightly-verify.yml, .github/workflows/verify.yml
=> ci: run verification on M1 runners

docs/source/driver/authoring.rst, docs/source/index.rst
=> docs: add a short page about new drivers

.github/workflows/dev_pr/title_check.py
=> ci: update PR title validity regex

c/driver/postgresql/copy/reader.h, c/driver/postgresql/postgres_type.h, c/driver/postgresql/postgresql_test.cc
Doesn't add anything meaningfully new, just adds tests for types.
Fixes #933.
=> feat(c/driver/postgresql): add money type and test intervals

csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
This change fixes all of the code in CAdbcDriverExporter to have reasonable error-handling. With this change implemented and a build of Arrow that includes the PR https://github.com/apache/arrow/pull/40992 I am able to connect to Spark from Python.
Closes #1751.
=> fix(csharp/src/Apache.Arrow.Adbc): Add support to the C Exporter for converting exceptions into AdbcErrors

csharp/src/Apache.Arrow.Adbc/AdbcConnection.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs, csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs, csharp/src/Drivers/Apache/Impala/ImpalaConnection.cs, csharp/src/Drivers/Apache/Spark/SparkConnection.cs
=> feat(csharp/src/Apache.Arrow.Adbc): Remove AdbcConnection.GetInfo(List<int>)

.github/workflows/native-unix.yml, .github/workflows/native-windows.yml, .github/workflows/nightly-verify.yml, .github/workflows/nightly-website.yml, .github/workflows/packaging.yml
=> ci: bump `actions/{upload-download}-artifact` to `v4`

go/adbc/driver/snowflake/connection.go
As pointed out by @zeroshade [here](https://github.com/apache/arrow-adbc/pull/1722#discussion_r1572883637), we should fix the formatting of the comment.
=> fix(go/adbc/driver/snowflake): comment format

.github/workflows/integration.yml, .github/workflows/native-unix.yml, .pre-commit-config.yaml, c/validation/adbc_validation_util.h, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/tests/test_lowlevel.py, python/adbc_driver_postgresql/benchmarks/benchmarks.py, python/adbc_driver_snowflake/adbc_driver_snowflake/__init__.py
=> chore: update all pre-commit hooks

.github/workflows/dev_pr.yml
=> ci: disallow pings in PR body text

docs/source/driver/postgresql.rst, docs/source/driver/status.rst
=> docs: update driver status table

.github/workflows/dev_pr.yml
=> ci: don't assign milestone for draft PRs

csharp/src/Apache.Arrow.Adbc/AdbcOptions.cs
=> fix(csharp): Change option translation to be case-sensitive

.github/workflows/packaging.yml
=> ci: re-enable arm64v8 build

docs/source/driver/status.rst
=> docs: add warning

.pre-commit-config.yaml, dev/bench/README.md, dev/bench/run_bench.py
Just a starting point to hopefully continue building up some benchmarking suite stuff.
=> chore(dev/bench): add a simple python benchmark script for ADBC

csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs, csharp/test/Apache.Arrow.Adbc.Tests/ImportedDuckDbTests.cs
Fix imported "GetObjects" to preserve a null value for the table types parameter. This enables GetObjects to work properly with the DuckDB driver; is also technically the correct translation.
=> fix(csharp/src/Apache.Arrow.Adbc/C): GetObjects should preserve a null tableTypes parameter value

dev/release/verify-release-candidate.sh
=> chore(dev/release): test latest Python in verify-release-candidate

ci/conda_env_docs.txt, docs/source/python/recipe/postgresql.rst, docs/source/python/recipe/postgresql_pool.py
=> docs: add connection pooling example

ci/scripts/website_build.sh
=> ci: fix test of whether docs are dev or release version

docs/source/development/releasing.rst, docs/source/development/versioning.rst, docs/source/index.rst
=> docs: update release management guide with new versioning scheme

dev/release/verify-release-candidate.sh
=> chore(dev/release): include C# in RC verification

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
=> chore: clarify issue templates

.github/workflows/dev_pr.yml, .github/workflows/dev_pr/body_check.py
=> ci: allow dependabot to ping itself

.pre-commit-config.yaml, python/adbc_driver_manager/adbc_driver_manager/_lib.pxd, python/adbc_driver_manager/adbc_driver_manager/_lib.pyx, python/adbc_driver_manager/adbc_driver_manager/_reader.pyx
=> chore(python): add cython-lint

docs/source/conf.py, docs/source/python/recipe/postgresql.rst, docs/source/python/recipe/postgresql_pandas.py, docs/source/python/recipe/postgresql_polars.py
=> docs: add recipes for using ADBC with Pandas and Polars

go/adbc/drivermgr/wrapper.go, go/adbc/go.mod, go/adbc/go.sum, go/adbc/pkg/_tmpl/driver.go.tmpl, go/adbc/pkg/_tmpl/utils.c.tmpl, go/adbc/pkg/_tmpl/utils.h.tmpl, go/adbc/pkg/flightsql/driver.go, go/adbc/pkg/flightsql/utils.c, go/adbc/pkg/flightsql/utils.h, go/adbc/pkg/panicdummy/driver.go, go/adbc/pkg/panicdummy/utils.c, go/adbc/pkg/panicdummy/utils.h, go/adbc/pkg/snowflake/driver.go, go/adbc/pkg/snowflake/utils.c, go/adbc/pkg/snowflake/utils.h
=> fix(go/adbc/pkg): clean up potential sites where Go GC may be exposed

dev/release/01-prepare.sh, dev/release/02-sign.sh, dev/release/utils-common.sh
=> chore(dev/release): include versions in changelog

dev/release/utils-prepare.sh
=> fix(dev/release): update C# <VersionSuffix> tag

ci/scripts/website_build.sh
=> fix(ci): update website_build.sh for new versioning scheme

.env
=> ci: update Docker images used for wheels

docs/source/python/driver_manager.rst
=> docs: clarify that driver manager is probably not what you want

csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj, csharp/test/Apache.Arrow.Adbc.Tests/Apache.Arrow.Adbc.Tests.csproj
Some more follow ups to https://github.com/apache/arrow-adbc/pull/1999 @CurtHagenlocher
=> chore(deps): bump System.Text.Json from 7.0.4 to 8.0.4 in /csharp/test/SmokeTests/Apache.Arrow.Adbc.SmokeTests

docs/source/driver/flight_sql.rst
=> docs: describe Flight SQL driver options

.github/workflows/nightly-verify.yml, ci/docker/cpp-clang-latest.dockerfile, docker-compose.yml
=> ci: test against latest Clang

csharp/src/Drivers/Apache/Spark/README.md, csharp/src/Drivers/Apache/readme.md
Add documentation for connection properties
* updates existing documentation for Apache/Thrift-based drivers
=> docs(csharp/src/Drivers/Apache/Spark): document connection properties

csharp/src/Drivers/BigQuery/readme.md, csharp/test/Drivers/BigQuery/readme.md
Updates the readme docs for the new parameters.
=> fix(csharp/src/Drivers/BigQuery): update BigQuery documents

go/adbc/driver/bigquery/record_reader.go
=> feat(go/adbc/driver/bigquery): Add schema to reader for BigQuery

docs/source/python/recipe/flight_sql.rst, docs/source/python/recipe/flightsql_sqlite_max_msg_size.py
=> docs: demonstrate `WITH_MAX_MSG_SIZE`

csharp/src/Client/AdbcCommand.cs, csharp/src/Client/AdbcParameter.cs, csharp/test/Apache.Arrow.Adbc.Tests/ClientTests.cs, csharp/test/Drivers/Interop/Snowflake/ClientTests.cs, csharp/test/Drivers/Interop/Snowflake/DriverTests.cs
Add support for parameterized execution through ADO.NET wrapper.
Resolves #2095
=> feat(csharp/src/Client): add support for parameterized execution

ci/conda_env_python.txt, docs/source/python/recipe/postgresql_polars.py, python/adbc_driver_manager/tests/test_lowlevel.py
=> test(python/adbc_driver_manager): relax exception message check

.github/workflows/nightly-verify.yml, ci/docker/python-debug.dockerfile, ci/docker/python-debug.sh, docker-compose.yml
=> ci: test against debug Python interpreter

rust/Cargo.lock, rust/Cargo.toml
=> chore(rust): update package metadata

csharp/src/Drivers/Apache/Spark/README.md, csharp/src/Drivers/Apache/Spark/SparkParameters.cs, csharp/test/Drivers/Apache/Spark/SparkConnectionTest.cs
Added documentation on how to connect to Azure HDInsight Spark Cluster
Removed existing flags related to Azure HDInsight Spark
=> feat(csharp/src/Drivers/Apache/Spark): Azure HDInsight Spark Documentation

csharp/src/Client/AdbcCommand.cs, csharp/src/Client/AdbcParameter.cs, csharp/test/Drivers/Interop/Snowflake/ClientTests.cs
Implements support for mapping DbType.Time and DbType.Decimal. Uses System.Convert to support a larger number of source types.
=> feat(csharp/src/Client): Additional parameter support for DbCommand

csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj, csharp/src/Drivers/FlightSql/Apache.Arrow.Adbc.Drivers.FlightSql.csproj, csharp/test/Drivers/BigQuery/Apache.Arrow.Adbc.Tests.Drivers.BigQuery.csproj
(In place of Dependabot's change.)
=> chore(csharp): bump Google.Cloud.BigQuery.Storage.V1 and System.Net.Http.WinHttpHandler in /csharp

ci/conda_env_glib.txt
Separated this change out from the Mambaforge change as it impacts all builds right now.
=> chore(ci): Pin Conda version of glib

README.md
Add missing hyperlink for CONTRIBUTING.md
=> docs(README.md): add hyperlink for CONTRIBUTING.md

go/adbc/go.mod, go/adbc/go.sum
Resolves https://github.com/apache/arrow-adbc/issues/2295
=> feat(go/adbc/driver/snowflake): update to the latest 1.12.0 gosnowflake driver

dev/release/post-12-website.sh
As suggested at https://github.com/apache/arrow-site/pull/557.
=> chore(dev/release): tweak blog post template

go/adbc/driver/snowflake/connection.go
=> fix(go/adbc/driver/snowflake): update default values for fetch params

java/driver-manager/src/main/java/org/apache/arrow/adbc/drivermanager/AdbcDriverManager.java
=> fix(java/driver-manager): typo

docs/source/faq.rst, docs/source/format/related_work.rst, docs/source/index.rst
See https://github.com/apache/arrow/pull/44313.
=> docs: add related work

.github/workflows/rust.yml
=> ci: simplify Rust builds

.github/CODEOWNERS, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverExporter.cs
This reverts commit https://github.com/apache/arrow-adbc/commit/1d268e9e5071bad9ea860780002df3a361309fdb.
=> chore(csharp/src/Apache.Arrow.Adbc/C): revert #2409

ci/conda_env_glib.txt
=> chore: unpin some GLib/Ruby dependencies

ci/scripts/docs_build.sh, java/pom.xml
=> docs: remove crosslinking to Arrow Javadocs

.github/workflows/dev_adbc.yml, .github/workflows/dev_pr.yml, dev/adbc_dev/__init__.py, dev/adbc_dev/changelog.py, dev/adbc_dev/tests/__init__.py, dev/adbc_dev/tests/test_changelog.py, dev/adbc_dev/title_check.py, dev/release/01-prepare.sh, dev/release/utils-common.sh
=> chore(dev/release): add changelog generator

.env, compose.yaml
=> ci: switch from `docker-compose.yml` to `compose.yaml`

dev/release/post-08-rust.sh, dev/release/utils-prepare.sh, rust/Cargo.lock, rust/Cargo.toml, rust/driver/datafusion/Cargo.toml, rust/driver/snowflake/Cargo.toml
=> chore(rust): publish driver crates

.github/workflows/packaging.yml, ci/linux-packages/Rakefile, ci/linux-packages/apt/ubuntu-noble/Dockerfile
=> feat(ci/linux-packages/apt): add support for Ubuntu 24.04 packages

java/pom.xml
=> docs: crosslink to Arrow Javadocs again

.github/workflows/packaging.yml, ci/scripts/install_python.sh
This cuts the build time from ~1 hour to ~10 minutes
=> ci: use native Linux ARM runner, test Python 3.13

c/include/arrow-adbc/adbc.h, go/adbc/drivermgr/arrow-adbc/adbc.h
Closes https://github.com/apache/arrow-adbc/issues/2248
=> chore(format): add new lines to adbc.h for clarity

c/driver/bigquery/README.md, c/driver/postgresql/README.md, c/driver/snowflake/README.md, c/driver/sqlite/README.md
=> docs: fix references to root CONTRIBUTING.md file

.github/workflows/integration.yml, .github/workflows/native-unix.yml, ci/scripts/remamba.sh
=> ci: add retry to mamba invocations

csharp/src/Drivers/Apache/Apache.Arrow.Adbc.Drivers.Apache.csproj, csharp/src/Drivers/Apache/Hive2/SqlTypeNameParser.cs, csharp/src/Drivers/BigQuery/Apache.Arrow.Adbc.Drivers.BigQuery.csproj
Add support for net472 to the BigQuery driver.
=> feat(csharp/src/Drivers/BigQuery): add support for net472

go/adbc/driver/snowflake/driver.go, go/adbc/driver/snowflake/driver_test.go
=> feat(go/adbc/driver/snowflake): implement WithTransporter driver option

csharp/src/Apache.Arrow.Adbc/C/CAdbcDriverImporter.cs, csharp/src/Client/AdbcCommand.cs, csharp/test/Apache.Arrow.Adbc.Tests/Client/DuckDbClientTests.cs, csharp/test/Apache.Arrow.Adbc.Tests/ImportedDuckDbTests.cs
=> feat(csharp): Add support for Prepare to ImportedStatement and to ADO.NET wrapper

.asf.yaml
As described on the mailing list [1].
[1]: https://lists.apache.org/thread/551ll326to6wflf2hp87vg01w1pq60ll
=> chore: update .asf.yaml to enable GitHub Discussions

.github/workflows/java.yml, .github/workflows/packaging.yml, ci/scripts/java_build.sh, ci/scripts/java_test.sh, ci/scripts/python_util.sh, compose.yaml, java/driver/jni/pom.xml
=> ci: build and test JNI module

rust/core/src/driver_manager.rs, rust/core/src/ffi/types.rs
=> fix(rust/core): remove the Mutex around the FFI driver object

python/adbc_driver_manager/pyproject.toml
=> test(python/adbc_driver_manager): add polars test dependency

csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TCancelOperationReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TCloseOperationReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TExecuteStatementReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TExecuteStatementResp.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TFetchResultsResp.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetCatalogsReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetColumnsReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetCrossReferenceReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetDelegationTokenReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetFunctionsReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetInfoReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetOperationStatusReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetOperationStatusResp.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetPrimaryKeysReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetResultSetMetadataReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetSchemasReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetTableTypesReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetTablesReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TGetTypeInfoReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/THandleIdentifier.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TOpenSessionReq.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TRowSet.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TSessionHandle.cs, csharp/src/Drivers/Apache/Thrift/Service/Rpc/Thrift/TStatus.cs
=> feat(csharp): Sanitize thrift protocol generated code for Databricks driver

csharp/src/Drivers/Databricks/Auth/OAuthClientCredentialsProvider.cs, csharp/test/Drivers/Databricks/Auth/OAuthClientCredentialsProviderTests.cs
Some simple improvements for the OAuthClientCredentialsProvider tests.
1. Users can use uri OR hostname parameter while running this test.
2. Tests expired token triggers a refetch for a non-expired token.
To test out, set `DATABRICKS_TEST_CONFIG_FILE` environment variable to some json file with the following fields:
```
"uri": "...", // can use hostname too
"client_id": "...",
"client_secret": "...",
```
=> feat(csharp/src/Drivers/Databricks): OAuthClientCredentialsProvider test improvements

go/adbc/driver/snowflake/snowflake_database.go
=> fix(go/adbc/driver/snowflake): set log level to not spam console

docs/source/driver/postgresql.rst, docs/source/python/recipe/postgresql.rst, docs/source/python/recipe/postgresql_execute_nocopy.py
For this discussion: https://github.com/apache/arrow-adbc/discussions/2857
=> docs: add USE_COPY recipe and update PostgreSQL docs

c/driver/postgresql/postgres_type.h, c/driver/postgresql/postgres_type_test.cc, python/adbc_driver_postgresql/tests/test_dbapi.py
=> fix(c/driver/postgresql): ingest zoned timestamp as WITH TIME ZONE

csharp/src/Apache.Arrow.Adbc/AdbcConnection11.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcConnection.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDatabase.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcDriver.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcPartitions.cs, csharp/src/Apache.Arrow.Adbc/C/CAdbcStatement.cs, csharp/src/Client/AdbcConnection.cs, csharp/src/Drivers/Apache/Hive2/DecimalUtility.cs, csharp/src/Drivers/Apache/Hive2/README.md, csharp/src/Drivers/Apache/Hive2/SqlTypeNameParser.cs, csharp/src/Drivers/Apache/Impala/README.md, csharp/src/Drivers/Apache/Spark/README.md, csharp/src/Drivers/Apache/Thrift/BitmapUtilities.cs, csharp/src/Drivers/Databricks/DatabricksStatement.cs, csharp/test/Apache.Arrow.Adbc.Tests/TestBase.cs, csharp/test/Drivers/Apache/Common/ClientTests.cs, csharp/test/Drivers/Apache/Common/DateTimeValueTests.cs, csharp/test/Drivers/Apache/Spark/SparkConnectionTest.cs, csharp/test/Drivers/BigQuery/AuthenticationTests.cs, csharp/test/Drivers/Databricks/DatabricksConnectionTest.cs, csharp/test/Drivers/Databricks/DateTimeValueTests.cs, csharp/test/Drivers/Databricks/StatementTests.cs, csharp/test/Drivers/Interop/FlightSql/readme.md, csharp/test/Drivers/Interop/Snowflake/SnowflakeTestingUtils.cs
No change for production code.
Some test code has been changed, but they are unlikely to affect the test.
Closes #2932
=> chore(csharp): fix typo

csharp/src/Drivers/Apache/ApacheUtility.cs, csharp/src/Drivers/Apache/Hive2/HiveServer2Connection.cs, csharp/src/Drivers/Apache/Hive2/HiveServer2Exception.cs, csharp/src/Drivers/Apache/Hive2/HiveServer2Reader.cs, csharp/src/Drivers/Apache/Hive2/HiveServer2Statement.cs
Parses exceptions for AggregateExceptions then flattens the exception to get more valuable messaging.
=> feat(csharp/src/Drivers/Apache): Format HiveServer2Exception messages

dev/bench/README.md, dev/release/verify-release-candidate.sh
=> chore(dev): fix typo

.pre-commit-config.yaml
=> chore: bump cpplint version and disable build/c++17 lint

python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_sqlite/tests/test_dbapi.py
=> feat(python/adbc_driver_manager): simplify autocommit=True

CONTRIBUTING.md
=> docs: update CONTRIBUTING to use mamba consistently

csharp/Directory.Build.props
Am aware of the comment however most if not all the third party notices are for the other languages.
Closes #2891
=> chore(csharp): use license expression

.env, ci/scripts/verify_ubuntu.sh, compose.yaml, dev/release/verify-release-candidate.sh
=> ci: update Maven and .NET download URLs

.github/workflows/nightly-verify.yml, .github/workflows/verify.yml, r/adbcdrivermanager/src/Makevars
=> ci: add `_LIBCPP_DISABLE_AVAILABILITY` as required

ruby/lib/adbc.rb
=> chore(ruby): Use require_relative

compose.yaml
=> chore: remove deprecated attribute from compose

c/vendor/toml++/toml.hpp, c/vendor/vendor_tomlplusplus.sh
=> build(c): fix warnings in vendored toml.hpp

docs/source/driver/snowflake.rst
=> docs: improve documentation about URI creation

ci/scripts/python_util.sh, ci/scripts/python_wheel_unix_build.sh, ci/scripts/python_wheel_unix_relocate.sh
=> build(python): keep building driver manager on manylinux2014

go/adbc/drivermgr/wrapper_sqlite_test.go, go/adbc/ext.go
=> feat(go/adbc): add GetDriverInfo helper

csharp/src/Drivers/Databricks/Reader/CloudFetch/CloudFetchResultFetcher.cs, csharp/test/Drivers/Databricks/E2E/CloudFetch/CloudFetchResultFetcherTest.cs
The CloudFetchResultFetcher.StopAsync() method could not properly cancel ongoing fetch operations because:
Missing cancellation token chaining: FetchNextResultBatchAsync created timeout-only tokens using ApacheUtility.GetCancellationToken() and ignored the external cancellation token passed from StopAsync()
Test reliability issues: Unit tests were failing because StopAsync() calls weren't actually cancelling background operations
Resource management: Background fetch operations could continue running even after disposal
Fixed cancellation token chaining in FetchNextResultBatchAsync:
Replace single timeout token with proper linked cancellation tokens
Combine both timeout cancellation and external cancellation using CancellationTokenSource.CreateLinkedTokenSource()
Now operations respond to …
=> fix(csharp/src/Drivers): Fix cloud fetch cancel/timeout mechnism

csharp/src/Apache.Arrow.Adbc/Tracing/TracingReader.cs, csharp/src/Drivers/Databricks/DatabricksConnection.cs, csharp/src/Drivers/Databricks/Reader/DatabricksCompositeReader.cs, csharp/test/Drivers/Databricks/Unit/DatabricksCompositeReaderUnitTests.cs
Adds unit tests for DatabricksCompositeReader
Includes small changes to the concrete classes for testability
=> fix(csharp/src/Drivers/Databricks): DatabricksCompositeReader unit tests

c/cmake_modules/AdbcDefines.cmake, c/driver/sqlite/statement_reader.h, compose.yaml
=> build(c): run nightly clang with `-Wdocumentation`

dev/release/verify-release-candidate.sh
=> ci: work around rustdoc and conda/macOS issue

java/driver/jdbc-validation-derby/pom.xml
Should have included this in #3334.
=> chore(java): update comment about java 8 and derby

csharp/src/Drivers/Databricks/readme.md
Fixing the Databricks Driver readme to list all the available config properties customer can tune
=> fix(csharp/src/Drivers/Databricks): Fix Databricks readme

java/driver/jni/src/main/java/org/apache/arrow/adbc/driver/jni/JniDriver.java, java/driver/jni/src/test/java/org/apache/arrow/adbc/driver/jni/JniDriverTest.java
=> feat(java/driver/jni): pass through all initial params

c/driver_manager/adbc_driver_manager.cc, c/driver_manager/adbc_driver_manager_test.cc, python/adbc_driver_manager/tests/test_dbapi.py, python/adbc_driver_manager/tests/test_lowlevel.py
=> feat(c/driver_manager): improve error reporting for manifests

python/adbc_driver_manager/adbc_driver_manager/_lib.pyx
=> fix(python/adbc_driver_manager): mark calls with nogil

docs/source/format/driver_manifests.rst, docs/source/glossary.rst
Follow on to #3388 
This PR makes a few improvements to the driver_manifests.rst page. Mainly, it reworks a bit of the start for clarity. I also found some issues later down in the doc which I've fixed as well.
=> docs: minor improvements to driver_manifests.rst

c/driver/sqlite/sqlite.cc, c/driver/sqlite/sqlite_test.cc, c/driver/sqlite/statement_reader.c, c/driver/sqlite/statement_reader.h, python/adbc_driver_manager/adbc_driver_manager/__init__.py, python/adbc_driver_manager/adbc_driver_manager/_dbapi_backend.py, python/adbc_driver_manager/adbc_driver_manager/dbapi.py, python/adbc_driver_manager/tests/test_dbapi.py, python/adbc_driver_manager/tests/test_dbapi_polars_nopyarrow.py
=> feat(c/driver/sqlite,python/adbc_driver_manager): bind params by name

.github/workflows/java.yml, .github/workflows/packaging.yml, ci/scripts/java_build.sh, compose.yaml, java/CMakeLists.txt, java/driver/jni/src/main/resources/META-INF/LICENSE, java/driver/jni/src/main/resources/META-INF/NOTICE
=> ci: build JNI artifacts

docs/source/driver/bigquery.rst, docs/source/index.rst
Closes https://github.com/apache/arrow-adbc/issues/3432
=> docs: add very basic bigquery drivers page

csharp/src/Drivers/Databricks/readme.md
Add instruction of setting up mitm proxy for debugging purpose.
=> docs(csharp/src/Drivers/Databricks): add mitm proxy instruction

.github/workflows/native-unix.yml
https://github.com/docker/compose/issues/10596
=> ci: fix spurious failure of docker-compose
